- platform: template
  sensors:
    sun_up:
      entity_id:
        - sun.sun
      value_template: >-
        {{ is_state("sun.sun", "above_horizon") }}
      icon_template: >-
        {% if is_state("binary_sensor.sun_up", "on") %}
          mdi:weather-sunset-up
        {% else %}
          mdi:weather-sunset-down
        {% endif %}
