- platform: bayesian
  name: user0001_status
  prior: 0.25
  probability_threshold: 0.91
  device_class: 'presence'
  observations:
    - entity_id: 'device_tracker.user0001_phone'
      prob_given_true: 0.9
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.user0001_phone_wifi'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.user0001_phone_bt'
      prob_given_true: 0.8
      prob_given_false: 0.4
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.e4e4abf03ecc'
      prob_given_true: 0.7
      prob_given_false: 0.4
      platform: 'state'
      to_state: 'home'
- platform: bayesian
  name: user0002_status
  prior: 0.25
  probability_threshold: 0.91
  device_class: 'presence'
  observations:
    - entity_id: 'device_tracker.user0002_phone'
      prob_given_true: 0.9
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.user0002_phone_wifi'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.user0002_phone_bt'
      prob_given_true: 0.8
      prob_given_false: 0.4
      platform: 'state'
      to_state: 'home'
- platform: bayesian
  name: user0003_status
  prior: 0.25
  probability_threshold: 0.91
  device_class: 'presence'
  observations:
    - entity_id: 'device_tracker.user0003_phone'
      prob_given_true: 0.9
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.user0003_phone_wifi'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.user0003_phone_bt'
      prob_given_true: 0.8
      prob_given_false: 0.4
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.cc4463abc980'
      prob_given_true: 0.7
      prob_given_false: 0.4
      platform: 'state'
      to_state: 'home'
- platform: bayesian
  name: user0004_status
  prior: 0.25
  probability_threshold: 0.91
  device_class: 'presence'
  observations:
    - entity_id: 'device_tracker.user0004_phone'
      prob_given_true: 0.9
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.user0004_phone_wifi'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.user0004_phone_bt'
      prob_given_true: 0.8
      prob_given_false: 0.4
      platform: 'state'
      to_state: 'home'
