# binary_sensor.yaml ---
# 
# Filename: ping.yaml
# Description: 
# Author: Geoff S Derber
# Maintainer: 
# Created: Sun Mar  3 12:12:38 2019 (-0500)
# Version: 
# Package-Requires: ()
# Last-Updated: Sun Jun  9 11:13:06 2019 (-0400)
#           By: Geoff S Derber
#     Update #: 4
# URL: 
# Doc URL: 
# Keywords: 
# Compatibility: 
# 
# 

# Commentary: 
# 
# 
# 
# 

# Change Log:
# 
# 
# 
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with GNU Emacs.  If not, see <https://www.gnu.org/licenses/>.
# 
# 

# Code:

# ======================================================================
#
# Network Equipment
#
# ======================================================================
- platform: ping
  host: 10.0.0.1
  name: Cerberus
  count: 1              # Number of packets to send
  #scan_interval: 5     # Polling Interval

#- platform: ping
#  host: 10.0.0.2
#  name: Hydra
#  count: 1              # Number of packets to send
  #scan_interval: 5     # Polling Interval

- platform: ping
  host: 192.168.0.1
  name: Death Star
  count: 1              # Number of packets to send
  #scan_interval: 5     # Polling Interval

#- platform: ping
#  host: 192.168.0.4
#  name: Executor
#  count: 1              # Number of packets to send
  #scan_interval: 5     # Polling Interval

#- platform: ping
#  host: 192.168.0.5
#  name: Iron Fist
#  count: 1              # Number of packets to send
  #scan_interval: 5     # Polling Interval

#- platform: ping
#  host: 10.0.0.3
#  name: Chimera
#  count: 1              # Number of packets to send
  #scan_interval: 5     # Polling Interval

#- platform: ping
#  host: 192.168.0.6
#  name: Lusankya
#  count: 1              # Number of packets to send
  #scan_interval: 5     # Polling Interval

- platform: ping
  host: 10.0.0.41
  name: wap1
  count: 1              # Number of packets to send
  #scan_interval: 5     # Polling Interval

- platform: ping
  host: 10.0.0.42
  name: wap2
  count: 1              # Number of packets to send
  #scan_interval: 5     # Polling Interval

- platform: ping
  host: 10.0.0.43
  name: wap3
  count: 1              # Number of packets to send
  #scan_interval: 5     # Polling Interval

- platform: ping
  host: 10.0.0.44
  name: wap4
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

# ======================================================================
#
# Olympus Servers
#
# ======================================================================
- platform: ping
  host: 10.0.1.20
  name: Angelia
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

- platform: ping
  host: 10.0.1.14
  name: Aphrodite
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

- platform: ping
  host: 10.0.1.11
  name: Apollo
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

- platform: ping
  host: 10.0.2.2
  name: Ariadne
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

- platform: ping
  host: 10.0.1.42
  name: Calliope
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

- platform: ping
  host: 10.0.1.18
  name: Calypso
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

- platform: ping
  host: 10.0.1.12
  name: Demeter
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

- platform: ping
  host: 10.0.2.1
  name: Dionysus
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

- platform: ping
  host: 10.0.1.16
  name: Hades
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

- platform: ping
  host: 10.0.1.2
  name: Hera
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

- platform: ping
  host: 10.0.1.19
  name: Hestia
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

- platform: ping
  host: 10.0.1.15
  name: Iris
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

- platform: ping
  host: 10.0.1.41
  name: Mnemosyne
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

- platform: ping
  host: 10.0.1.5
  name: Morpheus
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

- platform: ping
  host: 10.0.1.13
  name: Nyx
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

- platform : ping
  host: 10.0.1.17
  name: Persephone
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

- platform: ping
  host: 10.0.1.1
  name: Zeus
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

# ======================================================================
#
# SWG Servers
#
# ======================================================================
- platform: ping
  host: 192.168.1.2
  name: Defiance
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

- platform: ping
  host: 192.168.2.2
  name: Endeavor
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

# - platform: ping
#   host: 192.168.1.4
#   name: Home One
#   count: 1               # Number of packets to send
#   #scan_interval: 5       # Polling Interval

- platform: ping
  host: 192.168.1.1
  name: Independence
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

- platform: ping
  host: 192.168.1.3
  name: Liberty
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

#- platform: ping
#  host: 192.168.3.1
#  name: Millenium Falcon
#  count: 1               # Number of packets to send
#scan_interval: 5       # Polling Interval

- platform: ping
  host: 192.168.2.1
  name: Redemption
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

- platform: template
  sensors:
    user0001_laptop:
      device_class: connectivity
      value_template: >-
        {{ is_state('device_tracker.user0001_laptop_wifi', 'home') }}
    user0002_laptop:
      device_class: connectivity
      value_template: >-
        {{ is_state('device_tracker.user0002_laptop_1_wifi', 'home')
        or is_state('device_tracker.user0002_laptop_2_wifi', 'home') }}
    aether:
      friendly_name: "Aether"
      device_class: connectivity
      value_template: "{{ is_state('binary_sensor.wap1','on') }}"
      icon_template: >-
        {% if is_state('binary_sensor.wap1', 'on') %}
          mdi:access-point-network
        {% else %}
          mdi:access-point-network-off
        {% endif %}
    chaos:
      friendly_name: "Chaos"
      device_class: connectivity
      value_template: "{{ is_state('binary_sensor.wap2','on') }}"
      icon_template: >-
        {% if is_state('binary_sensor.wap2', 'on') %}
          mdi:access-point-network
        {% else %}
          mdi:access-point-network-off
        {% endif %}
    lelantos:
      friendly_name: "Lelantos"
      device_class: connectivity
      value_template: "{{ is_state('binary_sensor.wap3','on') }}"
      icon_template: >-
        {% if is_state('binary_sensor.wap3', 'on') %}
          mdi:access-point-network
        {% else %}
          mdi:access-point-network-off
        {% endif %}
    uranus:
      friendly_name: "Uranus"
      device_class: connectivity
      value_template: "{{ is_state('binary_sensor.wap4','on') }}"
      icon_template: >-
        {% if is_state('binary_sensor.wap4', 'on') %}
        mdi:access-point-network
        {% else %}
        mdi:access-point-network-off
        {% endif %}

# ======================================================================
#
# Internet of Things
#
# ======================================================================
- platform: ping
  host: 10.3.1.1
  name: Hue (Main Floor)
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

- platform: ping
  host: 10.3.1.2
  name: Hue (Basement)
  count: 1               # Number of packets to send
  #scan_interval: 5       # Polling Interval

#
# ping.yaml ends here
