- id: '1574735776519'
  alias: Turn on lights to correct color value
  description: ''
  trigger: []
  condition: []
  action:
  - data:
      entity_id: light.entity
    service: light.turn_on
- id: '1576627874516'
  alias: Christmas Lights On
  description: Turn on outdoor Christmas Lights
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - device_id: 6ec8830ea56d4efaae8b5cf62180794c
    domain: switch
    entity_id: switch.jasco_products_14284_outdoor_smart_switch_switch
    type: turn_on
- id: '1576628018411'
  alias: Christmas Lights Off
  description: ''
  trigger:
  - at: '22:00:00'
    platform: time
  condition: []
  action:
  - device_id: 6ec8830ea56d4efaae8b5cf62180794c
    domain: switch
    entity_id: switch.jasco_products_14284_outdoor_smart_switch_switch
    type: turn_off
- id: '1576717665597'
  alias: Daily Reboot
  description: ''
  trigger:
  - at: '4:00:00'
    platform: time
  condition: []
  action:
  - service: hassio.host_reboot
- id: '1577154074008'
  alias: test
  description: ''
  trigger:
  - entity_id: sensor.light_master_lamp_2_xy_color
    platform: state
    to: (0.17, 0.7)
  condition: []
  action:
  - entity_id: input_boolean.special_migraine_mode
    service: input_boolean.turn_on
- id: '1577189016507'
  alias: 'Christmas Lights On: Morning'
  description: ''
  trigger:
  - event: sunrise
    offset: '-1:30:00'
    platform: sun
  condition: []
  action:
  - entity_id: switch.jasco_products_14284_outdoor_smart_switch_switch
    service: switch.turn_on
- id: '1577189063657'
  alias: 'Christmas Lights Off: Morning'
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - entity_id: switch.jasco_products_14284_outdoor_smart_switch_switch
    service: switch.turn_off
