---
# ==================================================================================================
#
# Filename: configuration.yaml
# Description: Home Assistant Configuration Files
# Author: Hearth Minion
# Created: Sun Jan 13, 2019 12:21:16 (-0500)
# Home Assistant Version: 2024.1.3
# Version: 2024.01.1
# Last-Updated: Wed Jan 25, 2024 10:30 (-0500)
# URL: https://github.com/hearthminion/homeassistant_config/
#
# ==================================================================================================
# Code:

# ======================================================================
#
# Homeassistant:
#
# Main Home assistant options
#
# ======================================================================
homeassistant:
  # Customization file
  # Note: Having this file anywhere else disables editing from the UI
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

  packages: !include_dir_named packages

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - !secret trusted_net1
        - !secret trusted_net2
        - !secret trusted_net4
      allow_bypass_login: true
#    - type: command_line
#      command:
    - type: homeassistant

# ==================================================================================================
#
# Default Config Replacement
#
# I do not want everything enabled from default config.  Items not used that are part of
# default_config:
#   - assist_pipeline
#   - backup (I have this done via two git repos, the yaml config repo available via github, and
#            a private repo for the .storage directory)
#   - cloud
#   - conversation (I may enable this in the future)
#   - dhcp
#   - energy
#   - hardware
#   - stream
#   - usb
#   - webhook
#
# Documentation: https://www.home-assistant.io/integrations/default_config/
#
# ==================================================================================================
automation: !include automations.yaml
#assist_pipeline:
#backup:
bluetooth:
#cloud: Disabled
config:
#conversation:
counter:
#dhcp:
#energy:
frontend:
#hardware:
history:
homeassistant_alerts:
image_upload:
input_boolean: !include includes/input_boolean.yaml
input_button:
input_datetime: !include includes/input_datetime.yaml
input_number:
input_select:
input_text:
logbook:
logger: !include includes/logger.yaml
map:
media_source:
mobile_app:
my:
network:
person:
schedule:
scene: !include scenes.yaml
script: !include scripts.yaml
ssdp:
#stream:
system_health:
tag:
timer: !include includes/timers.yaml
#usb:
#webhook:
zeroconf:
zone:

# ==================================================================================================
#
# Old Style Configurations
#
# These are used because the new configurations for automations and scenes do not allow for
# comments explaining the "why" and thought process behind the automations.  Most of my automations
# are templated with the new method (automations.yaml) then moved here to add the explanations.
#
# ==================================================================================================
automation old: !include_dir_merge_list includes/automations/
scene old: !include_dir_merge_list includes/scenes/

# ==================================================================================================
#
# Non 'default_config' entries
#
# ==================================================================================================
mqtt: !include includes/mqtt.yaml
recorder: !include includes/recorder.yaml
sensor: !include_dir_merge_list includes/sensors/
system_log:
  max_entries: 50
  fire_event: false
template: !include_dir_merge_list includes/templates/

device_tracker:
  # - platform: bluetooth_tracker
  #   consider_home: 120
  #   interval_seconds: 40

owntracks:
  max_gps_accuracy: 200
  waypoints: true
  wayponts_whitelist:
    - user0001
    - user0002
  mqtt_topic: "owntracks/#"
  events_only: false

api:
lovelace: !include includes/lovelace.yaml

geo_location:
  - platform: usgs_earthquakes_feed
    feed_type: 'past_day_all_earthquakes'
    radius: 300

#vacuum: !include includes/vacuum.yaml

# ======================================================================
# configuration.yaml ends here
...
