# ======================================================================
#
# configuration.yaml ---
#
# Filename: configuration.yaml
# Description: Home Assistant Configuration Files
# Author: Geoff S Derber
# Maintainer:
# Created: Sun Jan 13 12:21:16 2019 (-0500)
# Home Assistant Version: 0.117.1
# Version: 0.117.0
# Package-Requires: ()
# Last-Updated: Sun Nov  2 9:50 2020 (-0500)
#           By: Geoff S Derber
#     Update #: 64
# URL: https://github.com/hearthminion/homeassistant/
# Doc URL: 
# Keywords: Home Assistant
# Compatibility: 
# 
# 
# Commentary: 
# 
# 
# 
# 
# Change Log:
# 
# 
# 
# License:
# 
# 
# ======================================================================
# Code:


# ======================================================================
#
# Homeassistant:
#
# Main Home assistant options
#
# ======================================================================
homeassistant:
  # Customization file
  # Note: Having this file anywhere else disables editing from the UI
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

  packages: !include_dir_named packages

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - !secret trusted_net1
        - !secret trusted_net2
      allow_bypass_login: true
#    - type: command_line
#      command:
    - type: homeassistant

default_config:

automation old: !include_dir_merge_list includes/automations/
binary_sensor: !include_dir_merge_list includes/binary_sensors/
group: !include_dir_merge_named includes/groups/
scene old: !include_dir_merge_list includes/scenes/
sensor: !include_dir_merge_list includes/sensors/
switch: !include_dir_merge_list includes/switches/
timer: !include includes/timers.yaml
discovery: !include includes/system/discovery.yaml
history: !include includes/system/history.yaml
logger: !include includes/system/logger.yaml
recorder: !include includes/system/recorder.yaml
system_log: !include includes/system/system_log.yaml

calendar:
  - platform: caldav
    username: !secret caldav_username
    password: !secret caldav_password
    url: !secret caldev_url

device_tracker:
  - platform: bluetooth_tracker
    consider_home: 120
    interval_seconds: 40

  # Re-enable nmap tracker
  # Add "interval_seconds" parameter to slow down frequency of scans
  # See:
  #   - https://github.com/home-assistant/core/issues/33281
  #   - https://community.home-assistant.io/t/0-107-6-broke-device-tracker/181234/
  #
  # Alternatively, reduce the size of number of hosts to scan
  - platform: nmap_tracker
    hosts: 10.0.99.0/24
    home_interval: 3

  - platform: ping
    hosts:
      user0001_laptop_wifi: 10.0.2.41
      user0002_laptop_1_wifi: 10.0.2.42
      user0002_laptop_2_wifi: 10.0.2.43
    count: 1
    interval_seconds: 60

owntracks:
  max_gps_accuracy: 200
  waypoints: true
  wayponts_whitelist:
    - user0001
    - user0002
  mqtt_topic: "owntracks/#"
  events_only: false

weather:
  - platform: darksky
    api_key: !secret darksky

geo_location:
  - platform: usgs_earthquakes_feed
    feed_type: 'past_day_all_earthquakes'
    radius: 300

climate:
  - platform: honeywell
    region: us
    username: !secret honeywell_user
    password: !secret honeywell_pass
    scan_interval: 600

updater:
  reporting: false
  include_used_components: false

lovelace: !include includes/lovelace.yaml

ios:

# ======================================================================
# configuration.yaml ends here
