# ======================================================================
#
# configuration.yaml ---
#
# Filename: configuration.yaml
# Description: Home Assistant Configuration Files
# Author: Geoff S Derber
# Maintainer:
# Created: Sun Jan 13 12:21:16 2019 (-0500)
# Home Assistant Version: 0.108.8
# Version: 0.108.17
# Package-Requires: ()
# Last-Updated: Sun Feb  2 16:40:52 2020 (-0500)
#           By: Geoff S Derber
#     Update #: 64
# URL: https://github.com/hearthminion/homeassistant/
# Doc URL: 
# Keywords: Home Assistant
# Compatibility: 
# 
# 

# Commentary: 
# 
# 
# 
# 

# Change Log:
# 
# 
# 
# License:
# 
# 
# ======================================================================
# Code:


# ======================================================================
#
# Homeassistant:
#
# Main Home assistant options
#
# ======================================================================
homeassistant:
  name: !secret ha_name
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret ha_elevation
  unit_system: !secret ha_unit_system
  time_zone: !secret ha_time_zone
  # Customization file
  # Note: Having this file anywhere else disables editing from the UI
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

  packages: !include_dir_named packages

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - !secret trusted_net1
        - !secret trusted_net2
      allow_bypass_login: true
#    - type: command_line
#      command:
    - type: homeassistant

# Automations file
# Note: Having this file anywhere else disables editing from the UI
automation: !include automations.yaml
automation old: !include_dir_merge_list includes/automations/
binary_sensor: !include_dir_merge_list includes/binary_sensors/
group: !include_dir_merge_named includes/groups/
input_boolean: !include_dir_merge_named includes/input_boolean/
input_select: !include_dir_merge_named includes/input_select/
# Scenes file
# Note: Having this file anywhere else disables editing from the UI
scene: !include scenes.yaml
scene old: !include_dir_merge_list includes/scenes/
sensor: !include_dir_merge_list includes/sensors/
switch: !include_dir_merge_list includes/switches/
timer: !include includes/timers.yaml
discovery: !include includes/system/discovery.yaml
logger: !include includes/system/logger.yaml
recorder: !include includes/system/recorder.yaml
system_log: !include includes/system/system_log.yaml
zone: !include includes/zones.yaml

device_tracker:
  - platform: bluetooth_tracker
    consider_home: 120
    interval_seconds: 40

  - platform: nmap_tracker
    hosts:
      - 10.0.99.0/24
      - 10.7.77.0/24
      - 10.0.2.41-43
    home_interval: 3

# ======================================================================
#
# Speedtest
#
# ======================================================================
speedtestdotnet:
  scan_interval:
    days: 0
    hours: 1
    minutes: 0
    seconds: 0
    milliseconds: 0
  monitored_conditions:
    - ping
    - download
    - upload

sun: # Track the sun

weather:
  - platform: darksky
    api_key: !secret darksky

geo_location:
  - platform: usgs_earthquakes_feed
    feed_type: 'past_day_all_earthquakes'
    radius: 300

climate:
  - platform: honeywell
    region: us
    username: !secret honeywell_user
    password: !secret honeywell_pass
    scan_interval: 600

# ======================================================================
#
# Only listen on localhost.  Nginx acts as a proxy for outside access.
#
# With Nginx acting as proxy, ssl certificate is not needed.
#
# Temporarily disabled:
#   https://community.home-assistant.io/t/dont-use-server-host-options-with-hass-io/176372
#
# ======================================================================
http:
  base_url: localhost
  server_port: 8123
  #ssl_certificate:
  #ssl_key:

updater:
  reporting: false
  include_used_components: false

config: # Enables configuration UI
map:    # Enables a map showing the location of tracked devices

frontend: # Enables the frontend
  themes: !include_dir_merge_named themes/
  javascript_version: latest
lovelace: !include includes/lovelace.yaml

# ======================================================================
#
# Services
#
# ======================================================================

ios:
system_health:
zeroconf:
zwave:
  usb_path: /dev/ttyACM0
  device_config: !include zwave_device_config.yaml
  network_key: !secret zwave_key

# ======================================================================
# configuration.yaml ends here
