# ==================================================================================================
#
# configuration.yaml ---
#
# Filename: configuration.yaml
# Description: Home Assistant Configuration Files
# Author: Geoff S Derber
# Maintainer:
# Created: Sun Jan 13 12:21:16 2019 (-0500)
# Home Assistant Version: 2021.4.4
# Version: 2021.10.0
# Package-Requires: ()
# Last-Updated: Fri Oct  15 10:27 2021 (-0500)
#           By: Geoff S Derber
#     Update #: 66
# URL: https://github.com/hearthminion/homeassistant/
# Doc URL: 
# Keywords: Home Assistant
# Compatibility: 
# 
# 
# Commentary: 
# 
# 
# 
# 
# 
# 
# 
# License:
# 
# 
# ==================================================================================================
# Code:


# ======================================================================
#
# Homeassistant:
#
# Main Home assistant options
#
# ======================================================================
homeassistant:
  # Customization file
  # Note: Having this file anywhere else disables editing from the UI
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

  packages: !include_dir_named packages

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - !secret trusted_net1
        - !secret trusted_net2
      allow_bypass_login: true
#    - type: command_line
#      command:
    - type: homeassistant

# ==================================================================================================
#
# Default Config Replacement
#
# I do not want everything enabled from default config.  Items not used that are part of
# default_config:
#   - cloud
#
# Documentation: https://www.home-assistant.io/integrations/default_config/
#
# ==================================================================================================
automation: !include automations.yaml
#cloud: Disabled
config:
counter:
frontend:
history: !include includes/system/history.yaml
image:
input_boolean:
input_datetime:
input_number:
input_select:
input_text:
logbook:
map:
media_source:
mobile_app:
person:
scene: !include scenes.yaml
script: !include scripts.yaml
ssdp:
sun:
system_health:
tag:
timer: !include includes/timers.yaml
updater:
zeroconf:
zone:

# Not part of default_config, but appears to need to be explicitely set if default_config is not
discovery: !include includes/system/discovery.yaml
  
# ==================================================================================================
#
# Old Style Configurations
#
# These are used because the new configurations for automations and scenes do not allow for
# comments explaining the "why" and thought process behind the automations.  Most of my automations
# are templated with the new method (automations.yaml) then moved here to add the explanations.
#
# ==================================================================================================
automation old: !include_dir_merge_list includes/automations/
scene old: !include_dir_merge_list includes/scenes/

binary_sensor: !include_dir_merge_list includes/binary_sensors/
group: !include_dir_merge_named includes/groups/
logger: !include includes/system/logger.yaml
recorder: !include includes/system/recorder.yaml
sensor: !include_dir_merge_list includes/sensors/
switch: !include_dir_merge_list includes/switches/
system_log: !include includes/system/system_log.yaml
template: !include_dir_merge_list includes/templates/

# calendar:
#   - platform: caldav
#     username: !secret caldav_username
#     password: !secret caldav_password
#     url: !secret caldav_url
#     verify_ssl: false
#     custom_calendars:
#       - name: Migraine
#         calendar: "Migraine Log"
#         search: ".*"

device_tracker:
  - platform: bluetooth_tracker
    consider_home: 120
    interval_seconds: 40

  - platform: ping
    hosts:
      user0001_laptop_wifi: 10.0.2.41
      user0002_laptop_1_wifi: 10.0.2.42
      user0002_laptop_2_wifi: 10.0.2.43
    count: 1
    interval_seconds: 60

owntracks:
  max_gps_accuracy: 200
  waypoints: true
  wayponts_whitelist:
    - user0001
    - user0002
  mqtt_topic: "owntracks/#"
  events_only: false

weather:
  - platform: pirateweather
    api_key: !secret pirateweather

geo_location:
  - platform: usgs_earthquakes_feed
    feed_type: 'past_day_all_earthquakes'
    radius: 300

lovelace: !include includes/lovelace.yaml

# ======================================================================
# configuration.yaml ends here
