# ======================================================================
#
# ui-lovelace.yaml
#
# ======================================================================
title: Home

views:
  - !include lovelace/00-summary.yaml
#  - !include lovelace/10-home.yaml
#  - !include lovelace/20-network.yaml
  - !include lovelace/21-networkalt.yaml
  - !include lovelace/25-zwave.yaml
  - !include lovelace/30-internet.yaml
  - !include lovelace/40-weather.yaml
  - !include lovelace/50-homeassistant.yaml
  - !include lovelace/60-user0001.yaml
  - !include lovelace/61-user0002.yaml
# ======================================================================
#
# Misc Views
#
# ======================================================================

# ======================================================================
#
#
#
# ======================================================================

# ======================================================================
# End ui-lovelace.yaml
