# ======================================================================
#
# ui-lovelace.yaml
#
# ======================================================================
custom_header:
  compact_mode: true
  header_text: '{{ hours24LZ }}:{{ minutesLZ }}'

title: Home

views:
  - !include lovelace/00-summary.yaml
#  - !include lovelace/10-home.yaml
#  - !include lovelace/20-network.yaml
  - !include lovelace/21-networkalt.yaml
  - !include lovelace/30-internet.yaml
  - !include lovelace/40-weather.yaml
  - !include lovelace/50-homeassistant.yaml

# ======================================================================
#
# Misc Views
#
# ======================================================================

# ======================================================================
#
#
#
# ======================================================================

# ======================================================================
# End ui-lovelace.yaml
