# External Resources
resources:
  - url: /community_plugin/atomic_calendar/atomic_calendar.js
    type: module
  - url: /community_plugin/banner-card/banner-card.js
    type: module
  - url: /community_plugin/bar-card/bar-card.js
    type: js
  - url: /community_plugin/bignumber-card/bignumber-card.js
    type: js
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/button-entity-row/button-entity-row.js
    type: js
  - url: /community_plugin/calendar-card/calendar-card.js
    type: js
  - url: /community_plugin/canvas-gauge-card/canvas-gauge-card.js
    type: module
  - url: /community_plugin/circle-sensor-card/circle-sensor-card.js
    type: module
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /community_plugin/decluttering-card/decluttering-card.js
    type: module
  - url: /community_plugin/dual-gauge-card/dual-gauge-card.js
    type: js
  - url: /community_plugin/entity-attributes-card/entity-attributes-card.js
    type: js
  - url: /community_plugin/ext-weblink/ext-weblink.js
    type: js
  - url: /community_plugin/flex-horseshoe-card/flex-horseshoe-card.js
    type: module
  - url: /community_plugin/garbage-collection-card/garbage-collection-card.js
    type: module
  - url: /community_plugin/gauge-card/gauge-card.js
    type: js
  - url: /community_plugin/github-card/github-card.js
    type: js
  - url: /community_plugin/group-card/group-card.js
    type: js
  - url: /community_plugin/group-element/group-element.js
    type: module
  - url: /community_plugin/light-entity-card/light-entity-card.js
    type: js
  - url: /community_plugin/light-entity-row/light-entity-row.js
    type: js
  - url: /community_plugin/list-card/list-card.js
    type: js
  - url: /community_plugin/love-lock-card/love-lock-card.js
    type: js
  - url: /community_plugin/lovelace-card-templater/lovelace-card-templater.js
    type: js
  - url: /community_plugin/lovelace-github-entity-row/github-entity-row.js
    type: js
  - url: /community_plugin/lovelace-home-feed-card/lovelace-home-feed-card.js
    type: js
  - url: /community_plugin/lovelace-light-with-profiles/light-with-profiles.js
    type: module
  - url: /community_plugin/plan-coordinates/plan-coordinates.js
    type: js
  - url: /community_plugin/secondaryinfo-entity-row/secondaryinfo-entity-row.js
    type: js
#  - url: /community_plugin/state-attribute-element/state-attribute-element.js
#    type: js
#  - url: /community_plugin/state-element/state-element.js
#    type: js
  - url: /community_plugin/text-action-element/text-action-element.js
    type: module
  - url: /community_plugin/text-divider-row/text-divider-row.js
    type: module
  - url: /community_plugin/text-element/text-element.js
    type: js
  - url: /community_plugin/tracking-number-card/tracking-number-card.js
    type: js
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/lovelace-auto-entities/auto-entities.js
    type: module
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: js
  - url: /local/custom-cards/lovelace-card-tools/card-tools.js
    type: module
  - url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
    type: module
  - url: /community_plugin/lovelace-gui-sandbox/gui-sandbox.js
    type: module
  - url: /community_plugin/lovelace-layout-card/layout-card.js
    type: js
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: module

custom_header:
  compact_mode: true
  header_text: '{{ hours24LZ }}:{{ minutesLZ }}'

title: Home

views:
  - !include lovelace/00-summary.yaml
  - !include lovelace/10-home.yaml
  - !include lovelace/11-lights.yaml
  - !include lovelace/20-network.yaml
  - !include lovelace/21-networkalt.yaml
  - !include lovelace/30-internet.yaml
  - !include lovelace/40-weather.yaml
  - !include lovelace/50-homeassistant.yaml
#  - !include lovelace/60-user0001.yaml
#  - !include lovelace/61-user0002.yaml
#  - !include lovelace/70-systems.yaml

# ======================================================================
#
# Misc Views
#
# ======================================================================

# ======================================================================
#
#
#
# ======================================================================

# ======================================================================
# End ui-lovelace.yaml
