binary_sensor:
  - platform: tod
    name: "Predawn"
    after: "sunrise"
    after_offset: "-00:30"
    before: "sunrise"

  - platform: tod
    name: "Predusk"
    after: "sunset"
    after_offset: "-00:30"
    before: "sunset"
