binary_sensor:
  - platform: car_wash
    weather: weather.kahn_daynight

sun:

sensor:
  - platform: moon

  # Seasons
  - platform: season
    type: astronomical

  - platform: season
    type: meteorological

  - platform: nws_alerts
    zone_id: "GAC059,GAC219"

template:
  - binary_sensor:
      - unique_id: "7de08353-b672-41eb-aed1-eca95d808d4d"
        name: "Sun Up"
        state: >-
          {{ is_state("sun.sun", "above_horizon") }}
        icon: >-
          {% if is_state("binary_sensor.sun_up", "on") %}
            mdi:weather-sunset-up
          {% else %}
            mdi:weather-sunset-down
          {% endif %}

  - sensor:
      - unique_id: "b3187f1a-daf3-468d-a18a-579801f0d078"
        name: "Sun elevation"
        state: "{{ state_attr('sun.sun', 'elevation') }}"
        unit_of_measurement: '°'
