sensor:
  - platform: pirateweather
    api_key: !secret pirateweather
    scan_interval: '00:30:00'
    forecast:
      - 0
    monitored_conditions:
      - summary
      - icon
      - temperature
      - precip_type
      - precip_intensity
      - precip_probability
      - precip_accumulation
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_gust
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - ozone
      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_high
      - temperature_low
      - apparent_temperature_high
      - apparent_temperature_low
      - precip_intensity_max
      - uv_index
      - moon_phase
      - nearest_storm_distance
      - nearest_storm_bearing

  - platform: pirateweather
    api_key: !secret pirateweather
    scan_interval: '06:00:00'
    forecast:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    monitored_conditions:
      - summary
      - icon
      - temperature
      - precip_type
      - precip_intensity
      - precip_probability
      - precip_accumulation
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_gust
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - ozone
      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_high
      - temperature_low
      - apparent_temperature_high
      - apparent_temperature_low
      - precip_intensity_max
      - uv_index
      - moon_phase
      - nearest_storm_distance
      - nearest_storm_bearing

template:
  - sensor:
      - unique_id: "10cd6c80-b86f-4ee5-8865-41e0b661530b"
        name: "Darksky Pressure"
        state: '{{ states.sensor.pirateweather_pressure.state | float / 33.864 | round(2) }}'
        unit_of_measurement: 'inHg'

      - unique_id: "65e0527a-7948-4704-af47-0c2772f0f0b7"
        name: "Darksky Pressure 0d"
        state: '{{ states.sensor.pirateweather_pressure_0d.state | float / 33.864 | round(2) }}'
        unit_of_measurement: 'inHg'

      - unique_id: "2e7ef5af-74d5-4def-acd9-265b2f68d39d"
        name: "Darksky Pressure 1d"
        state: '{{ states.sensor.pirateweather_pressure_1d.state | float / 33.864 | round(2) }}'
        unit_of_measurement: 'inHg'

      - unique_id: "43fb5e97-bf86-4d9c-a808-0a2b10924c3a"
        name: "Darksky Pressure 2d"
        state: '{{ states.sensor.pirateweather_pressure_2d.state | float / 33.864 | round(2) }}'
        unit_of_measurement: 'inHg'

      - unique_id: "1a6da79a-8b0b-4481-be23-e23a71e418d6"
        name: "Darksky Pressure 3d"
        state: '{{ states.sensor.pirateweather_pressure_3d.state | float / 33.864 | round(2) }}'
        unit_of_measurement: 'inHg'

      - unique_id: "a0f2efb3-2459-40a3-927b-5e5963c89dd4"
        name: "Darksky Pressure 4d"
        state: '{{ states.sensor.pirateweather_pressure_4d.state | float / 33.864 | round(2) }}'
        unit_of_measurement: 'inHg'

      - unique_id: "a88c49b8-ae47-4ed8-9a7c-2ee6fe0a00cb"
        name: "Darksky Pressure 5d"
        state: '{{ states.sensor.pirateweather_pressure_5d.state | float / 33.864 | round(2) }}'
        unit_of_measurement: 'inHg'

      - unique_id: "6d56a40d-e253-4122-8765-9fad97a8a0c3"
        name: "Darksky Pressure 6d"
        state: '{{ states.sensor.pirateweather_pressure_6d.state | float / 33.864 | round(2) }}'
        unit_of_measurement: 'inHg'

      - unique_id: "827e9a64-d29a-46d2-9039-bdff9729519a"
        name: "Darksky Pressure 7d"
        state: '{{ states.sensor.pirateweather_pressure_7d.state | float / 33.864 | round(2) }}'
        unit_of_measurement: 'inHg'

weather:
  - platform: pirateweather
    api_key: !secret pirateweather
