# ==================================================================================================
#
# Set Lighting Mode: Circadian (with Brightness adjustments)"
#
# - In the morning when the sun rises to 18 degrees below the horizon
#   enable
# ==================================================================================================
- id: "c538b51a-b47f-41b6-b85c-57cd0efade1c"
  alias: "Turn Off Migraine Mode"
  description: ""
  trigger:
  - at: 04:00:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: input_boolean.special_migraine_mode
    service: input_boolean.turn_off

- id: "6ed4807a-3951-412e-be81-5d6d74a77d14"
  alias: "Turn Off Master Bedroom TV Power"
  description: ""
  trigger:
    - platform: time
      at: "21:00:00"
    - platform: state
      entity_id: sensor.mf1_bedroom1_zwave13_power
      to: "0"
    - platform: state
      entity_id: light.mf1_bedroom1_lamp1
      from: "on"
      to: "off"
    - platform: state
      entity_id: light.mf1_bedroom1_lamp2
      from: "on"
      to: "off"
    - platform: state
      entity_id: media_player.mf1_bedroom1_bd_f5900
      to: "off"
      for:
        hours: 0
        minutes: 1
        seconds: 30
  condition:
    - condition: state
      entity_id: media_player.mf1_bedroom1_bd_f5900
      state: "off"
      for:
        hours: 0
        minutes: 1
        seconds: 0
    - condition: time
      after: "21:00:00"
    - condition: state
      entity_id: light.mf1_bedroom1_lamp1
      state: "off"
    - condition: state
      entity_id: light.mf1_bedroom1_lamp2
      state: "off"
    - condition: numeric_state
      entity_id: sensor.mf1_bedroom1_zwave13_power
      below: "5"
  action:
    - service: "switch.turn_off"
      data:
        entity_id:
            - switch.mf1_bedroom1_zwave13_switch
  mode: single

- id: "e63c0e77-1904-4a46-a73c-6982837270a8"
  alias: "Turn On Master Bedroom TV power"
  description: ""
  trigger:
    - platform: sun
      event: sunrise
    - platform: state
      entity_id: media_player.mf1_bedroom1_bd_f5900
      from: "off"
      to: "on"
  condition: []
  action:
    - service: "switch.turn_on"
      data:
        entity_id:
            - switch.mf1_bedroom1_zwave13_switch
  mode: single
