---
# ==================================================================================================
#
# Set Lighting Mode: Circadian (with Brightness adjustments)"
#
# - In the morning when the sun rises to 18 degrees below the horizon
#   enable
# ==================================================================================================
- id: "c538b51a-b47f-41b6-b85c-57cd0efade1c"
  alias: "Turn Off Migraine Mode"
  description: ""
  trigger:
  - at: 04:00:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: input_boolean.special_migraine_mode
    service: input_boolean.turn_off
