# ==================================================================================================
#
# Set Lighting Mode: Circadian (with Brightness adjustments)"
#
# - In the morning when the sun rises to 18 degrees below the horizon
#   enable
# ==================================================================================================
- id: "c538b51a-b47f-41b6-b85c-57cd0efade1c"
  alias: "Turn Off Migraine Mode"
  description: ""
  trigger:
  - at: 04:00:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: input_boolean.special_migraine_mode
    service: input_boolean.turn_off

# ==================================================================================================
#
# Set Lighting Mode: Circadian (with Brightness adjustments)"
#
# - In the morning when the sun rises to 18 degrees below the horizon
#   enable
# ==================================================================================================
- id: "918ded3c-579d-4b16-8511-f89d881b0103"
  alias: "Start Sleep Timer"
  description: "Starts a timer upon going to bed."
  trigger:
    - platform: time
      at: "21:00:00"
    - platform: state
      entity_id: light.all_lights
      to: "off"
    - platform: state
      entity_id: light.master_bedroom_lamp_1
      from: "on"
      to: "off"
    - platform: state
      entity_id: light.master_bedroom_lamp_2
      from: "on"
      to: "off"
  condition:
    - condition: time
      after: "21:00:00"
    - condition: state
      entity_id: light.master_bedroom_lamp_2
      state: "off"
    - condition: state
      entity_id: light.master_bedroom_lamp_1
      state: "off"
  action:
    - service: timer.start
      data:
        entity_id: timer.lights_off

- id: "6ed4807a-3951-412e-be81-5d6d74a77d14"
  alias: "Turn Off Master Bedroom TV Power"
  description: ""
  trigger:
    - platform: time
      at: "21:00:00"
    - platform: state
      entity_id: sensor.nodeid_4_electric_w_value_3
      to: "0"
    - platform: state
      entity_id: light.master_bedroom_lamp_1
      from: "on"
      to: "off"
    - platform: state
      entity_id: light.master_bedroom_lamp_2
      from: "on"
      to: "off"
    - platform: state
      entity_id: media_player.samsung_bd_f5900
      from: "on"
      to: "off"
  condition:
    - condition: device
      device_id: 30ff6de20a8f11ebaec1b7b1859d29d6
      domain: media_player
      entity_id: media_player.samsung_bd_f5900
      type: is_off
    - condition: time
      after: "21:00:00"
    - condition: state
      entity_id: light.master_bedroom_lamp_2
      state: "off"
    - condition: state
      entity_id: light.master_bedroom_lamp_1
      state: "off"
    - condition: numeric_state
      entity_id: sensor.nodeid_4_electric_w_value_3
      below: "5"
  action:
    - type: turn_off
      entity_id: switch.nodeid_4_switch_3
      domain: switch
  mode: single

- id: "e63c0e77-1904-4a46-a73c-6982837270a8"
  alias: "Turn On Master Bedroom TV power"
  description: ""
  trigger:
    - platform: sun
      event: sunrise
    - platform: state
      entity_id: media_player.samsung_bd_f5900
      from: "off"
      to: "on"
  condition: []
  action:
    - type: turn_on
      entity_id: switch.nodeid_4_switch_3
      domain: switch
  mode: single
