---
# ======================================================================
#
# Set Lighting Mode: Circadian (with Brightness adjustments)"
#
# - In the morning when the sun rises to 18 degrees below the horizon
#   enable
# ======================================================================
- alias: 'Turn Off Migraine Mode'
  description: ''
  trigger:
  - at: 03:00:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: input_boolean.migraine_mode
    service: input_boolean.turn_off

# ======================================================================
#
# Set Lighting Mode: Circadian (with Brightness adjustments)"
#
# - In the morning when the sun rises to 18 degrees below the horizon
#   enable
# ======================================================================
- id: "1606847390094"
  alias: 'Start Sleep Timer'
  description: ''
  trigger:
  - platform: state
    entity_id: light.all_lights
    to: 'off'
  - platform: state
    entity_id: light.master_lamp_2
    from: 'on'
    to: 'off'
  - platform: time
    at: '22:00:00'
  condition:
  - after: '22:00:00'
    condition: time
  - condition: state
    entity_id: light.master_lamp_2
    state: 'off'
  action:
  - service: timer.start
    data:
      entity_id: timer.lights_off

- id: '1606847637745'
alias: Turn of Master Bedroom TV Power
description: ''
trigger:
  - platform: time
    at: '22:00'
  - platform: state
    entity_id: sensor.power_strip_03_outlet_3_power
    to: '0'
  - platform: state
    entity_id: light.master_bedroom_lamp_1
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: light.master_bedroom_lamp_2
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: media_player.samsung_bd_f5900
    from: 'on'
    to: 'off'
condition:
  - condition: device
    device_id: 30ff6de20a8f11ebaec1b7b1859d29d6
    domain: media_player
    entity_id: media_player.samsung_bd_f5900
    type: is_off
  - condition: time
    after: '22:00'
  - condition: state
    entity_id: light.master_bedroom_lamp_2
    state: 'off'
  - condition: state
    entity_id: light.master_bedroom_lamp_1
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.power_strip_03_outlet_3_power
    below: '5'
action:
  - type: turn_off
    device_id: df96863a0f8bfe05ddaba286433
