# ==================================================================================================
#
# Basement
#
# Lights:
#   - light.basement_lamp_
#   - light.basement_lamp_
#   - light.basement_lamp_
#
# Light Groups:
#   - light.basement
#
# ==================================================================================================
adaptive_lighting:
  - name: "Basement"
    lights:
      - light.basement
    initial_transition: 1
    min_color_temp: 2200
    max_color_temp: 6500

# ==================================================================================================
#
# Automations
#
#
#
# ==================================================================================================
automation:
  - id: '07bb38d4-9581-4268-a6cb-821f8dd9367e'
    alias: '[Light] Basement: Turn Off Lights At Night'
    initial_state: false
    description: ''
    trigger:
      - at: '21:30'
        platform: time
    condition: []
    action:
      - service: light.turn_off
        data:
          entity_id: light.basement

  - id: "fa05d4ef-c8be-425a-b3e8-8418270d5009"
    alias: "[Light] Basement: Adaptive Lighting (Toggle Brightness Adjustment)"
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        to: "Circadian"
      - platform: state
        entity_id: binary_sensor.light_basement_autobrightness
    variables:
      brightness_mode: "{{ states('binary_sensor.light_basement_autobrightness') }}"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
    action:
      - service: "switch.turn_{{ brightness_mode }}"
        data:
          entity_id:
            - switch.adaptive_lighting_adapt_brightness_basement
    mode: single

  - id: "0f6a057d-afa4-4688-bee2-28226441e6f8"
    alias: "[Light] Basement - Adaptive Lighting (Turn Off Brightness Adjustment)"
    initial_state: false
    description: ""
    trigger:
        - platform: event
          event_type: hue_event
          event_data:
            id: bf_great_room_switch_button
            subtype: 3
        - platform: event
          event_type: hue_event
          event_data:
            id: bf_great_room_switch_button
            subtype: 2
    condition: []
    action:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.adaptive_lighting_adapt_brightness_basement
    mode: single

  # Temporarily disable until I can figure out how to reverse the variable definition.
  # IE, when states('binary_sensor.light_basement_color_mode') is off, the variable should be 'on'
  # - id: "4c6e9101-a48b-480f-bd66-ad4b5fe13ac2"
  #   alias: "[Light] Basement: Adaptive Lighting (Toggle)"
  #   initial_state: false
  #   trigger:
  #     - platform: state
  #       entity_id: input_select.light_mode
  #       to: "Circadian"
  #     - platform: state
  #       entity_id: binary_sensor.light_basement_color_mode
  #   variables:
  #     brightness_mode: "{{ states('binary_sensor.light_basement_autobrightness') }}"
  #   condition:
  #     condition: and
  #     conditions:
  #       - condition: template
  #         value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
  #   action:
  #     - service: "switch.turn_{{ brightness_mode }}"
  #       data:
  #         entity_id:
  #           - switch.adaptive_lighting_adapt_brightness_basement
  #   mode: single



# # ======================================================================
# #
# #
# #
# # ======================================================================
# input_select:
#   hue_scene_basement_bedroom:
#     name: "[Light] Hue Basement Scene"
#     icon: mdi:palette
#     initial: "Circadian"
#     options:
#       - Arctic aurora
#       - Sevanna sunset
#       - Tropical twilight
#       - Spring blossom
#       - Relax
#       - Read
#       - Concentrate
#       - Energize
#       - Bright
#       - Dimmed
#       - Nightlight
#       - Motown
#       - Midsomer Sun
#       - Midwinter
#       - Ocean Dawn
#       - Emerald Isle
#       - Mountain Breeze
#       - Spring lake
#       - Moonlight
#       - Starlight
#       - Soho
#       - Golden Pond
#       - Frosty Dawn
#       - Fairfax
#       - Autumn Gold
#       - Palm Beach
#       - Lake Mist
#       - Chinatown
#       - Tokyo
#       - Sunday Morning
#       - Ibiza
#       - Nebula
#       - Galaxy
#       - Ruby Glow
#       - Winter mountain
#       - Blue Lagoon
#       - Honolulu
#       - Lake Placid
#       - Osaka
#       - Sundowner
#       - Blood Moon
#       - Circadian
#       - Night Mode
#       - Migraine

# ==================================================================================================
#
# Rest Command
#
# Light IDs:
# - 01: e687cdcb-7022-4d66-9763-ec5ead8f8808
# - 02: 068c9cd1-0128-423b-b0f4-e9bc57e0308e
# - 03: 65a17417-29b9-4978-9145-0d3ce5e94c01
# - 04: 84e56e8b-a96f-4a25-9715-4ecc0921ab8d
# - 05: 12fe02ef-c867-4eae-982e-f8fdf9e0ba23
# - 06: e464775c-3b2b-453d-b7cf-e7def42610f6
# - 07: 2b238059-189a-4f70-b33a-6b6948b70dc7
# - 08: b02df779-caaa-446a-8e0e-e73e069f9cbd
# - 09: 5d9e8921-1307-4181-826e-55c3a05e14ac
# - 10: ae1340a6-0178-4eb5-8b4a-c166abd7a297
# - 11: 557f80c4-02a7-4944-8591-53eb8c33cb95
# - 12: 8677b6df-8d08-4eba-a4c5-927d3321915d
#
# ==================================================================================================
rest_command:
  light_update_basement_scene_homeassistant:
    url: "https://hue2.iot.home/clip/v2/resource/scene/{{ scene_id }}"
    method: put
    headers:
      authorization: "hue-application-key: {{ username }}"
      accept: "application/json"
      payload: '{ "actions":[
      {
         "action":{ {{ color }},{{ brightness }},{{ bulb_01_on_state }} },
         "target":{"rid":"12fe02ef-c867-4eae-982e-f8fdf9e0ba23","rtype":"light"}
      }
      ],
      "group":{"rid":"4789c565-2e72-4506-80aa-cfa4be63e7e8","rtype":"zone"},
      "id":"cd29377b-333f-4e4d-97ef-5d2a8989c7ac",
      "id_v1":"/scenes/FeLBGg4OiptLHtH",
      "metadata":{"name":"HomeAssistant"},
      "palette":{"color":[],"color_temperature":[{{{ color }},{{ brightness }}}],"dimming":[]},
      "speed":0.6031746031746031,
      "type":"scene"
      }'
    verify_ssl: false
    content_type: "application/json"

         # },{
         # "action":{ {{ color }},{{ brightness }},{{ bulb_02_on_state }} },
         # "target":{"rid":"e687cdcb-7022-4d66-9763-ec5ead8f8808","rtype":"light"}
         # },{
         # "action":{ {{ color }},{{ brightness }},{{ bulb_03_on_state }} },
         # "target":{"rid":"557f80c4-02a7-4944-8591-53eb8c33cb95","rtype":"light"}
         # },{
         # "action":{ {{ color }},{{ brightness }},{{ bulb_04_on_state }} },
         # "target":{"rid":"65a17417-29b9-4978-9145-0d3ce5e94c01","rtype":"light"}
         # },{
         # "action":{ {{ color }},{{ brightness }},{{ bulb_05_on_state }} },
         # "target":{"rid":"068c9cd1-0128-423b-b0f4-e9bc57e0308e","rtype":"light"}
         # },{
         # "action":{ {{ color }},{{ brightness }},{{ bulb_06_on_state }} },
         # "target":{"rid":"b02df779-caaa-446a-8e0e-e73e069f9cbd","rtype":"light"}
         # },{
         # "action":{ {{ color }},{{ brightness }},{{ bulb_07_on_state }} },
         # "target":{"rid":"2b238059-189a-4f70-b33a-6b6948b70dc7","rtype":"light"}
         # },{
         # "action":{ {{ color }},{{ brightness }},{{ bulb_08_on_state }} },
         # "target":{"rid":"e464775c-3b2b-453d-b7cf-e7def42610f6","rtype":"light"}
         # },{
         # "action":{ {{ color }},{{ brightness }},{{ bulb_09_on_state }} },
         # "target":{"rid":"ae1340a6-0178-4eb5-8b4a-c166abd7a297","rtype":"light"}
         # },{
         # "action":{ {{ color }},{{ brightness }},{{ bulb_10_on_state }} },
         # "target":{"rid":"84e56e8b-a96f-4a25-9715-4ecc0921ab8d","rtype":"light"}
         # },{
         # "action":{ {{ color }},{{ brightness }},{{ bulb_11_on_state }} },
         # "target":{"rid":"5d9e8921-1307-4181-826e-55c3a05e14ac","rtype":"light"}
         # },{
         # "action":{ {{ color }},{{ brightness }},{{ bulb_12_on_state }} },
         # "target":{"rid":"8677b6df-8d08-4eba-a4c5-927d3321915d","rtype":"light"}

# ==================================================================================================
#
# Scenes
#
# Notes:
#
# Brightness settings:
#  100% = 255
#   75% = 192
#   50% = 128
#   25% =  64
#
# Colors:
#   Red = xy [0.689,0.309]
# Green = xy [0.17,0.7]
#
# ======================================================================
scene:
  - id: "29d35002-68ed-4cfe-bcd3-552e55c219c1"
    name: "[Light] Enable Basement Automations"
    entities:
      automation.light_basement_turn_off_lights_at_night:
        state: "on"
      automation.light_basement_adaptive_lighting_toggle_brightness_adjustment:
        state: "on"
      automation.light_basement_adaptive_lighting_turn_off_brightness_adjustment:
        state: "on"

  - id: "68dcd95f-bf3f-42d7-bb84-6b50af2bb70e"
    name: "[Light] Basement: Darken"
    entities:
      light.bf_den_lamp_2:
        state: "on"
        xy_color:
          - 0.689
          - 0.309
        brightness: 64
      light.basement_bulb_1:
        state: "off"
      light.basement_bulb_2:
        state: "off"
      light.basement_bulb_3:
        state: "off"
      light.basement_lamp_2:
        state: "off"
      light.basement_lamp_3:
        state: "off"
      light.basement_stairwell_bulb:
        state: "off"
      light.cave_lamp_2_bulb_2:
        state: "off"
      light.den_ceiling_bulb_1:
        state: "on"
        xy_color:
          - 0.689
          - 0.309
        brightness: 64
      light.den_ceiling_bulb_2:
        state: "off"
      light.den_ceiling_bulb_3:
        state: "off"
      light.den_lamp_1_bulb:
        state: "off"
      light.hue_ambiance_lamp_2:
        state: "off"
      light.hue_ambiance_lamp_3:
        state: "off"
      light.hue_ambiance_lamp_4:
        state: "off"

  - id: "d8c9b5de-8ed7-4403-87ee-172feb15d9a5"
    name: "[Light] Basement: Migraine"
    entities:
      light.bf_den_lamp_2:
        state: "on"
        xy_color:
          - 0.17
          - 0.7
        brightness: 64
      light.basement_bulb_1:
        state: "off"
      light.basement_bulb_2:
        state: "off"
      light.basement_bulb_3:
        state: "off"
      light.basement_lamp_2:
        state: "off"
      light.basement_lamp_3:
        state: "off"
      light.basement_stairwell_bulb:
        state: "off"
      light.cave_lamp_2_bulb_2:
        state: "off"
      light.den_ceiling_bulb_1:
        state: "on"
        xy_color:
          - 0.17
          - 0.7
        brightness: 64
      light.den_ceiling_bulb_2:
        state: "off"
      light.den_ceiling_bulb_3:
        state: "off"
      light.den_lamp_1_bulb:
        state: "off"
      light.hue_ambiance_lamp_2:
        state: "off"
      light.hue_ambiance_lamp_3:
        state: "off"
      light.hue_ambiance_lamp_4:
        state: "off"

  - id: "10fd713e-b10b-4e3d-833b-3ea63816b5de"
    name: "[Light] Basement: Bright"
    entities:
      light.basement:
        state: "on"
        color_temp: 367
        brightness: 255

  - id: "22b7c3af-0991-4f83-b2b2-6d51f1df089c"
    name: "[Light] Basement: Concentrate"
    entities:
      light.basement:
        state: "on"
        color_temp: 230
        brightness: 255

  - id: "9e5f60ca-caae-41b3-bd7b-7fce33bcc436"
    name: "[Light] Basement: Dimmed"
    entities:
      light.basement:
        state: "on"
        color_temp: 369
        brightness: 76

  - id: "126a563d-3826-4d00-81e1-abca1a6869b2"
    name: "[Light] Basement: Energize"
    entities:
      light.basement:
        state: "on"
        color_temp: 156
        brightness: 255

  - id: "50d190ae-8d62-4716-ac9c-3ef5757a1009"
    name: "[Light] Basement: Nightlight"
    entities:
      light.basement:
        state: "on"
        color_temp: 454
        brightness: 1

  - id: "3e72d0b5-c2f2-4f4e-87df-67bc7c63882d"
    name: "[Light] Basement: Read"
    entities:
      light.basement:
        state: "on"
        color_temp: 343
        brightness: 255

  - id: "fbe2e3db-c839-42d6-86de-c879baf8673e"
    name: "[Light] Basement: Relax"
    entities:
      light.basement:
        state: "on"
        color_temp: 447
        brightness: 145

  - id: "b448b6d9-fc73-4f87-8cd9-f0df64dd350d"
    name: "[Light] Basement: Off"
    entities:
      light.basement:
        state: "off"

# ==================================================================================================
#
# Templates
#
# Need to eventually convert these into the new 'template:' style.  This currently doesn't seem
# to work inside packages.
#
# https://www.home-assistant.io/integrations/template/
#
# ==================================================================================================
template:
  - binary_sensor:
      - unique_id: "64ca8117-0ecc-4dab-b821-b67f08fe10f0"
        name: "[Light] Basement Autobrightness"
        state: >-
          {{ (
               state_attr("switch.adaptive_lighting_basement", "brightness_pct") | int ) <
               ( state_attr("binary_sensor.light_basement_autobrightness", "brightness_max")
               | int )
             and ( state_attr("switch.adaptive_lighting_basement", "brightness_pct") | int ) >
             ( state_attr("binary_sensor.light_basement_autobrightness", "brightness_min") | int
             ) }}
        attributes:
          brightness: >-
            {% if state_attr("light.basement", "brightness") == None or
               is_state_attr("light.basement", "brightness", "unknown") or
               is_state("light.basement", "off") %}
              {{ ( state_attr("switch.adaptive_lighting_basement", "brightness_pct" ) | int | int ) }}
            {% else %}
              {{ ( state_attr("light.basement","brightness") / 254 * 100 ) | int }}
            {% endif %}
          brightness_max: >-
            {{ state_attr("binary_sensor.light_basement_autobrightness", "brightness") | int + 4 }}
          brightness_min: >-
            {{ state_attr("binary_sensor.light_basement_autobrightness", "brightness") | int - 4 }}

      - unique_id: "77e8421d-25eb-413e-905f-8887b4d91e77"
        name: "[Light] Basement Color Mode"
        state: "{{ state_attr('light.basement','color_mode') == 'xy' }}"

  - sensor:
      - unique_id: "c3ba92a2-de79-41fa-b818-3809a4750d3a"
        name: "[Light] Basement Color"
        state: "{{ state_attr('light.basement', 'xy_color') }}"
