# ==================================================================================================
#
# Basement
#
# Lights:
#   - light.basement_lamp_
#   - light.basement_lamp_
#   - light.basement_lamp_
#
# Light Groups:
#   - light.basement
#
# ==================================================================================================
adaptive_lighting:
  - name: "Basement"
    lights:
      - light.basement
    initial_transition: 1
    min_color_temp: 2200
    max_color_temp: 6500

# ==================================================================================================
#
# Automations
#
#
#
# ==================================================================================================
automation:
  - id: '07bb38d4-9581-4268-a6cb-821f8dd9367e'
    alias: '[Light] Basement: Turn Off Lights At Night'
    initial_state: false
    description: ''
    trigger:
      - at: '21:30'
        platform: time
    condition: []
    action:
      - service: light.turn_off
        data:
          entity_id: light.basement

  - id: "fa05d4ef-c8be-425a-b3e8-8418270d5009"
    alias: "[Light] Basement: Adaptive Lighting (Toggle Brightness Adjustment)"
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        to: "Circadian"
      - platform: state
        entity_id: binary_sensor.light_basement_autobrightness
    variables:
      brightness_mode: "{{ states('binary_sensor.light_basement_autobrightness') }}"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
    action:
      - service: "switch.turn_{{ brightness_mode }}"
        data:
          entity_id:
            - switch.adaptive_lighting_adapt_brightness_basement
    mode: single

  - id: "0f6a057d-afa4-4688-bee2-28226441e6f8"
    alias: "[Light] Basement - Adaptive Lighting (Turn Off Brightness Adjustment)"
    description: ""
    trigger:
        - platform: event
          event_type: hue_event
          event_data:
            id: bf_great_room_switch_button
            subtype: 3
        - platform: event
          event_type: hue_event
          event_data:
            id: bf_great_room_switch_button
            subtype: 2
    condition: []
    action:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.adaptive_lighting_adapt_brightness_den_couch_lamp_2
    mode: single

 #- id: "eaae85d0-24f0-4309-aba3-dd17225f97e7"


# # ======================================================================
# #
# #
# #
# # ======================================================================
# input_select:
#   hue_scene_basement_bedroom:
#     name: "[Light] Hue Basement Scene"
#     icon: mdi:palette
#     initial: "Circadian"
#     options:
#       - Arctic aurora
#       - Sevanna sunset
#       - Tropical twilight
#       - Spring blossom
#       - Relax
#       - Read
#       - Concentrate
#       - Energize
#       - Bright
#       - Dimmed
#       - Nightlight
#       - Motown
#       - Midsomer Sun
#       - Midwinter
#       - Ocean Dawn
#       - Emerald Isle
#       - Mountain Breeze
#       - Spring lake
#       - Moonlight
#       - Starlight
#       - Soho
#       - Golden Pond
#       - Frosty Dawn
#       - Fairfax
#       - Autumn Gold
#       - Palm Beach
#       - Lake Mist
#       - Chinatown
#       - Tokyo
#       - Sunday Morning
#       - Ibiza
#       - Nebula
#       - Galaxy
#       - Ruby Glow
#       - Winter mountain
#       - Blue Lagoon
#       - Honolulu
#       - Lake Placid
#       - Osaka
#       - Sundowner
#       - Blood Moon
#       - Circadian
#       - Night Mode
#       - Migraine

# # ==================================================================================================
# #
# # Rest Command
# #
# # 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17
# #
# # ==================================================================================================
# # rest_command:
# #   light_update_basement_scene_homeassistant:
# #     url: "https://hue2.iot.home/api/{{ username }}/scenes/{{ scene_id }}"
# #     method: put
# #     payload: '{ "lightstates": { "4": { "on": "{{ bulb_01_on_state }}", {{ color }}, {{ brightness }} }, "5": { "on": "{{ bulb_02_on_state }}", {{ color }}, {{ brightness }} }, "6": { "on": "{{ bulb_03_on_state }}", {{ color }}, {{ brightness }} }, "7": { "on": "{{ bulb_04_on_state }}", {{ color }}, {{ brightness }} }, "8": { "on": "{{ bulb_05_on_state }}", {{ color }}, {{ brightness }} }, "9": { "on": "{{ bulb_06_on_state }}", {{ color }}, {{ brightness }} }, "10": { "on": "{{ bulb_07_on_state }}", {{ color }}, {{ brightness }} }, "11": { "on": "{{ bulb_08_on_state }}", {{ color }}, {{ brightness }} }, "12": { "on": "{{ bulb_09_on_state }}", {{ color }}, {{ brightness }} }, "14": { "on": "{{ bulb_10_on_state }}", {{ color }}, {{ brightness }} }, "15": { "on": "{{ bulb_11_on_state }}", {{ color }}, {{ brightness }} }, "16": { "on": "{{ bulb_12_on_state }}", {{ color }}, {{ brightness }} }, "17": { "on": "{{ bulb_13_on_state }}", {{ color }}, {{ brightness }} }}}'
# #     verify_ssl: false

# # ==================================================================================================
# #
# # Scenes
# #
# # Notes:
# #
# # Brightness settings:
# #  100% = 255
# #   75% = 192
# #   50% = 128
# #   25% =  64
# #
# # Colors:
# #   Red = xy [0.689,0.309]
# # Green = xy [0.17,0.7]
# #
# # ======================================================================
# scene:
#   - id: "29d35002-68ed-4cfe-bcd3-552e55c219c1"
#     name: "[Light] Enable Basement Automations"
#     entities:
#       automation.light_basement_turn_off_lights_at_night:
#         state: "on"
#       automation.light_basement_adaptive_lighting_toggle_brightness_adjustment:
#         state: "on"

#   - id: "68dcd95f-bf3f-42d7-bb84-6b50af2bb70e"
#     name: "[Light] Basement: Darken Room"
#     entities:
#       light.hue_color_lamp_2_2:
#         state: "on"
#         xy_color:
#           - 0.689
#           - 0.309
#         brightness: 64
#       light.basement_bulb_1:
#         state: "off"
#       light.basement_lamp_2:
#         state: "off"
#       light.basement_lamp_3:
#         state: "off"
#       light.basement_stairwell_bulb:
#         state: "off"
#       light.cave_lamp_2_bulb_2:
#         state: "off"
#       light.den_ceiling_bulb_1:
#         state: "on"
#         xy_color:
#           - 0.689
#           - 0.309
#         brightness: 64
#       light.den_ceiling_bulb_2:
#         state: "off"
#       light.den_ceiling_bulb_3:
#         state: "off"
#       light.den_lamp_1_bulb:
#         state: "on"
#         xy_color:
#           - 0.689
#           - 0.309
#         brightness: 64
#       light.hue_ambiance_lamp_2:
#         state: "off"
#       light.hue_color_lamp_1:
#         state: "on"
#         xy_color:
#           - 0.689
#           - 0.309
#         brightness: 64
#       light.hue_color_lamp_2:
#         state: "on"
#         xy_color:
#           - 0.689
#           - 0.309
#         brightness: 64
#       light.hue_color_lamp_3:
#         state: "on"
#         xy_color:
#           - 0.689
#           - 0.309
#         brightness: 64

#   - id: "d8c9b5de-8ed7-4403-87ee-172feb15d9a5"
#     name: "[Light] Basement: Migraine"
#     entities:
#       light.hue_color_lamp_2_2:
#         state: "on"
#         xy_color:
#           - 0.17
#           - 0.7
#         brightness: 128
#       light.basement_bulb_1:
#         state: "off"
#       light.basement_bulb_2:
#         state: "off"
#       light.basement_bulb_3:
#         state: "off"
#       light.basement_lamp_2:
#         state: "off"
#       light.basement_lamp_3:
#         state: "off"
#       light.basement_stairwell_bulb:
#         state: "off"
#       light.cave_lamp_2_bulb_2:
#         state: "off"
#       light.den_ceiling_bulb_1:
#         state: "on"
#         xy_color:
#           - 0.17
#           - 0.7
#         brightness: 128
#       light.den_ceiling_bulb_2:
#         state: "off"
#       light.den_ceiling_bulb_3:
#         state: "off"
#       light.den_lamp_1_bulb:
#         state: "on"
#         xy_color:
#           - 0.17
#           - 0.7
#         brightness: 128
#       light.hue_ambiance_lamp_2:
#         state: "off"
#       light.hue_color_lamp_1:
#         state: "on"
#         xy_color:
#           - 0.17
#           - 0.7
#         brightness: 128
#       light.hue_color_lamp_2:
#         state: "on"
#         xy_color:
#           - 0.17
#           - 0.7
#         brightness: 128
#       light.hue_color_lamp_3:
#         state: "on"
#         xy_color:
#           - 0.17
#           - 0.7
#         brightness: 128

# sensor:
#   - platform: template
#     sensors:
#       light_basement_xy_color:
#         friendly_name: "[Light] Basement: XY Color"
#         value_template: "{{ state_attr('light.basement_color','xy_color') }}"

# ==================================================================================================
#
# Templates
#
# Need to eventually convert these into the new 'template:' style.  This currently doesn't seem
# to work inside packages.
#
# https://www.home-assistant.io/integrations/template/
#
# ==================================================================================================
template:
  - binary_sensor:
      - unique_id: "64ca8117-0ecc-4dab-b821-b67f08fe10f0"
        name: "[Light] Basement Autobrightness"
        state: >-
          {{ (
               state_attr("switch.adaptive_lighting_basement", "brightness_pct") | int ) <
               ( state_attr("binary_sensor.light_basement_autobrightness", "brightness_max")
               | int )
             and ( state_attr("switch.adaptive_lighting_basement", "brightness_pct") | int ) >
             ( state_attr("binary_sensor.light_basement_autobrightness", "brightness_min") | int
             ) }}
        attributes:
          brightness: >-
            {% if state_attr("light.basement", "brightness") == None or
               is_state_attr("light.basement", "brightness", "unknown") or
               is_state("light.basement", "off") %}
              {{ ( state_attr("switch.adaptive_lighting_basement", "brightness_pct" ) | int | int ) }}
            {% else %}
              {{ ( state_attr("light.basement","brightness") / 254 * 100 ) | int }}
            {% endif %}
          brightness_max: >-
            {{ state_attr("binary_sensor.light_basement_autobrightness", "brightness") | int + 4 }}
          brightness_min: >-
            {{ state_attr("binary_sensor.light_basement_autobrightness", "brightness") | int - 4 }}
