# ==================================================================================================
#
# Basement
#
# Lights:
#   - light.basement_lamp_
#   - light.basement_lamp_
#   - light.basement_lamp_
#
# Light Groups:
#   - light.basement
#
# ==================================================================================================

# ==================================================================================================
#
# Automations
#
#
#
# ==================================================================================================
automation:
  - id: '07bb38d4-9581-4268-a6cb-821f8dd9367e'
    alias: '[Light] BF1: All - Turn Off Lights At Night'
    initial_state: false
    description: ''
    trigger:
      - at: '21:30'
        platform: time
    condition: []
    action:
      - service: light.turn_off
        data:
          entity_id: light.bf1_all
    mode: single

light:
  - platform: group
    name: "BF: All"
    entities:
      - light.bf1_all

# ======================================================================
#
# Input Select
#
# ======================================================================
# input_select:
#   hue_scene_basement_bedroom:
#     name: "[Light] Hue Basement Scene"
#     icon: mdi:palette
#     initial: "Circadian"
#     options:
#       - Arctic aurora
#       - Sevanna sunset
#       - Tropical twilight
#       - Spring blossom
#       - Relax
#       - Read
#       - Concentrate
#       - Energize
#       - Bright
#       - Dimmed
#       - Nightlight
#       - Motown
#       - Midsomer Sun
#       - Midwinter
#       - Ocean Dawn
#       - Emerald Isle
#       - Mountain Breeze
#       - Spring lake
#       - Moonlight
#       - Starlight
#       - Soho
#       - Golden Pond
#       - Frosty Dawn
#       - Fairfax
#       - Autumn Gold
#       - Palm Beach
#       - Lake Mist
#       - Chinatown
#       - Tokyo
#       - Sunday Morning
#       - Ibiza
#       - Nebula
#       - Galaxy
#       - Ruby Glow
#       - Winter mountain
#       - Blue Lagoon
#       - Honolulu
#       - Lake Placid
#       - Osaka
#       - Sundowner
#       - Blood Moon
#       - Circadian
#       - Night Mode
#       - Migraine

# ==================================================================================================
#
# Rest Command
#
# Light IDs:
# - 01: e687cdcb-7022-4d66-9763-ec5ead8f8808
#   name: BF Kitchen CF1 Bulb
# - 02: 068c9cd1-0128-423b-b0f4-e9bc57e0308e
#   name: BF Stairwell Bulb
# - 03: 3781ec36-a5a4-4d11-9965-5f453a3004b4
#   name: BF Storage1 CF2 Bulb
# - 04: 84e56e8b-a96f-4a25-9715-4ecc0921ab8d
#   name: BF Den Lamp 2 Bulb
# - 05: 12fe02ef-c867-4eae-982e-f8fdf9e0ba23
#   name: BF Storage1 Bulb 1
# - 06: e464775c-3b2b-453d-b7cf-e7def42610f6
#   name: BF Den Lamp 3 Bulb 1
# - 07: 2b238059-189a-4f70-b33a-6b6948b70dc7
#   name: BF Den CF1 Bulb
# - 08: b02df779-caaa-446a-8e0e-e73e069f9cbd
#   name: BF Den CF2 Bulb
# - 09: 5d9e8921-1307-4181-826e-55c3a05e14ac
#   name: BF Den Lamp 1 Bulb
# - 10: ae1340a6-0178-4eb5-8b4a-c166abd7a297
#   name: BF Hallway CF Bulb 1
# - 11: 557f80c4-02a7-4944-8591-53eb8c33cb95
#   name: BF Hallway CF Bulb 3
# - 12: 8677b6df-8d08-4eba-a4c5-927d3321915d
#   name: BF Den Lamp 3 Bulb 2
#
# ==================================================================================================
rest_command:
  light_update_bf1_all_scene:
    url: "https://hue2.iot.home/clip/v2/resource/scene/{{ scene_id }}"
    method: put
    headers:
      hue-application-key: "{{ username }}"
    payload: '{
          "id":"{{ scene_id }}",
          "actions":[
          {
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"12fe02ef-c867-4eae-982e-f8fdf9e0ba23","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"e687cdcb-7022-4d66-9763-ec5ead8f8808","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"557f80c4-02a7-4944-8591-53eb8c33cb95","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"3781ec36-a5a4-4d11-9965-5f453a3004b4","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"068c9cd1-0128-423b-b0f4-e9bc57e0308e","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"b02df779-caaa-446a-8e0e-e73e069f9cbd","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"2b238059-189a-4f70-b33a-6b6948b70dc7","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"e464775c-3b2b-453d-b7cf-e7def42610f6","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"ae1340a6-0178-4eb5-8b4a-c166abd7a297","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"84e56e8b-a96f-4a25-9715-4ecc0921ab8d","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"5d9e8921-1307-4181-826e-55c3a05e14ac","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"8677b6df-8d08-4eba-a4c5-927d3321915d","rtype":"light"}
          }
          ]
          }'
    verify_ssl: false
    content_type: "application/json"

  light_update_bf1_all_scene_complex:
    url: "https://hue2.iot.home/clip/v2/resource/scene/{{ scene_id }}"
    method: put
    headers:
      hue-application-key: "{{ username }}"
    payload: '{
          "id":"{{ scene_id }}",
          "actions":[
          {
          "action":{ {{ bulb_01_color }},{{ bulb_01_brightness }},{{ bulb_01_on_state }} },
          "target":{"rid":"12fe02ef-c867-4eae-982e-f8fdf9e0ba23","rtype":"light"}
          },{
          "action":{ {{ bulb_02_color }},{{ bulb_02_brightness }},{{ bulb_02_on_state }} },
          "target":{"rid":"e687cdcb-7022-4d66-9763-ec5ead8f8808","rtype":"light"}
          },{
          "action":{ {{ bulb_03_color }},{{ bulb_03_brightness }},{{ bulb_03_on_state }} },
          "target":{"rid":"557f80c4-02a7-4944-8591-53eb8c33cb95","rtype":"light"}
          },{
          "action":{ {{ bulb_04_color }},{{ bulb_04_brightness }},{{ bulb_04_on_state }} },
          "target":{"rid":"3781ec36-a5a4-4d11-9965-5f453a3004b4","rtype":"light"}
          },{
          "action":{ {{ bulb_05_color }},{{ bulb_05_brightness }},{{ bulb_05_on_state }} },
          "target":{"rid":"068c9cd1-0128-423b-b0f4-e9bc57e0308e","rtype":"light"}
          },{
          "action":{ {{ bulb_06_color }},{{ bulb_06_brightness }},{{ bulb_06_on_state }} },
          "target":{"rid":"b02df779-caaa-446a-8e0e-e73e069f9cbd","rtype":"light"}
          },{
          "action":{ {{ bulb_07_color }},{{ bulb_07_brightness }},{{ bulb_07_on_state }} },
          "target":{"rid":"2b238059-189a-4f70-b33a-6b6948b70dc7","rtype":"light"}
          },{
          "action":{ {{ bulb_08_color }},{{ bulb_08_brightness }},{{ bulb_08_on_state }} },
          "target":{"rid":"e464775c-3b2b-453d-b7cf-e7def42610f6","rtype":"light"}
          },{
          "action":{ {{ bulb_09_color }},{{ bulb_09_brightness }},{{ bulb_09_on_state }} },
          "target":{"rid":"ae1340a6-0178-4eb5-8b4a-c166abd7a297","rtype":"light"}
          },{
          "action":{ {{ bulb_10_color }},{{ bulb_10_brightness }},{{ bulb_10_on_state }} },
          "target":{"rid":"84e56e8b-a96f-4a25-9715-4ecc0921ab8d","rtype":"light"}
          },{
          "action":{ {{ bulb_11_color }},{{ bulb_11_brightness }},{{ bulb_11_on_state }} },
          "target":{"rid":"5d9e8921-1307-4181-826e-55c3a05e14ac","rtype":"light"}
          },{
          "action":{ {{ bulb_12_color }},{{ bulb_12_brightness }},{{ bulb_12_on_state }} },
          "target":{"rid":"8677b6df-8d08-4eba-a4c5-927d3321915d","rtype":"light"}
          }
          ]
          }'
    verify_ssl: false
    content_type: "application/json"

# ==================================================================================================
#
# Scenes
#
# Notes:
#
# Brightness settings:
#  100% = 255
#   75% = 192
#   50% = 128
#   25% =  64
#
# Colors:
#   Red = xy [0.6915,0.3083]
# Green = xy [0.17,0.7]
#
# ==================================================================================================
scene:
  - id: "29d35002-68ed-4cfe-bcd3-552e55c219c1"
    name: "[Light] BF1: All - Enable Automations"
    entities:
      automation.light_basement_turn_off_lights_at_night:
        state: "on"

  - id: "68dcd95f-bf3f-42d7-bb84-6b50af2bb70e"
    name: "[Light] BF1: All - Darken"
    entities:
      light.bf_den_lamp_2_bulb:
        state: "on"
        xy_color:
          - 0.6915
          - 0.3083
        brightness: 64
      light.bf_den_cf1_bulb:
        state: "on"
        xy_color:
          - 0.6915
          - 0.3083
        brightness: 64
      light.bf_den_cf2_bulb:
        state: "off"
      light.bf_den_lamp_1_bulb:
        state: "off"
      light.bf_den_lamp3_bulb_1:
        state: "off"
      light.bf_den_lamp3_bulb_2:
        state: "off"
      light.bf_hallway_cf_bulb_1:
        state: "off"
      light.bf_hallway_cf_bulb_3:
        state: "off"
      light.bf_kitchen_cf1_bulb:
        state: "off"
      light.bf_stairwell_bulb:
        state: "off"
      light.bf_storage1_cf1_bulb:
        state: "off"
      light.bf_storage1_cf2_bulb:
        state: "off"

  - id: "d8c9b5de-8ed7-4403-87ee-172feb15d9a5"
    name: "[Light] BF1: All - Migraine"
    entities:
      light.bf_den_lamp_2_bulb:
        state: "on"
        xy_color:
          - 0.17
          - 0.7
        brightness: 64
      light.bf_den_cf1_bulb:
        state: "on"
        xy_color:
          - 0.17
          - 0.7
        brightness: 64
      light.bf_den_cf2_bulb:
        state: "off"
      light.bf_den_lamp_1_bulb:
        state: "off"
      light.bf_den_lamp3_bulb_1:
        state: "off"
      light.bf_den_lamp3_bulb_2:
        state: "off"
      light.bf_hallway_cf_bulb_1:
        state: "off"
      light.bf_hallway_cf_bulb_3:
        state: "off"
      light.bf_kitchen_cf1_bulb:
        state: "off"
      light.bf_stairwell_bulb:
        state: "off"
      light.bf_storage1_cf1_bulb:
        state: "off"
      light.bf_storage1_cf2_bulb:
        state: "off"

  - id: "10fd713e-b10b-4e3d-833b-3ea63816b5de"
    name: "[Light] BF1: All - Bright"
    entities:
      light.basement:
        state: "on"
        color_temp: 367
        brightness: 255

  - id: "22b7c3af-0991-4f83-b2b2-6d51f1df089c"
    name: "[Light] BF1: All - Concentrate"
    entities:
      light.basement:
        state: "on"
        color_temp: 230
        brightness: 255

  - id: "9e5f60ca-caae-41b3-bd7b-7fce33bcc436"
    name: "[Light] BF1: All - Dimmed"
    entities:
      light.basement:
        state: "on"
        color_temp: 369
        brightness: 76

  - id: "126a563d-3826-4d00-81e1-abca1a6869b2"
    name: "[Light] BF1: All - Energize"
    entities:
      light.basement:
        state: "on"
        color_temp: 156
        brightness: 255

  - id: "50d190ae-8d62-4716-ac9c-3ef5757a1009"
    name: "[Light] BF1: All - Nightlight"
    entities:
      light.basement:
        state: "on"
        color_temp: 454
        brightness: 1

  - id: "3e72d0b5-c2f2-4f4e-87df-67bc7c63882d"
    name: "[Light] BF1: All - Read"
    entities:
      light.basement:
        state: "on"
        color_temp: 343
        brightness: 255

  - id: "fbe2e3db-c839-42d6-86de-c879baf8673e"
    name: "[Light] BF1: All - Relax"
    entities:
      light.basement:
        state: "on"
        color_temp: 447
        brightness: 145

  - id: "b448b6d9-fc73-4f87-8cd9-f0df64dd350d"
    name: "[Light] BF1: All - Off"
    entities:
      light.basement:
        state: "off"
