---
# ==================================================================================================
#
# Basement
#
# Lights:
#   - light.basement_lamp_
#   - light.basement_lamp_
#   - light.basement_lamp_
#
# Light Groups:
#   - light.basement
#
# ==================================================================================================

# ==================================================================================================
#
# Automations
#
#
#
# ==================================================================================================
automation:
  - id: "07bb38d4-9581-4268-a6cb-821f8dd9367e"
    alias: "[Light] BF: All - Turn Off Lights At Night"
    description: ""
    trigger:
      - at: "21:30"
        platform: time
    condition: []
    action:
      - service: light.turn_off
        data:
          entity_id: light.bf_all
    mode: single

  # ================================================================================================
  #
  #
  #
  # ================================================================================================
  - id: "739ebd7a-cda1-4b99-81f8-ce568864893a"
    alias: "BF1: All - Auto populate Hue dynamic scene input select"
    description: ""
    trigger:
      - platform: event
        event_type: delayed_homeassistant_start
    action:
      service: input_select.set_options
      target:
        entity_id: input_select.bf1_all_lights_dynamic_scenes
      data:
        options: >
          {{ states.scene
            | selectattr("attributes.group_name","eq","BF1: All")
            | selectattr("attributes.is_dynamic","eq",true)
            | map(attribute="name")
            | list }}
    mode: restart

  - id: "754e17ab-94f2-48a0-ac5b-9e01fa156873"
    alias: "BF1: All - Update Selected Scene"
    trigger:
      - platform: state
        entity_id: input_select.bf1_all_lights_scene
    condition:
      - condition: template
        value_template: "{{ trigger.to_state != trigger.from_state }}"
    action:
      service: scene.turn_on
      data_template:
        entity_id: >
          {{ states('input_select.bf1_all_lights_scene') }}
    mode: single

# ==================================================================================================
#
#
#
# ==================================================================================================
#input_boolean:

# ==================================================================================================
#
# Input Number
#
# ==================================================================================================
input_number:
  bf1_all_dynamic_scene_speed:
    name: "BF1: All - Dynamic Scene Speed"
    min: 0
    max: 100
    step: 10

  bf1_all_dynamic_scene_brightness:
    name: "BF1: All - Dynamic Scene Brightness"
    min: 0
    max: 255
    step: 10

# ==================================================================================================
#
# Input Select
#
# ==================================================================================================
input_select:
  # bf_all_lights_scene:
  #   name: "BF1: All Lights - Scenes"
  #   options:
  #     - scene.bf1_all_bright
  #     - scene.bf1_all_candle
  #     - scene.bf1_all_concentrate
  #     - scene.bf1_all_darken
  #     - scene.bf1_all_dimmed
  #     - scene.bf1_all_energize
  #     - scene.bf1_all_fireplace
  #     - scene.bf1_all_homeassistant
  #     - scene.bf1_all_migraine
  #     - scene.bf1_all_nightlight
  #     - scene.bf1_all_read
  #     - scene.bf1_all_relax
  #     - scene.bf1_all_dynamic

  bf1_all_lights_scene:
    name: "BF1: All Lights - Scenes"
    options:
      - scene.bf1_all_bright
      - scene.bf1_all_candle
      - scene.bf1_all_concentrate
      - scene.bf1_all_darken
      - scene.bf1_all_dimmed
      - scene.bf1_all_energize
      - scene.bf1_all_fireplace
      - scene.bf1_all_homeassistant
      - scene.bf1_all_migraine
      - scene.bf1_all_nightlight
      - scene.bf1_all_read
      - scene.bf1_all_relax
      - scene.bf1_all_dynamic

  bf1_dynamic_scenes:
    name: "BF1: All - Dynamic Scene"
    options:
      - Blossom
      - Crocus
      - Precious
      - Narcissa
      - Honolulu
      - Savanna sunset
      - Golden pond
      - Ruby glow
      - Tropical twilight
      - Miami
      - Cancun
      - Rio
      - Chinatown
      - Ibiza
      - Osaka
      - Tokyo
      - Motown
      - Fairfax
      - Galaxy
      - Starlight
      - Blood moon
      - Arctic aurora
      - Moonlight
      - Nebula
      - Lovebirds
      - Smitten
      - Glitz and glam

  bf_scene_sequences:
    name: "BF: All Scene Sequences"
    options:
      - None
      - Serenity

# ==================================================================================================
#
# Input Text
#
# ==================================================================================================
input_text:
  bf1_all_scene_homeassistant:
    min: 36
    max: 36

# ==================================================================================================
#
# Light
#
# ==================================================================================================
light:
  - platform: group
    unique_id: "06ca56aa-d248-4620-878f-2aa54fe54d8b"
    name: "BF: All"
    entities:
      - light.bf1_all

  - platform: template
    lights:
      bf1_all_alt:
        friendly_name: "BF1: All (Alt)"
        unique_id: "58831bb7-9e66-4dee-b2bc-48e659c3f734"
        value_template: "{{ is_state('light.bf1_all', 'on') }}"
        level_template: "{{ state_attr('light.bf1_all','brightness') | int(255) }}"
        temperature_template: "{{ state_attr('light.bf1_all','color_temp') | int(367) }}"
        color_template: "{{ state_attr('light.bf1_all','hs_color') }}"
        min_mireds_template: "{{ state_attr('light.bf1_all','min_mireds') | int(100) }}"
        max_mireds_template: "{{ state_attr('light.bf1_all','max_mireds') | int(500) }}"
        #effect_list_template: "{{ state_attr('input_select.bf1_all_lights_scene', 'options') }}"
        turn_on:
          service: scene.turn_on
          data_template:
            entity_id: >
              {{ states('input_select.bf1_all_scene') }}
        turn_off:
          service: light.turn_off
          target:
            entity_id: light.bf1_all
        set_level:
          service: light.turn_on
          target:
            entity_id: light.bf1_all
          data:
            brightness: "{{ brightness }}"
        set_temperature:
          service: light.turn_on
          target:
            entity_id: light.bf1_all
          data:
            color_temp: "{{ color_temp }}"
        set_color:
          service: light.turn_on
          target:
            entity_id: light.bf1_all
          data:
            hs_color:
              - "{{ hs[0] }}"
              - "{{ hs[1] }}"
        # set_effect:
        #   - service: scene.turn_on
        #     data_template:
        #       entity_id: >-
        #         {{ states('input_select.bf1_all_scene') }}
        supports_transition_template: "{{ true }}"

# ==================================================================================================
#
# Scenes
#
# Notes:
#
# Brightness settings:
#  100% = 255
#   75% = 192
#   50% = 128
#   25% =  64
#
# Colors:
#   Red = xy [0.6915,0.3083]
# Green = xy [0.17,0.7]
#
# ==================================================================================================
scene:
  - id: "29d35002-68ed-4cfe-bcd3-552e55c219c1"
    name: "[Light] BF1: All - Enable Automations"
    entities:
      automation.light_bf1_all_turn_off_lights_at_night:
        state: "on"

# ==================================================================================================
#
# Scripts
#
# ==================================================================================================
script:
  bf1_all_lights_sunrise:
    alias: "BF1: All - Sunrise sequence"
    mode: single
    sequence:
      - service: hue.activate_scene
        data:
          dynamic: true
          transition: 600
        target:
          entity_id: scene.bf1_all_beginnings
        metadata: {}

  bf_adv_daily_demo:
    alias: "BF: All - Advanced Daily Demo"
    sequence:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.bf1_den_cf1_adaptive_lighting
            - switch.bf1_den_cf2_adaptive_lighting
            - switch.bf1_den_lamp1_adaptive_lighting
            - switch.bf1_den_lamp2_adaptive_lighting
            - switch.bf1_den_lamp3_adaptive_lighting
            - switch.bf1_hallway_adaptive_lighting
            - switch.bf1_kitchen_adaptive_lighting
            - switch.bf1_stairwell_adaptive_lighting
            - switch.bf1_storage1_adaptive_lighting
            - switch.bf1_storage2_adaptive_lighting

      - service: light.turn_off
        target:
          entity_id:
            - light.bf_all

      - alias: "Wait 10s"
        delay: 10

      - service: hue.activate_scene
        data:
          dynamic: true
          transition: 21
        target:
          entity_id:
            - scene.bf1_all_beginnings

      - alias: "Wait 21s"
        delay: 21

      - service: hue.activate_scene
        data:
          dynamic: true
          transition: 13
        target:
          entity_id:
            - scene.bf1_all_first_light

      - alias: "Wait 13s"
        delay: 13

      - service: hue.activate_scene
        data:
          dynamic: true
          transition: 8
        target:
          entity_id:
            - scene.bf1_all_horizon

      - alias: "Wait 8s"
        delay: 8

      - service: hue.activate_scene
        data:
          dynamic: true
          transition: 5
        target:
          entity_id:
            - scene.bf1_all_horizon

      - alias: "Wait 5s"
        delay: 5

      - service: hue.activate_scene
        data:
          dynamic: true
          transition: 3
        target:
          entity_id:
            - scene.bf1_all_valley_dawn

      - alias: "Wait 8s"
        delay: 3

      - service: hue.activate_scene
        data:
          dynamic: true
          transition: 2
        target:
          entity_id:
            - scene.bf1_all_sunflare

      - alias: "Wait 8s"
        delay: 2

      - service: light.turn_on
        data:
          color_temp: 500
          transition: 2
          brightness: 100
        target:
          entity_id:
            - light.bf1_all

      - alias: "Wait 8s"
        delay: 2

      - service: light.turn_on
        data:
          color_temp: 153
          transition: 90
          brightness: 100
        target:
          entity_id:
            - light.bf1_all

      - alias: "Wait 90s"
        delay: 90

      - service: light.turn_on
        data:
          color_temp: 500
          transition: 90
          brightness: 100
        target:
          entity_id:
            - light.bf1_all

      - alias: "Wait 90s"
        delay: 90

      - service: light.turn_on
        data:
          color_temp: 500
          transition: 30
          brightness: 25
        target:
          entity_id:
            - light.bf1_all

      - alias: "Wait 8s"
        delay: 30

      - service: light.turn_off
        target:
          entity_id:
            - light.bf_all

      - alias: "Wait 90s"
        delay: 90

      - service: hue.activate_scene
        target:
          entity_id:
            - scene.bf1_all_sleep

      - alias: "Wait 90s"
        delay: 90

      - service: hue.activate_scene
        target:
          entity_id:
            - scene.bf1_all_homeassistant

      - service: switch.turn_on
        target:
          entity_id:
            - switch.bf1_den_cf1_adaptive_lighting
            - switch.bf1_den_cf2_adaptive_lighting
            - switch.bf1_den_lamp1_adaptive_lighting
            - switch.bf1_den_lamp2_adaptive_lighting
            - switch.bf1_den_lamp3_adaptive_lighting
            - switch.bf1_hallway_adaptive_lighting
            - switch.bf1_kitchen_adaptive_lighting
            - switch.bf1_stairwell_adaptive_lighting
            - switch.bf1_storage1_adaptive_lighting
            - switch.bf1_storage2_adaptive_lighting

  bf_daily_demo:
    alias: "BF: All - Daily Demo"
    sequence:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.bf1_den_cf1_adaptive_lighting
            - switch.bf1_den_cf2_adaptive_lighting
            - switch.bf1_den_lamp1_adaptive_lighting
            - switch.bf1_den_lamp2_adaptive_lighting
            - switch.bf1_den_lamp3_adaptive_lighting
            - switch.bf1_hallway_adaptive_lighting
            - switch.bf1_kitchen_adaptive_lighting
            - switch.bf1_stairwell_adaptive_lighting
            - switch.bf1_storage1_adaptive_lighting
            - switch.bf1_storage2_adaptive_lighting

      - service: light.turn_off
        target:
          entity_id:
            - light.bf_all

      - alias: "Wait 10s"
        delay: 10

      - service: light.turn_on
        data:
          color_temp: 500
          transition: 30
          brightness: 100
        target:
          entity_id:
            - light.bf1_all

      - alias: "Wait 30s"
        delay: 30

      - service: light.turn_on
        data:
          color_temp: 153
          transition: 90
          brightness: 100
        target:
          entity_id:
            - light.bf1_all

      - alias: "Wait 90s"
        delay: 90

      - service: light.turn_on
        data:
          color_temp: 500
          transition: 90
          brightness: 100
        target:
          entity_id:
            - light.bf1_all

      - alias: "Wait 90s"
        delay: 90

      - service: light.turn_on
        data:
          color_temp: 500
          transition: 30
          brightness: 25
        target:
          entity_id:
            - light.bf1_all

      - alias: "Wait 8s"
        delay: 30

      - service: light.turn_off
        target:
          entity_id:
            - light.bf_all

      - alias: "Wait 90s"
        delay: 90

      - service: hue.activate_scene
        target:
          entity_id:
            - scene.bf1_all_sleep

      - alias: "Wait 90s"
        delay: 90

      - service: hue.activate_scene
        target:
          entity_id:
            - scene.bf1_all_homeassistant

      - service: switch.turn_on
        target:
          entity_id:
            - switch.bf1_den_cf1_adaptive_lighting
            - switch.bf1_den_cf2_adaptive_lighting
            - switch.bf1_den_lamp1_adaptive_lighting
            - switch.bf1_den_lamp2_adaptive_lighting
            - switch.bf1_den_lamp3_adaptive_lighting
            - switch.bf1_hallway_adaptive_lighting
            - switch.bf1_kitchen_adaptive_lighting
            - switch.bf1_stairwell_adaptive_lighting
            - switch.bf1_storage1_adaptive_lighting
            - switch.bf1_storage2_adaptive_lighting

  bf1_all_lights_serenity:
    alias: "BF: All - Serenity Sequence"
    sequence:
      - alias: "Set Hue Scene Sequence to 'Serenity'"
        service: input_select.select_option
        data_template:
          entity_id: input_select.bf_scene_sequences
          option: "Serenity"
      - alias: "Cycle through Hue Serenity Scenes."
        repeat:
          while:
            - condition: state
              entity_id: input_select.bf_scene_sequences
              state: "Serenity"
            # Don't do it too many times
            - condition: template
              value_template: "{{ repeat.index <= 20 }}"
          sequence:
            - service: hue.activate_scene
              data:
                dynamic: true
                transition: 1
              target:
                entity_id:
                  - scene.bf1_all_galaxy

            - alias: "Wait 10 minutes"
              delay: 600

            - service: hue.activate_scene
              data:
                dynamic: true
                transition: 1
              target:
                entity_id:
                  - scene.bf1_all_starlight

            - alias: "Wait 10 minutes"
              delay: 600

            - service: hue.activate_scene
              data:
                dynamic: true
                transition: 1
              target:
                entity_id:
                  - scene.bf1_all_blood_moon

            - alias: "Wait 10 minutes"
              delay: 600

            - service: hue.activate_scene
              data:
                dynamic: true
                transition: 1
              target:
                entity_id:
                  - scene.bf1_all_arctic_aurora

            - alias: "Wait 10 minutes"
              delay: 600

            - service: hue.activate_scene
              data:
                dynamic: true
                transition: 1
              target:
                entity_id:
                  - scene.bf1_all_moonlight

            - alias: "Wait 10 minutes"
              delay: 600

            - service: hue.activate_scene
              data:
                dynamic: true
                transition: 1
              target:
                entity_id:
                  - scene.bf1_all_nebula

            - alias: "Wait 10 minutes"
              delay: 600

      - alias: "Return to prior state."
        service: hue.activate_scene
        data:
          transition: 1
        target:
          entity_id:
            - scene.bf1_all_homeassistant
