# ==================================================================================================
#
# Basement
#
# Lights:
#   - light.basement_lamp_
#   - light.basement_lamp_
#   - light.basement_lamp_
#
# Light Groups:
#   - light.basement
#
# ==================================================================================================

# ==================================================================================================
#
# Automations
#
#
#
# ==================================================================================================
automation:
  - id: '07bb38d4-9581-4268-a6cb-821f8dd9367e'
    alias: '[Light] BF: All - Turn Off Lights At Night'
    initial_state: false
    description: ''
    trigger:
      - at: '21:30'
        platform: time
    condition: []
    action:
      - service: light.turn_off
        data:
          entity_id: light.bf_all
    mode: single

  # ================================================================================================
  #
  #
  #
  # ================================================================================================
  - id: "739ebd7a-cda1-4b99-81f8-ce568864893a"
    alias: "BF1: All - Auto populate Hue dynamic scene input select"
    mode: restart
    trigger:
      - platform: event
        event_type: delayed_homeassistant_start
      - platform: state
        entity_id: input_select.hue_group
    action:
      service: input_select.set_options
      target:
        entity_id: input_select.bf1_all_lights_dynamic_scenes
      data:
        options: >
          {{ states.scene
            | selectattr('attributes.group_name','eq','BF1: All')
            | selectattr('attributes.is_dynamic','eq',true)
            | map(attribute='name')
            | list }}

# ==================================================================================================
#
#
#
# ==================================================================================================
input_boolean:
  bf1_all_lights:
    name: "BF1: All Lights"

# ==================================================================================================
#
# Input Number
#
# ==================================================================================================
input_number:
  bf1_all_dynamic_scene_speed:
    name: "BF1: All - Dynamic Scene Speed"
    min: 0
    max: 100
    step: 10

  bf1_all_dynamic_scene_brightness:
    name: "BF1: All - Dynamic Scene Brightness"
    min: 0
    max: 255
    step: 10

# ==================================================================================================
#
# Input Select
#
# ==================================================================================================
input_select:
  bf1_all_lights_scene:
    name: "BF1: All Lights - Scenes"
    options:
      - scene.bf1_all_bright
      - scene.bf1_all_candle
      - scene.bf1_all_concentrate
      - scene.bf1_all_darken
      - scene.bf1_all_dimmed
      - scene.bf1_all_energize
      - scene.bf1_all_fireplace
      - scene.bf1_all_homeassistant
      - scene.bf1_all_migraine
      - scene.bf1_all_nightlight
      - scene.bf1_all_read
      - scene.bf1_all_relax
      - scene.bf1_all_dynamic

  bf1_all_lights_dynamic_scenes:
    name: "BF1: All Lights - Dynamic Scenes"
    options:
      - Bright

# ==================================================================================================
#
# Light
#
# ==================================================================================================
light:
  - platform: group
    unique_id: "06ca56aa-d248-4620-878f-2aa54fe54d8b"
    name: "BF: All"
    entities:
      - light.bf1_all

# ==================================================================================================
#
# Rest Command
#
# Light IDs:
# - 01: e687cdcb-7022-4d66-9763-ec5ead8f8808
#   name: BF1 Kitchen CF1 Bulb
# - 02: 068c9cd1-0128-423b-b0f4-e9bc57e0308e
#   name: BF1 Stairwell Bulb
# - 03: 9393d087-3b37-4b3b-be15-49ad8d1da861
#   name: BF1 Storage2 Lamp1 Bulb1
# - 04: 3781ec36-a5a4-4d11-9965-5f453a3004b4
#   name: BF1 Storage1 CF2 Bulb1
# - 05: 8677b6df-8d08-4eba-a4c5-927d3321915d
#   name: BF1 Den Lamp3 Bulb2
# - 06: b159cfed-04ac-43b4-b390-2c3d1eb29ecb
#   name: BF1 Hallway CF Bulb2
# - 07: 84e56e8b-a96f-4a25-9715-4ecc0921ab8d
#   name: BF1 Den Lamp2 Bulb1
# - 08: 12fe02ef-c867-4eae-982e-f8fdf9e0ba23
#   name: BF Storage1 CF1 Bulb1
# - 09: e464775c-3b2b-453d-b7cf-e7def42610f6
#   name: BF1 Den Lamp3 Bulb1
# - 10: 2f340335-486f-4c67-921b-e7d8c33f581f
#   name: BF1 Storage2 Lamp2 Bulb1
# - 11: 2b238059-189a-4f70-b33a-6b6948b70dc7
#   name: BF1 Den CF1 Bulb1
# - 12: b02df779-caaa-446a-8e0e-e73e069f9cbd
#   name: BF2 Den CF2 Bulb1
# - 13: bbf6ca34-f834-4ffb-8f94-bb9165d0ed57
#   name: BF1 Storage2 Lamp3 Bulb1
# - 14: 5d9e8921-1307-4181-826e-55c3a05e14ac
#   name: BF2 Den Lamp1 Bulb1
# - 15: ae1340a6-0178-4eb5-8b4a-c166abd7a297
#   name: BF2 Hallway CF Bulb1
# - 16: 557f80c4-02a7-4944-8591-53eb8c33cb95
#   name: BF2 Hallway CF Bulb3
#
# ==================================================================================================
rest_command:
  light_update_bf1_all_scene:
    url: "https://hue2.iot.home/clip/v2/resource/scene/{{ scene_id }}"
    method: put
    headers:
      hue-application-key: "{{ username }}"
    payload: '{
          "id":"{{ scene_id }}",
          "actions":[
          {
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"e687cdcb-7022-4d66-9763-ec5ead8f8808","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"068c9cd1-0128-423b-b0f4-e9bc57e0308e","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"9393d087-3b37-4b3b-be15-49ad8d1da861","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"3781ec36-a5a4-4d11-9965-5f453a3004b4","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"8677b6df-8d08-4eba-a4c5-927d3321915d","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"b159cfed-04ac-43b4-b390-2c3d1eb29ecb","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"84e56e8b-a96f-4a25-9715-4ecc0921ab8d","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"12fe02ef-c867-4eae-982e-f8fdf9e0ba23","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"e464775c-3b2b-453d-b7cf-e7def42610f6","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"2f340335-486f-4c67-921b-e7d8c33f581f","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"2b238059-189a-4f70-b33a-6b6948b70dc7","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"b02df779-caaa-446a-8e0e-e73e069f9cbd","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"bbf6ca34-f834-4ffb-8f94-bb9165d0ed57","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"5d9e8921-1307-4181-826e-55c3a05e14ac","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"ae1340a6-0178-4eb5-8b4a-c166abd7a297","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"557f80c4-02a7-4944-8591-53eb8c33cb95","rtype":"light"}
          }
          ]
          }'
    verify_ssl: false
    content_type: "application/json"

  light_update_bf1_all_scene_complex:
    url: "https://hue2.iot.home/clip/v2/resource/scene/{{ scene_id }}"
    method: put
    headers:
      hue-application-key: "{{ username }}"
    payload: '{
          "id":"{{ scene_id }}",
          "actions":[
          {
          "action":{ {{ bulb_01_color }},{{ bulb_01_brightness }},{{ bulb_01_on_state }} },
          "target":{"rid":"12fe02ef-c867-4eae-982e-f8fdf9e0ba23","rtype":"light"}
          },{
          "action":{ {{ bulb_02_color }},{{ bulb_02_brightness }},{{ bulb_02_on_state }} },
          "target":{"rid":"e687cdcb-7022-4d66-9763-ec5ead8f8808","rtype":"light"}
          },{
          "action":{ {{ bulb_03_color }},{{ bulb_03_brightness }},{{ bulb_03_on_state }} },
          "target":{"rid":"557f80c4-02a7-4944-8591-53eb8c33cb95","rtype":"light"}
          },{
          "action":{ {{ bulb_04_color }},{{ bulb_04_brightness }},{{ bulb_04_on_state }} },
          "target":{"rid":"3781ec36-a5a4-4d11-9965-5f453a3004b4","rtype":"light"}
          },{
          "action":{ {{ bulb_05_color }},{{ bulb_05_brightness }},{{ bulb_05_on_state }} },
          "target":{"rid":"068c9cd1-0128-423b-b0f4-e9bc57e0308e","rtype":"light"}
          },{
          "action":{ {{ bulb_06_color }},{{ bulb_06_brightness }},{{ bulb_06_on_state }} },
          "target":{"rid":"b02df779-caaa-446a-8e0e-e73e069f9cbd","rtype":"light"}
          },{
          "action":{ {{ bulb_07_color }},{{ bulb_07_brightness }},{{ bulb_07_on_state }} },
          "target":{"rid":"2b238059-189a-4f70-b33a-6b6948b70dc7","rtype":"light"}
          },{
          "action":{ {{ bulb_08_color }},{{ bulb_08_brightness }},{{ bulb_08_on_state }} },
          "target":{"rid":"e464775c-3b2b-453d-b7cf-e7def42610f6","rtype":"light"}
          },{
          "action":{ {{ bulb_09_color }},{{ bulb_09_brightness }},{{ bulb_09_on_state }} },
          "target":{"rid":"ae1340a6-0178-4eb5-8b4a-c166abd7a297","rtype":"light"}
          },{
          "action":{ {{ bulb_10_color }},{{ bulb_10_brightness }},{{ bulb_10_on_state }} },
          "target":{"rid":"84e56e8b-a96f-4a25-9715-4ecc0921ab8d","rtype":"light"}
          },{
          "action":{ {{ bulb_11_color }},{{ bulb_11_brightness }},{{ bulb_11_on_state }} },
          "target":{"rid":"5d9e8921-1307-4181-826e-55c3a05e14ac","rtype":"light"}
          },{
          "action":{ {{ bulb_12_color }},{{ bulb_12_brightness }},{{ bulb_12_on_state }} },
          "target":{"rid":"8677b6df-8d08-4eba-a4c5-927d3321915d","rtype":"light"}
          }
          ]
          }'
    verify_ssl: false
    content_type: "application/json"

# ==================================================================================================
#
# Scenes
#
# Notes:
#
# Brightness settings:
#  100% = 255
#   75% = 192
#   50% = 128
#   25% =  64
#
# Colors:
#   Red = xy [0.6915,0.3083]
# Green = xy [0.17,0.7]
#
# ==================================================================================================
scene:
  - id: "29d35002-68ed-4cfe-bcd3-552e55c219c1"
    name: "[Light] BF1: All - Enable Automations"
    entities:
      automation.light_bf1_all_turn_off_lights_at_night:
        state: "on"

  - id: "68dcd95f-bf3f-42d7-bb84-6b50af2bb70e"
    name: "[Light] BF1: All - Darken"
    entities:
      light.bf1_den_lamp2_bulb1:
        state: "on"
        xy_color:
          - 0.6915
          - 0.3083
        brightness: 64
      light.bf1den_cf1_bulb1:
        state: "on"
        xy_color:
          - 0.6915
          - 0.3083
        brightness: 64
      light.bf1_den_cf2_bulb1:
        state: "off"
      light.bf1_den_lamp1_bulb1:
        state: "off"
      light.bf1_den_lamp3_bulb_1:
        state: "off"
      light.bf1_den_lamp3_bulb_2:
        state: "off"
      light.bf1_hallway_cf1_bulb_1:
        state: "off"
      light.bf1_hallway_cf1_bulb_2:
        state: "off"
      light.bf1_hallway_cf1_bulb_3:
        state: "off"
      light.bf1_kitchen_cf1_bulb1:
        state: "off"
      light.bf1_stairwell_cf1_bulb1:
        state: "off"
      light.bf1_storage1_cf1_bulb1:
        state: "off"
      light.bf1_storage1_cf2_bulb1:
        state: "off"
      light.bf1_storage2_lamp1_bulb1:
        state: "off"
      light.bf1_storage2_lamp2_bulb1:
        state: "off"
      light.bf1_storage2_lamp3_bulb1:
        state: "off"

  - id: "d8c9b5de-8ed7-4403-87ee-172feb15d9a5"
    name: "[Light] BF1: All - Migraine"
    entities:
      light.bf1_den_lamp2_bulb1:
        state: "on"
        xy_color:
          - 0.23
          - 0.698
        brightness: 64
      light.bf1_den_cf1_bulb1:
        state: "on"
        xy_color:
          - 0.23
          - 0.698
        brightness: 64
      light.bf1_den_cf2_bulb1:
        state: "off"
      light.bf1_den_lamp1_bulb1:
        state: "off"
      light.bf1_den_lamp3_bulb_1:
        state: "off"
      light.bf1_den_lamp3_bulb_2:
        state: "off"
      light.bf1_hallway_cf1_bulb_1:
        state: "off"
      light.bf1_hallway_cf1_bulb_2:
        state: "off"
      light.bf1_hallway_cf1_bulb_3:
        state: "off"
      light.bf1_kitchen_cf1_bulb1:
        state: "off"
      light.bf1_stairwell_cf1_bulb1:
        state: "off"
      light.bf1_storage1_cf1_bulb1:
        state: "off"
      light.bf1_storage1_cf2_bulb1:
        state: "off"
      light.bf1_storage2_lamp1_bulb1:
        state: "off"
      light.bf1_storage2_lamp2_bulb1:
        state: "off"
      light.bf1_storage2_lamp3_bulb1:
        state: "off"

  - id: "10fd713e-b10b-4e3d-833b-3ea63816b5de"
    name: "[Light] BF1: All - Bright"
    entities:
      light.bf1_all:
        state: "on"
        color_temp: 367
        brightness: 255

  - id: "22b7c3af-0991-4f83-b2b2-6d51f1df089c"
    name: "[Light] BF1: All - Concentrate"
    entities:
      light.bf1_all:
        state: "on"
        color_temp: 230
        brightness: 255

  - id: "9e5f60ca-caae-41b3-bd7b-7fce33bcc436"
    name: "[Light] BF1: All - Dimmed"
    entities:
      light.bf1_all:
        state: "on"
        color_temp: 369
        brightness: 76

  - id: "126a563d-3826-4d00-81e1-abca1a6869b2"
    name: "[Light] BF1: All - Energize"
    entities:
      light.bf1_all:
        state: "on"
        color_temp: 156
        brightness: 255

  - id: "50d190ae-8d62-4716-ac9c-3ef5757a1009"
    name: "[Light] BF1: All - Nightlight"
    entities:
      light.bf1_all:
        state: "on"
        color_temp: 454
        brightness: 1

  - id: "3e72d0b5-c2f2-4f4e-87df-67bc7c63882d"
    name: "[Light] BF1: All - Read"
    entities:
      light.bf1_all:
        state: "on"
        color_temp: 343
        brightness: 255

  - id: "fbe2e3db-c839-42d6-86de-c879baf8673e"
    name: "[Light] BF1: All - Relax"
    entities:
      light.bf1_all:
        state: "on"
        color_temp: 447
        brightness: 145

  - id: "b448b6d9-fc73-4f87-8cd9-f0df64dd350d"
    name: "[Light] BF1: All - Off"
    entities:
      light.bf1_all:
        state: "off"

  - id: "f8c94b9d-ab8b-4c1e-8b75-51b2b59e4102"
    name: "[Light] BF: All - Bright"
    entities:
      light.bf_all:
        state: "on"
        color_temp: 367
        brightness: 255

  - id: "e57eee01-207c-4017-9cd4-496fbc8f4ac1"
    name: "[Light] BF: All - Concentrate"
    entities:
      light.bf_all:
        state: "on"
        color_temp: 230
        brightness: 255

  - id: "7e61a7e6-b675-415c-a18b-e5d4cd273e28"
    name: "[Light] BF: All - Dimmed"
    entities:
      light.bf_all:
        state: "on"
        color_temp: 369
        brightness: 76

  - id: "be46d867-6b91-4022-9d04-5ebc660594e6"
    name: "[Light] BF: All - Energize"
    entities:
      light.bf_all:
        state: "on"
        color_temp: 156
        brightness: 255

  - id: "4261918a-3873-4fc7-8b44-fe170d3b977b"
    name: "[Light] BF: All - Nightlight"
    entities:
      light.bf_all:
        state: "on"
        color_temp: 454
        brightness: 1

  - id: "e4a5152c-f811-462e-b870-6a38d4e009f1"
    name: "[Light] BF: All - Read"
    entities:
      light.bf_all:
        state: "on"
        color_temp: 343
        brightness: 255

  - id: "02404dae-8c2a-43a3-b9b7-c9eea54554ca"
    name: "[Light] BF: All - Relax"
    entities:
      light.bf_all:
        state: "on"
        color_temp: 447
        brightness: 145

  - id: "5e623fd7-f173-469f-9f8c-29bfefa486ec"
    name: "[Light] BF: All - Off"
    entities:
      light.bf_all:
        state: "off"
