# ==================================================================================================
#
# Basement Floor: Hallway
#
# ==================================================================================================
adaptive_lighting:
  - name: "BF1: Hallway"
    lights:
      - light.bf1_hallway
    initial_transition: 1
    min_color_temp: 2200
    max_color_temp: 6500

# ==================================================================================================
#
# Automations
#
# ==================================================================================================
automation:
  - id: "416078c3-1f3a-4742-9974-205c1f2fe0ceu"
    alias: "[Light] BF1: Hallway - Adaptive Lighting (Toggle Brightness Adjustment)"
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        to: "Circadian"
      - platform: state
        entity_id: binary_sensor.light_bf1_hallway_autobrightness
    variables:
      brightness_mode: "{{ states('binary_sensor.light_basement_autobrightness') }}"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
    action:
      - service: "switch.turn_{{ brightness_mode }}"
        data:
          entity_id:
            - switch.adaptive_lighting_adapt_brightness_bf1_hallway
    mode: single

  - id: "25c326c4-7137-4899-8796-186d0fd42682"
    alias: "[Light] BF1: Hallway - Adaptive Lighting (Turn Off Brightness Adjustment)"
    initial_state: false
    description: ""
    trigger:
        - platform: event
          event_type: hue_event
          event_data:
            id: bf1_great_room_switch_button
            subtype: 3
        - platform: event
          event_type: hue_event
          event_data:
            id: bf1_great_room_switch_button
            subtype: 2
    condition: []
    action:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.adaptive_lighting_adapt_brightness_bf1_hallway
    mode: single

  # Temporarily disable until I can figure out how to reverse the variable definition.
  # IE, when states('binary_sensor.light_basement_color_mode') is off, the variable should be 'on'
  # - id: "4c6e9101-a48b-480f-bd66-ad4b5fe13ac2"
  #   alias: "[Light] Basement: Adaptive Lighting (Toggle)"
  #   initial_state: false
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.light_basement_color_mode
  #   variables:
  #     brightness_mode: "{{ states('binary_sensor.light_basement_autobrightness') }}"
  #   condition:
  #     condition: and
  #     conditions:
  #       - condition: template
  #         value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
  #   action:
  #     - service: "switch.turn_{{ brightness_mode }}"
  #       data:
  #         entity_id:
  #           - switch.adaptive_lighting_adapt_brightness_basement
  #   mode: single


  # ================================================================================================
  #
  # 
  #
  # This doesn't actually work.
  #
  # The goal is to disable adaptive lighting, if button 1 on a hue dimmer switch is pressed more
  # than 1 time within 10 seconds.
  #
  # I will also need to re-enable adaptive lighting if I so choose.  (Prior to the daily reset at
  # 4 am.)
  #
  # ================================================================================================
  # - id: "b7592a97-117b-406b-9cc1-0c0747536190"
  #   alias: "[Light] Basement: Turn Off Adaptive Lighting"
  #   description: ""
  #   trigger:
  #       - platform: event
  #         event_type: hue_event
  #         event_data:
  #           id: bf1_great_room_switch_button
  #           subtype: 1
  #           type: short_release
  #   condition:
  #     - condition: template
  #       value_template: >-
  #         "{{ ((now().timestamp() - as_timestamp(state_attr('automation.test', 'last_triggered'))) < 10 ) }}"
  #   action:
  #     - service: switch.turn_off
  #       data: {}
  #       target:
  #         entity_id: switch.adaptive_lighting_basement
  #   mode: single

# ==================================================================================================
#
# Rest Commands
#
# ==================================================================================================
rest_command:
  light_update_bf1_hallway_scene:
    url: "https://hue2.iot.home/clip/v2/resource/scene/{{ scene_id }}"
    method: put
    headers:
      hue-application-key: "{{ username }}"
    payload: '{
          "id":"{{ scene_id }}",
          "actions":[
          {
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid": "557f80c4-02a7-4944-8591-53eb8c33cb95","rtype":"light"}
          },
          {
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid": "ae1340a6-0178-4eb5-8b4a-c166abd7a297","rtype":"light"}
          }
          ]
          }'
    verify_ssl: false
    content_type: "application/json"

# ==================================================================================================
#
# Scenes
#
# ==================================================================================================
scene:
  - id: "e893eca7-3305-4ddd-8cef-8d698c022082"
    name: "[Light] BF1: Hallway - Enable Automations"
    entities:
      automation.light_bf1_hallway_adaptive_lighting_toggle_brightness_adjustment:
        state: "on"
      automation.light_bf1_hallway_adaptive_lighting_turn_off_brightness_adjustment:
        state: "on"

  - id: "5c92577b-ab66-4192-a23e-23a12164dcb8"
    name: "[Light] BF1: Hallway - Bright"
    entities:
      light.bf1_hallway:
        state: "on"
        color_temp: 367
        brightness: 255

  - id: "64f013d5-3abf-44ef-a802-c20ad5e9214b"
    name: "[Light] BF1: Hallway - Concentrate"
    entities:
      light.bf1_hallway:
        state: "on"
        color_temp: 230
        brightness: 255

  - id: "04418671-9d32-4668-9b19-67ac3f9aa199"
    name: "[Light] BF1: Hallway - Dimmed"
    entities:
      light.bf1_hallway:
        state: "on"
        color_temp: 369
        brightness: 76

  - id: "cc7765a6-d698-4d13-9751-fab21ec6c4c9"
    name: "[Light] BF1: Hallway - Energize"
    entities:
      light.bf1_hallway:
        state: "on"
        color_temp: 156
        brightness: 255

  - id: "452cc28b-b56a-4e43-b7c7-a4383913a11e"
    name: "[Light] BF1: Hallway - Nightlight"
    entities:
      light.bf1_hallway:
        state: "on"
        color_temp: 454
        brightness: 1

  - id: "e9053d2b-ce86-4385-8e05-36391973f3ff"
    name: "[Light] BF1: Hallway - Read"
    entities:
      light.bf1_hallway:
        state: "on"
        color_temp: 343
        brightness: 255

  - id: "e3870fe7-1366-4ac8-acbe-4161eaa64260"
    name: "[Light] BF1: Hallway - Relax"
    entities:
      light.bf1_hallway:
        state: "on"
        color_temp: 447
        brightness: 145

  - id: "a58ea71d-b262-40fb-9aef-b116272fa81c"
    name: "[Light] BF1: Hallway - Off"
    entities:
      light.bf1_hallway:
        state: "off"

# ==================================================================================================
#
# Templates
#
# Need to eventually convert these into the new 'template:' style.  This currently doesn't seem
# to work inside packages.
#
# https://www.home-assistant.io/integrations/template/
#
# ==================================================================================================
template:
  - binary_sensor:
      - unique_id: "555f45d7-a9da-4df6-9578-804c1aba5415"
        name: "[Light] BF1: Hallway Autobrightness"
        state: >-
          {{ (
               states("sensor.global_dummy_light_brightness") | int(100) ) <
               ( state_attr("binary_sensor.light_bf1_hallway_autobrightness", "brightness_max")
               | int(104) )
             and ( states("sensor.global_dummy_light_brightness") | int(100) ) >
             ( state_attr("binary_sensor.light_bf1_hallway_autobrightness", "brightness_min") | int(100)
             ) }}
        attributes:
          brightness: >-
            {% if state_attr("light.bf1_hallway", "brightness") == None or
               is_state_attr("light.bf1_hallway", "brightness", "unknown") or
               is_state("light.bf1_hallway", "off") %}
              {{ ( states("sensor.global_dummy_light_brightness") | int(100) ) }}
            {% else %}
              {{ ( state_attr("light.bf1_hallway","brightness") / 254 * 100 ) | int(100) }}
            {% endif %}
          brightness_max: >-
            {{ state_attr("binary_sensor.light_bf1_hallway_autobrightness", "brightness") | int(100) + 4 }}
          brightness_min: >-
            {{ state_attr("binary_sensor.light_bf1_hallway_autobrightness", "brightness") | int(100) - 4 }}

      - unique_id: "77e8421d-25eb-413e-905f-8887b4d91e77"
        name: "[Light] BF1: Hallway Color Mode"
        state: "{{ state_attr('light.bf1_hallway','color_mode') == 'xy' }}"

  - sensor:
      - unique_id: "cdc049d4-981e-472f-abcd-f279960ff70c"
        name: "[Light] BF1: Hallway Color"
        state: "{{ state_attr('light.bf1_hallway', 'xy_color') }}"
