# ==================================================================================================
#
# Basement Floor: Hallway
#
# ==================================================================================================
adaptive_lighting:
  - name: "BF1: Kitchen"
    lights:
      - light.bf1_kitchen
    initial_transition: 1
    min_color_temp: 2200
    max_color_temp: 6500


# ==================================================================================================
#
# Automations
#
# ==================================================================================================
automation:
  - id: "fa732465-ad55-45a0-8880-6fea977a47f9"
    alias: "BF1: Kitchen - Adaptive Lighting (Toggle Brightness Adjustment)"
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        to: "Circadian"
      - platform: state
        entity_id: binary_sensor.bf1_kitchen_autobrightness
        not_from:
          - "unknown"
          - "unavailable"
        not_to:
          - "unknown"
          - "unavailable"
    variables:
      brightness_mode: "{{ states('binary_sensor.light_bf1_kitchen_autobrightness') }}"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
    action:
      - service: "switch.turn_{{ brightness_mode }}"
        data:
          entity_id:
            - switch.bf1_kitchen_adaptive_lighting_brightness
    mode: single

  - id: "37bbc65c-5a6c-48cd-9aa5-cc6b087340e9"
    alias: "BF1: Kitchen - Adaptive Lighting (Turn Off Brightness Adjustment)"
    description: ""
    trigger:
        - platform: event
          event_type: hue_event
          event_data:
            id: bf1_great_room_switch_button
            subtype: 3
        - platform: event
          event_type: hue_event
          event_data:
            id: bf1_great_room_switch_button
            subtype: 2
    condition: []
    action:
      - service: switch.turn_off
        data: {}
        target:
          entity_id:
            - switch.bf1_kitchen_adaptive_lighting_brightness
    mode: single

  - id: "1c167f4d-15cb-42cf-ba37-da57ed2e0040"
    alias: "BF1: Kitchen - Adaptive Lighting (Toggle Color Adjustment)"
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        to: "Circadian"
      - platform: state
        entity_id: binary_sensor.bf1_kitchen_autocolor
        not_from:
          - "unknown"
          - "unavailable"
        not_to:
          - "unknown"
          - "unavailable"
    variables:
      brightness_mode: "{{ states('binary_sensor.bf1_kitchen_autocolor') }}"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
    action:
      - service: "switch.turn_{{ brightness_mode }}"
        data: {}
        target:
          entity_id:
            - switch.bf1_kitchen_adaptive_lighting_color
    mode: single

  - id: "9a829acc-1e10-4e55-b9bf-dece5e26bfcc"
    alias: "BF1: Kitchen - Adaptive Lighting (Turn Off Color Adjustment)"
    description: ""
    trigger:
        - platform: event
          event_type: hue_event
          event_data:
            id: bf1_great_room_switch_button
            subtype: 4
            type: "long_release"
    condition: []
    action:
      - service: switch.turn_off
        data: {}
        target:
          entity_id:
            - switch.bf1_kitchen_adaptive_lighting_color
    mode: single

  - id: "0f8d930a-b009-47d8-b784-9f18657fcf6b"
    alias: "BF1: Kitchen - Green Has Been On"
    description: ""
    trigger:
      - platform: state
        entity_id: light.bf1_kitchen
        attribute: xy_color
        to: (0.23, 0.698)
    condition: []
    action:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.bf1_kitchen_green_event
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.special_migraine_mode
    mode: single

  - id: "becf923a-93e0-4dc9-b3e6-318140c00988"
    alias: "BF1: Kitchen - Turn off Green tracker"
    description: ""
    trigger:
      - at: "04:00"
        platform: time
    condition: []
    action:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.bf1_kitchen_green_event
    mode: single

# ==================================================================================================
#
# Input Boolean
#
# ==================================================================================================
input_boolean:
  bf1_kitchen_green_event:
    name: "BF1: Kitchen - Green Event"

# ==================================================================================================
#
# Input Select
#
# ==================================================================================================
input_select:
  bf1_kitchen_scene:
    name: "BF1: Kitchen - Scene"
    options:
      - scene.bf1_kitchen_bright
      - scene.bf1_kitchen_candle
      - scene.bf1_kitchen_concentrate
      - scene.bf1_kitchen_darken
      - scene.bf1_kitchen_dimmed
      - scene.bf1_kitchen_energize
      - scene.bf1_kitchen_fireplace
      - scene.bf1_kitchen_homeassistant
      - scene.bf1_kitchen_migraine
      - scene.bf1_kitchen_nightlight
      - scene.bf1_kitchen_read
      - scene.bf1_kitchen_relax
      - scene.bf1_kitchen_dynamic
    initial: scene.bf1_kitchen_homeassistant

# ==================================================================================================
#
# Template Lights
#
# ==================================================================================================
light:
  - platform: template
    lights:
      bf1_den_alt:
        friendly_name: "BF1: Kitchen (Alt)"
        unique_id: "e756cc56-1f05-4c4a-994b-849d9be9d58d"
        value_template: "{{ is_state('light.bf1_kitchen', 'on') }}"
        level_template: "{{ state_attr('light.bf1_kitchen','brightness') | int(255) }}"
        temperature_template: "{{ state_attr('light.bf1_kitchen','color_temp') | int(367) }}"
        color_template: "{{ state_attr('light.bf1_kitchen','hs_color') }}"
        min_mireds_template: "{{ state_attr('light.bf1_kitchen','min_mireds') | int(100) }}"
        max_mireds_template: "{{ state_attr('light.bf1_kitchen','max_mireds') | int(500) }}"
        #effect_list_template: "{{ state_attr('light.bf1_kitchen_cf1_bulb1', 'effect_list') }}"
        turn_on:
          service: scene.turn_on
          data_template:
            entity_id: >
              {{ states('input_select.bf1_kitchen_scene') }}
        turn_off:
          service: light.turn_off
          target:
            entity_id: light.bf1_kitchen
        set_level:
          service: light.turn_on
          target:
            entity_id: light.bf1_kitchen
          data:
            brightness: "{{ brightness }}"
        set_temperature:
          service: light.turn_on
          target:
            entity_id: light.bf1_kitchen
          data:
            color_temp: "{{ color_temp }}"
        set_color:
          service: light.turn_on
          target:
            entity_id: light.bf1_kitchen
          data:
            hs_color:
              - "{{ hs[0] }}"
              - "{{ hs[1] }}"
        # set_effect:
        #   - service: light.turn_on
        #     data_template:
        #       - light.bf1_kitchen
        #     effect: "{{ effect }}"
        supports_transition_template: "{{ true }}"  

# ==================================================================================================
#
# Rest Command
#
# Light IDs:
# - 01: e687cdcb-7022-4d66-9763-ec5ead8f8808
#   name: BF1 Kitchen CF1 Bulb
#
# ==================================================================================================
rest_command:
  light_update_bf1_kitchen_scene:
    url: "https://hue2.iot.home/clip/v2/resource/scene/{{ scene_id }}"
    method: put
    headers:
      hue-application-key: "{{ username }}"
    payload: '{
          "id":"{{ scene_id }}",
          "actions":[
          {
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"e687cdcb-7022-4d66-9763-ec5ead8f8808","rtype":"light"}
          }
          ]
          }'
    verify_ssl: false
    content_type: "application/json"

# ==================================================================================================
#
# Scenes
#
# ==================================================================================================
#scene:

# ==================================================================================================
#
# Templates
#
# ==================================================================================================
template:
  - binary_sensor:
      - unique_id: "c1c5bcb6-ed31-4482-871b-1f210b2e453e"
        name: "BF1: Kitchen Autobrightness"
        state: >-
          {{ (
               states("sensor.global_dummy_light_brightness") | int(100) ) <
               ( state_attr("binary_sensor.light_bf1_kitchen_autobrightness", "brightness_max")
               | int(104) )
             and ( states("sensor.global_dummy_light_brightness") | int(100) ) >
             ( state_attr("binary_sensor.light_bf1_kitchen_autobrightness", "brightness_min") | int(100)
             ) }}
        attributes:
          brightness: >-
            {% if state_attr("light.bf1_kitchen", "brightness") == None or
               is_state_attr("light.bf1_kitchen", "brightness", "unknown") or
               is_state("light.bf1_kitchen", "off") %}
              {{ ( states("sensor.global_dummy_light_brightness") | int(100) ) }}
            {% else %}
              {{ ( state_attr("light.bf1_kitchen","brightness") / 254 * 100 ) | int(100) }}
            {% endif %}
          brightness_max: >-
            {{ state_attr("binary_sensor.light_bf1_kitchen_autobrightness", "brightness") | int(100) + 4 }}
          brightness_min: >-
            {{ state_attr("binary_sensor.light_bf1_kitchen_autobrightness", "brightness") | int(100) - 4 }}

      - unique_id: "37ed3761-06b4-4094-9276-0f3105561bd1"
        name: "BF1: Kitchen - Autocolor"
        state: >-
          {{ ( states("sensor.global_dummy_light_color_temperature") | int(367) ) <
               ( state_attr("binary_sensor.bf1_kitchen_autocolor", "color_temp_max")
               | int(382) )
             and ( states("sensor.global_dummy_light_color_temperature") | int(367) ) >
               ( state_attr("binary_sensor.bf1_kitchen_autocolor", "color_temp_min")
               | int(352))
             }}
        attributes:
          color_temp: >-
            {% if state_attr("light.bf1_kitchen", "color_temp") is number %}
              {{ state_attr("light.bf1_kitchen","color_temp") | int(367) }}
            {% else %}
              {{ ( states("sensor.global_dummy_light_color_temperature") | int(367) ) }}
            {% endif %}
          color_temp_max: >-
            {{ state_attr("binary_sensor.bf1_kitchen_autocolor", "color_temp") | int(367) + 15 }}
          color_temp_min: >-
            {{ state_attr("binary_sensor.bf1_kitchen_autocolor", "color_temp") | int(367) - 15 }}

      - unique_id: "9e40bf29-e87f-43e3-9368-49c842204d88"
        name: "BF1: Kitchen Color Mode"
        state: "{{ state_attr('light.bf1_kitchen','color_mode') == 'xy' }}"

  - sensor:
      - unique_id: "65f6cd80-55d1-4c56-b4b5-4fc92b6c3354"
        name: "BF1: Kitchen Color"
        state: "{{ state_attr('light.bf1_kitchen', 'xy_color') }}"
