# ==================================================================================================
#
# Basement Floor: Hallway
#
# ==================================================================================================
adaptive_lighting:
  - name: "BF1: Kitchen"
    lights:
      - light.bf1_kitchen
    initial_transition: 1
    min_color_temp: 2200
    max_color_temp: 6500


# ==================================================================================================
#
# Automations
#
# ==================================================================================================
automation:
  - id: "fa732465-ad55-45a0-8880-6fea977a47f9"
    alias: "[Light] BF1: Kitchen - Adaptive Lighting (Toggle Brightness Adjustment)"
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        to: "Circadian"
      - platform: state
        entity_id: binary_sensor.light_bf1_kitchen_autobrightness
    variables:
      brightness_mode: "{{ states('binary_sensor.light_bf1_kitchen_autobrightness') }}"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
    action:
      - service: "switch.turn_{{ brightness_mode }}"
        data:
          entity_id:
            - switch.adaptive_lighting_adapt_brightness_bf1_kitchen
    mode: single

  - id: "37bbc65c-5a6c-48cd-9aa5-cc6b087340e9"
    alias: "[Light] BF1: Kitchen - Adaptive Lighting (Turn Off Brightness Adjustment)"
    description: ""
    trigger:
        - platform: event
          event_type: hue_event
          event_data:
            id: bf1_great_room_switch_button
            subtype: 3
        - platform: event
          event_type: hue_event
          event_data:
            id: bf1_great_room_switch_button
            subtype: 2
    condition: []
    action:
      - service: switch.turn_off
        data: {}
        target:
          entity_id:
            - switch.adaptive_lighting_adapt_brightness_bf1_kitchen
    mode: single

# ==================================================================================================
#
# Input Select
#
# ==================================================================================================
input_select:
  bf1_kitchen_scene:
    name: "BF1: Kitchen - Scene"
    options:
      - scene.bf1_kitchen_bright
      - scene.bf1_kitchen_candle
      - scene.bf1_kitchen_concentrate
      - scene.bf1_kitchen_darken
      - scene.bf1_kitchen_dimmed
      - scene.bf1_kitchen_energize
      - scene.bf1_kitchen_fireplace
      - scene.bf1_kitchen_homeassistant
      - scene.bf1_kitchen_migraine
      - scene.bf1_kitchen_nightlight
      - scene.bf1_kitchen_read
      - scene.bf1_kitchen_relax
      - scene.bf1_kitchen_dynamic
    initial: scene.bf1_kitchen_homeassistant

# ==================================================================================================
#
# Template Lights
#
# ==================================================================================================
light:
  - platform: template
    lights:
      bf1_den_alt:
        friendly_name: "BF1: Kitchen (Alt)"
        unique_id: "e756cc56-1f05-4c4a-994b-849d9be9d58d"
        value_template: "{{ is_state('light.bf1_kitchen', 'on') }}"
        level_template: "{{ state_attr('light.bf1_kitchen','brightness') | int(255) }}"
        temperature_template: "{{ state_attr('light.bf1_kitchen','color_temp') | int(367) }}"
        color_template: "{{ state_attr('light.bf1_kitchen','hs_color') }}"
        min_mireds_template: "{{ state_attr('light.bf1_kitchen','min_mireds') | int(100) }}"
        max_mireds_template: "{{ state_attr('light.bf1_kitchen','max_mireds') | int(500) }}"
        effect_list_template: "{{ state_attr('light.bf1_kitchen', 'effect_list') }}"
        turn_on:
          service: scene.turn_on
          data_template:
            entity_id: >
              {{ states('input_select.bf1_kitchen_scene') }}
        turn_off:
          service: light.turn_off
          target:
            entity_id: light.bf1_kitchen
        set_level:
          service: light.turn_on
          target:
            entity_id: light.bf1_kitchen
          data:
            brightness: "{{ brightness }}"
        set_temperature:
          service: light.turn_on
          target:
            entity_id: light.bf1_kitchen
          data:
            color_temp: "{{ color_temp }}"
        set_color:
          service: light.turn_on
          target:
            entity_id: light.bf1_kitchen
          data:
            hs_color:
              - "{{ hs[0] }}"
              - "{{ hs[1] }}"
        # set_effect:
        #   - service: light.turn_on
        #     data_template:
        #       - light.bf1_kitchen
        #     effect: "{{ effect }}"
        supports_transition_template: "{{ true }}"  

# ==================================================================================================
#
# Rest Command
#
# Light IDs:
# - 01: e687cdcb-7022-4d66-9763-ec5ead8f8808
#   name: BF1 Kitchen CF1 Bulb
#
# ==================================================================================================
rest_command:
  light_update_bf1_kitchen_scene:
    url: "https://hue2.iot.home/clip/v2/resource/scene/{{ scene_id }}"
    method: put
    headers:
      hue-application-key: "{{ username }}"
    payload: '{
          "id":"{{ scene_id }}",
          "actions":[
          {
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"e687cdcb-7022-4d66-9763-ec5ead8f8808","rtype":"light"}
          }
          ]
          }'
    verify_ssl: false
    content_type: "application/json"

# ==================================================================================================
#
# Scenes
#
# ==================================================================================================
scene:
  - id: "afedd813-67a6-4ebf-8449-14e8fdf2d840"
    name: "[Light] BF1: Kitchen - Bright"
    entities:
      light.bf1_kitchen:
        state: "on"
        color_temp: 367
        brightness: 255

  - id: "da69350e-8276-4dda-bf81-f58b10b5f94a"
    name: "[Light] BF1: Kitchen - Concentrate"
    entities:
      light.bf1_kitchen:
        state: "on"
        color_temp: 230
        brightness: 255

  - id: "e6e20c99-54de-43b5-b374-c40a654d970c"
    name: "[Light] BF1: Kitchen - Dimmed"
    entities:
      light.bf1_kitchen:
        state: "on"
        color_temp: 369
        brightness: 76

  - id: "64e9e1be-5998-482f-809b-ff7fe3adbb21"
    name: "[Light] BF1: Kitchen - Energize"
    entities:
      light.bf1_kitchen:
        state: "on"
        color_temp: 156
        brightness: 255

  - id: "9885473f-a4ad-4de5-b912-e723687f2523"
    name: "[Light] BF1: Kitchen - Nightlight"
    entities:
      light.bf1_kitchen:
        state: "on"
        color_temp: 454
        brightness: 1

  - id: "64567801-323e-4a27-b596-469a242a9d5b"
    name: "[Light] BF1: Kitchen - Read"
    entities:
      light.bf1_kitchen:
        state: "on"
        color_temp: 343
        brightness: 255

  - id: "bff3e48f-93c1-4150-baa1-f4e03b28244d"
    name: "[Light] BF1: Kitchen - Relax"
    entities:
      light.bf1_kitchen:
        state: "on"
        color_temp: 447
        brightness: 145

  - id: "bcb11048-50d9-4fd9-ae7b-e4640f00a1dc"
    name: "[Light] BF1: Kitchen - Off"
    entities:
      light.bf1_kitchen:
        state: "off"

# ==================================================================================================
#
# Templates
#
# Need to eventually convert these into the new 'template:' style.  This currently doesn't seem
# to work inside packages.
#
# https://www.home-assistant.io/integrations/template/
#
# ==================================================================================================
template:
  - binary_sensor:
      - unique_id: "c1c5bcb6-ed31-4482-871b-1f210b2e453e"
        name: "[Light] BF1: Kitchen Autobrightness"
        state: >-
          {{ (
               states("sensor.global_dummy_light_brightness") | int(100) ) <
               ( state_attr("binary_sensor.light_bf1_kitchen_autobrightness", "brightness_max")
               | int(104) )
             and ( states("sensor.global_dummy_light_brightness") | int(100) ) >
             ( state_attr("binary_sensor.light_bf1_kitchen_autobrightness", "brightness_min") | int(100)
             ) }}
        attributes:
          brightness: >-
            {% if state_attr("light.bf1_kitchen", "brightness") == None or
               is_state_attr("light.bf1_kitchen", "brightness", "unknown") or
               is_state("light.bf1_kitchen", "off") %}
              {{ ( states("sensor.global_dummy_light_brightness") | int(100) ) }}
            {% else %}
              {{ ( state_attr("light.bf1_kitchen","brightness") / 254 * 100 ) | int(100) }}
            {% endif %}
          brightness_max: >-
            {{ state_attr("binary_sensor.light_bf1_kitchen_autobrightness", "brightness") | int(100) + 4 }}
          brightness_min: >-
            {{ state_attr("binary_sensor.light_bf1_kitchen_autobrightness", "brightness") | int(100) - 4 }}

      - unique_id: "9e40bf29-e87f-43e3-9368-49c842204d88"
        name: "[Light] BF1: Kitchen Color Mode"
        state: "{{ state_attr('light.bf1_kitchen','color_mode') == 'xy' }}"

  - sensor:
      - unique_id: "65f6cd80-55d1-4c56-b4b5-4fc92b6c3354"
        name: "[Light] BF1: Kitchen Color"
        state: "{{ state_attr('light.bf1_kitchen', 'xy_color') }}"
