---
# ==================================================================================================
#
# Adaptive Lighting
#
# ==================================================================================================
adaptive_lighting:
  - name: "BF1: Stairwell"
    lights:
      - light.bf1_stairwell
    initial_transition: 1
    min_color_temp: 2200
    max_color_temp: 6500

# ==================================================================================================
#
# Automations
#
# ==================================================================================================
automation:
  - id: "8aa338d4-6186-4948-9f04-e3ab3867d48d"
    alias: "[Light] BF1: Stairwell - Adaptive Lighting (Toggle Brightness Adjustment)"
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        to: "Circadian"
      - platform: state
        entity_id: binary_sensor.light_bf1_stairwell_autobrightness
    variables:
      brightness_mode: "{{ states('binary_sensor.light_bf1_stairwell_autobrightness') }}"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
    action:
      - service: "switch.turn_{{ brightness_mode }}"
        data:
          entity_id:
            - switch.adaptive_lighting_adapt_brightness_bf1_stairwell
    mode: single

  - id: "b979cb2f-3728-415d-8ef3-4e97511b9bd7"
    alias: "[Light] BF1: Stairwell - Adaptive Lighting (Turn Off Brightness Adjustment)"
    initial_state: false
    description: ""
    trigger:
        - platform: event
          event_type: hue_event
          event_data:
            id: bf1_great_room_switch_button
            subtype: 3
        - platform: event
          event_type: hue_event
          event_data:
            id: bf1_great_room_switch_button
            subtype: 2
    condition: []
    action:
      - service: switch.turn_off
        data: {}
        target:
          entity_id:
            - switch.adaptive_lighting_adapt_brightness_bf1_stairwell
    mode: single

# ==================================================================================================
#
# Rest Command
#
# Light IDs:
# - 02: 068c9cd1-0128-423b-b0f4-e9bc57e0308e
#   name: BF1 Stairwell Bulb
#
# ==================================================================================================
rest_command:
  light_update_bf1_stairwell_scene:
    url: "https://hue2.iot.home/clip/v2/resource/scene/{{ scene_id }}"
    method: put
    headers:
      hue-application-key: "{{ username }}"
    payload: '{
          "id":"{{ scene_id }}",
          "actions":[
          {
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid":"068c9cd1-0128-423b-b0f4-e9bc57e0308e","rtype":"light"}
          }
          ]
          }'
    verify_ssl: false
    content_type: "application/json"

# ==================================================================================================
#
# Scenes
#
# ==================================================================================================
scene:
  - id: "89a9d18b-7d93-4775-91e9-12d82e1081bd"
    name: "[Light] BF1: Stairwell - Bright"
    entities:
      light.bf1_stairwell:
        state: "on"
        color_temp: 367
        brightness: 255

  - id: "2ae8e6e7-dcf5-4c5d-873d-731eb60fdd8e"
    name: "[Light] BF1: Stairwell - Concentrate"
    entities:
      light.bf1_stairwell:
        state: "on"
        color_temp: 230
        brightness: 255

  - id: "f4534e1d-2a43-4cb7-8bca-e5e4dce82178"
    name: "[Light] BF1: Stairwell - Dimmed"
    entities:
      light.bf1_stairwell:
        state: "on"
        color_temp: 369
        brightness: 76

  - id: "3d939f27-43af-44e2-b18c-55cbd91a19d6U"
    name: "[Light] BF1: Stairwell - Energize"
    entities:
      light.bf1_stairwell:
        state: "on"
        color_temp: 156
        brightness: 255

  - id: "d82be773-00d1-4ad7-a1c5-9e784165a0fe"
    name: "[Light] BF1: Stairwell - Nightlight"
    entities:
      light.bf1_stairwell:
        state: "on"
        color_temp: 454
        brightness: 1

  - id: "8344f689-e28f-4869-b405-a53ec7158c7a"
    name: "[Light] BF1: Stairwell - Read"
    entities:
      light.bf1_stairwell:
        state: "on"
        color_temp: 343
        brightness: 255

  - id: "5a9f8883-c6b8-472a-9a74-5b81a7204dd5"
    name: "[Light] BF1: Stairwell - Relax"
    entities:
      light.bf1_stairwell:
        state: "on"
        color_temp: 447
        brightness: 145

  - id: "d701d267-2dcd-49ba-a2e9-b5d18f61ed81"
    name: "[Light] BF1: Stairwell - Off"
    entities:
      light.bf1_stairwell:
        state: "off"

# ==================================================================================================
#
# Templates
#
# Need to eventually convert these into the new 'template:' style.  This currently doesn't seem
# to work inside packages.
#
# https://www.home-assistant.io/integrations/template/
#
# ==================================================================================================
template:
  - binary_sensor:
      - unique_id: "5f8e0a31-8253-4f68-a1b0-669c858e41d0"
        name: "[Light] BF1: Stairwell Autobrightness"
        state: >-
          {{ (
               states("sensor.global_dummy_light_brightness") | int(100) ) <
               ( state_attr("binary_sensor.light_bf1_stairwell_autobrightness", "brightness_max")
               | int(104) )
             and ( states("sensor.global_dummy_light_brightness") | int(100) ) >
             ( state_attr("binary_sensor.light_bf1_stairwell_autobrightness", "brightness_min") | int(100)
             ) }}
        attributes:
          brightness: >-
            {% if state_attr("light.bf1_stairwell", "brightness") == None or
               is_state_attr("light.bf1_stairwell", "brightness", "unknown") or
               is_state("light.bf1_stairwell", "off") %}
              {{ ( states("sensor.global_dummy_light_brightness") | int(100) ) }}
            {% else %}
              {{ ( state_attr("light.bf1_stairwell","brightness") / 254 * 100 ) | int(100) }}
            {% endif %}
          brightness_max: >-
            {{ state_attr("binary_sensor.light_bf1_stairwell_autobrightness", "brightness") | int(100) + 4 }}
          brightness_min: >-
            {{ state_attr("binary_sensor.light_bf1_stairwell_autobrightness", "brightness") | int(100) - 4 }}

      - unique_id: "83efc366-95c0-4043-824b-981877bd16c7"
        name: "[Light] BF1: Stairwell Color Mode"
        state: "{{ state_attr('light.bf1_stairwell','color_mode') == 'xy' }}"

  - sensor:
      - unique_id: "7c4d59da-df7b-4de7-8531-5f30d81d3cfb"
        name: "[Light] BF1: Stairwell Color"
        state: "{{ state_attr('light.bf1_stairwell', 'xy_color') }}"
