---
# ==================================================================================================
#
# Basement Floor: Storage1
#
# ==================================================================================================
adaptive_lighting:
  - name: "BF1: Storage1"
    lights:
      - light.bf1_storage1
    #prefer_rgb_color: false
    initial_transition: 1
    #sleep_transition: 1
    #transition: 45
    #interval: 90
    #min_brightness: 1
    #max_brightness: 100
    min_color_temp: 2200
    max_color_temp: 6500
    #sleep_brightness: 1
    #sleep_rgb_or_color_temp: "color_temp"
    #sleep_rgb_color:
    #  - 255
    #  - 56
    #  - 0
    #sleep_color_temp: 1000
    #sunrise_time: None
    #max_sunrise_time: None
    #sunrise_offset: 0
    #sunset_time: None
    #min_sunset_time: None
    #sunset_offset: 0
    #only_once: False
    #take_over_control: True
    #detect_non_ha_changes: False
    adapt_delay: 10

# ==================================================================================================
#
# Automations
#
# ==================================================================================================
automation:
  - id: "a627f708-2baf-43a5-b771-b4f2f1701105"
    alias: "BF1: Storage1 - Adaptive Lighting (Toggle Brightness Adjustment)"
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        to: "Circadian"
      - platform: state
        entity_id: binary_sensor.light_bf1_storage1_autobrightness
        not_from:
          - "unknown"
          - "unavailable"
        not_to:
          - "unknown"
          - "unavailable"
    variables:
      brightness_mode: "{{ states('binary_sensor.light_bf1_storage1_autobrightness') }}"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
    action:
      - service: "switch.turn_{{ brightness_mode }}"
        data:
          entity_id:
            - switch.bf1_storage1_adaptive_lighting_brightness
    mode: single

  - id: "61192490-3ad9-4b16-bdcf-5f2cc2615afd"
    alias: "BF1: Storage1 - Adaptive Lighting (Turn Off Brightness Adjustment)"
    description: ""
    trigger:
        - platform: event
          event_type: hue_event
          event_data:
            id: bf1_great_room_switch_button
            subtype: 3
        - platform: event
          event_type: hue_event
          event_data:
            id: bf1_great_room_switch_button
            subtype: 2
    condition: []
    action:
      - service: switch.turn_off
        data: {}
        target:
          entity_id:
            - switch.bf1_storage1_adaptive_lighting_brightness
    mode: single

  - id: "a2ddf847-00cb-4ba6-9cbd-93bb26f0c526"
    alias: "BF1: Storage1 - Adaptive Lighting (Toggle Color Adjustment)"
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        to: "Circadian"
      - platform: state
        entity_id: binary_sensor.bf1_storage1_autocolor
        not_from:
          - "unknown"
          - "unavailable"
        not_to:
          - "unknown"
          - "unavailable"
    variables:
      brightness_mode: "{{ states('binary_sensor.bf1_storage1_autocolor') }}"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
    action:
      - service: "switch.turn_{{ brightness_mode }}"
        data: {}
        target:
          entity_id:
            - switch.bf1_storage1_adaptive_lighting_color
    mode: single

  - id: "5c704d09-d7ae-4dc7-b6fb-560affb222f0"
    alias: "BF1: Storage1 - Adaptive Lighting (Turn Off Color Adjustment)"
    description: ""
    trigger:
        - platform: event
          event_type: hue_event
          event_data:
            id: bf1_great_room_switch_button
            subtype: 4
            type: "long_release"
    condition: []
    action:
      - service: switch.turn_off
        data: {}
        target:
          entity_id:
            - switch.bf1_storage1_adaptive_lighting_color
    mode: single

  - id: "d8d30910-2195-409c-a068-d87ba2b48596"
    alias: "BF1: Storage1 - Green Has Been On"
    description: ""
    trigger:
      - platform: state
        entity_id: light.bf1_storage1
        attribute: xy_color
        to: (0.23, 0.698)
    condition: []
    action:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.bf1_storage1_green_event
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.special_migraine_mode
    mode: single

  - id: "bf2c0436-0a93-4f19-91cf-b3d5ae71d10b"
    alias: "BF1: Storage1 - Turn off Green tracker"
    description: ""
    trigger:
      - at: "04:00"
        platform: time
    condition: []
    action:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.bf1_storage1_green_event
    mode: single

# ==================================================================================================
#
# Input Boolean
#
# ==================================================================================================
input_boolean:
  bf1_storage1_green_event:
    name: "BF1: Storage1 - Green Event"

# ==================================================================================================
#
# Input Text
#
# ==================================================================================================
input_text:
  bf1_storage1_cf1_bulb1:
    name: "BF1: Storage1 CF1 Bulb1"
    min: 36
    max: 36
  bf1_storage1_cf2_bulb1:
    name: "BF1: Storage1 CF2 Bulb1"
    min: 36
    max: 36

  bf1_storage1_scene_homeassistant:
    name: "BF1: Storage1 Scene HomeAssistant"
    min: 36
    max: 36

# ==================================================================================================
#
# Scenes
#
# ==================================================================================================
#scene:

# ==================================================================================================
#
# Templates
#
# Need to eventually convert these into the new 'template:' style.  This currently doesn't seem
# to work inside packages.
#
# https://www.home-assistant.io/integrations/template/
#
# ==================================================================================================
template:
  - binary_sensor:
      - unique_id: "0f4ece11-2159-460a-a814-964f1894bd16"
        name: "BF1: Storage1 Autobrightness"
        state: >-
          {{ (
               states("sensor.global_dummy_light_brightness") | int(100) ) <
               ( state_attr("binary_sensor.light_bf1_storage1_autobrightness", "brightness_max")
               | int(104) )
             and ( states("sensor.global_dummy_light_brightness") | int(100) ) >
             ( state_attr("binary_sensor.light_bf1_storage1_autobrightness", "brightness_min") | int(100)
             ) }}
        attributes:
          brightness: >-
            {% if state_attr("light.bf1_storage1", "brightness") == None or
               is_state_attr("light.bf1_storage1", "brightness", "unknown") or
               is_state("light.bf1_storage1", "off") %}
              {{ ( states("sensor.global_dummy_light_brightness") | int(100) ) }}
            {% else %}
              {{ ( state_attr("light.bf1_storage1","brightness") / 254 * 100 ) | int(100) }}
            {% endif %}
          brightness_max: >-
            {{ state_attr("binary_sensor.light_bf1_storage1_autobrightness", "brightness") | int(100) + 4 }}
          brightness_min: >-
            {{ state_attr("binary_sensor.light_bf1_storage1_autobrightness", "brightness") | int(100) - 4 }}

      - unique_id: "9cacc9b6-4bd6-4578-aa7a-6454268e9653"
        name: "BF1: Storage1 - Autocolor"
        state: >-
          {{ ( states("sensor.global_dummy_light_color_temperature") | int(367) ) <
               ( state_attr("binary_sensor.bf1_storage1_autocolor", "color_temp_max")
               | int(382) )
             and ( states("sensor.global_dummy_light_color_temperature") | int(367) ) >
               ( state_attr("binary_sensor.bf1_storage1_autocolor", "color_temp_min")
               | int(352))
             }}
        attributes:
          color_temp: >-
            {% if state_attr("light.bf1_storage1", "color_temp") is number %}
              {{ state_attr("light.bf1_storage1","color_temp") | int(367) }}
            {% else %}
              {{ ( states("sensor.global_dummy_light_color_temperature") | int(367) ) }}
            {% endif %}
          color_temp_max: >-
            {{ state_attr("binary_sensor.bf1_storage1_autocolor", "color_temp") | int(367) + 15 }}
          color_temp_min: >-
            {{ state_attr("binary_sensor.bf1_storage1_autocolor", "color_temp") | int(367) - 15 }}

      - unique_id: "a6010d67-12b3-4c8f-99c5-ba5977ed0854"
        name: "BF1: Storage1 Color Mode"
        state: "{{ state_attr('light.bf1_storage1','color_mode') == 'xy' }}"

  - sensor:
      - unique_id: "a042ecbe-48a2-4d4c-b0e7-0abb048a8468"
        name: "BF1: Storage1 Color"
        state: "{{ state_attr('light.bf1_storage1', 'xy_color') }}"

...
