# ==================================================================================================
#
# common settings
#
# ==================================================================================================
homeassistant:

# ==================================================================================================
#
# Input select
#
# ==================================================================================================
input_select:
  light_mode:
    name: "Light Mode"
    options:
      - "Circadian"
      - "Darken House"
      - "Migraine"
      - "Sleeping (Migraine)"
      - "Night Out"
      - "Guests"
      - "Other"
    #initial: "Circadian"
    #icon: "mdi:light"

# ==================================================================================================
#
# Light Groups
#
# ==================================================================================================
light:
  - platform: group
    name: All lights
    entities:
      - light.basement
      - light.main_floor

