# ==================================================================================================
#
# common settings
#
# ==================================================================================================
automation:
  - id: "65d7e60e-4e39-460b-a319-b65f497b6465"
    alias: "[Light] Enable Lighting Automations"
    description: ""
    trigger:
      - event: start
        platform: homeassistant
    condition: []
    action:
      - scene: scene.light_enable_basement_automations
      - scene: scene.light_enable_common_automations
      - scene: scene.light_enable_master_bedroom_automations

  - id: "a3ed2024-e1a9-4ac8-8dca-80cc62812fcf"
    alias: "[Light] Adaptive Lighting (Toggle)"
    description: ''
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        to: Circadian
      - platform: state
        entity_id: input_select.light_mode
        from: Circadian
    variables:
      circadian_mode: "{{ states('binary_sensor.circadian_mode') }}"
    condition: []
    action:
      - service: "switch.turn_{{ circadian_mode }}"
        data:
          entity_id:
            - switch.adaptive_lighting_basement
            #- switch.adaptive_lighting_den_couch_lamp_2
            #- switch.adaptive_lighting_mf_bedroom_1_lamp_2

  # ================================================================================================
  #
  # Set Lighting Mode: Circadian
  #
  # Trigger:
  # - In the morning when the sun rises to 18 degrees below the horizon
  #   enable
  #
  # Actions:
  #
  # ================================================================================================
  - id: "087bce7b-c92f-4c05-a3ba-22949cb79e61"
    alias: "[Light] Set Light Mode: Circadian"
    description: ""
    initial_state: false
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        above: -18
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.light_mode
          option: "Circadian"

  # ================================================================================================
  #
  # Set Lighting Mode: Darken House
  #
  # Trigger:
  # - When the timer that begins the nighttime routine finishes
  #
  # Actions:
  #
  # ================================================================================================
  - id: "ed400d67-ffec-489a-9d90-1a589baa6910"
    alias: "[Light] Set Light Mode: Darken House"
    description: ""
    initial_state: false
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.lights_off
    condition: []
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.light_mode
          option: "Darken House"

  # ================================================================================================
  #
  # Set Lighting Mode: Migraine
  #
  # Trigger:
  # - Input Boolean: Special Migraine Mode is set to true
  #
  # Actions:
  # - 
  # ================================================================================================
  - id: "1b4dd01f-acb1-4462-b14a-7d818f12787b"
    alias: "[Light] Set Light Mode: Migraine"
    description: ""
    initial_state: false
    trigger:
      platform: state
      entity_id: input_boolean.special_migraine_mode
      to: "on"
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.light_mode
          option: "Migraine"

  - id: "387e7772-a2c3-4d29-b524-8aa36fbc65b2"
    alias: "[Light] Enable Migraine Mode"
    description: ""
    initial_state: false
    trigger:
      - entity_id: sensor.light_mf_den_couch_lamp_2_color
        platform: state
        to: (0.17, 0.7)
      - entity_id: sensor.light_basement_color
        platform: state
        to: (0.17, 0.7)
      - entity_id: sensor.light_mf_bedroom_1_lamp_2_color
        platform: state
        to: (0.17, 0.7)
    condition: []
    action:
      - entity_id: input_boolean.special_migraine_mode
        service: input_boolean.turn_on

  # ================================================================================================
  #
  # Set Lighting Mode: Guests
  #
  # Trigger:
  # - Input Boolean: Special Guest Mode is set to true
  #
  # Actions:
  # -
  #
  # ================================================================================================
  - id: "049e19ec-4370-427d-a080-8fece7a2ca6d"
    alias: "[Light] Set Light Mode: Guests"
    description: ""
    initial_state: false
    trigger:
    - platform: state
      entity_id: input_boolean.special_guest_present
      from: "off"
      to: "on"
    condition: []
    action:
      data:
        entity_id: input_select.light_mode
        option: "Guests"
      service: input_select.select_option

  # ================================================================================================
  #
  # Update HomeAssistant Scene on Hue Bridge
  #
  # Runs every 5 minutes while light mode is "circadian"
  #
  # ================================================================================================
  # - id: "b9267e40-af1c-4f92-bb98-e6839787cc97"
  #   alias: "[Light] Update HomeAssistant on Hue Bridge"
  #   description: ""
  #   trigger:
  #     - platform: time_pattern
  #       minutes: "/5"
  #   condition:
  #     condition: and
  #     conditions:
  #       - condition: template
  #         value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
  #   action:
  #     - service: script.turn_on
  #       data: 

# ==================================================================================================
#
# Input Boolean
#
# ==================================================================================================
input_boolean:
  special_migraine_mode:
    name: Migraine Mode
    initial: off
    icon: mdi:hospital-box
  special_guest_present:
    name: Guests are present
    initial: off
    icon: mdi:human

# ==================================================================================================
#
# Input select
#
# ==================================================================================================
input_select:
  light_mode:
    name: "Light Mode"
    options:
      - "Circadian"
      - "Darken House"
      - "Migraine"
      - "Sleeping (Migraine)"
      - "Night Out"
      - "Guests"
      - "Other"

# ==================================================================================================
#
# Light Groups
#
# ==================================================================================================
light:
  - platform: group
    name: "All lights"
    entities:
      - light.basement
      - light.main_floor

# ==================================================================================================
#
# Scenes
#
# ==================================================================================================
scene:
  - id: "e697c216-b8c7-4825-9f40-4fd01d220d40"
    name: "[Light] Enable Common Automations"
    entities:
      automation.light_set_light_mode_circadian:
        state: 'on'
      automation.light_set_light_mode_guests:
        state: 'on'
      automation.light_set_light_mode_migraine:
        state: 'on'
      automation.light_set_light_mode_darken_house:
        state: 'on'
      automation.light_enable_migraine_mode:
        state: 'on'
      automation.light_adaptive_lighting_toggle:
        state: 'on'

script:
  light_update_scene_homeassistant_circadian:
    alias: "[Light] Update Home Assistant Scenes (Circadian)"
    sequence:
      - service: rest_command.light_update_basement_scene_homeassistant
        data:
          scene_id: "2432a16d-f38e-44d0-8e9a-dfd9fc8c52ab"
          username: !secret hue2_username
          color: '"ct": {{ state_attr("switch.adaptive_lighting_basement", "color_temp_mired") | int }}'
          brightness: '"bri": {{ state_attr("switch.adaptive_lighting_basement", "brightness_pct") | int }}'
          bulb_01_on_state: "true"
          bulb_02_on_state: "true"
          bulb_03_on_state: "true"
          bulb_04_on_state: "true"
          bulb_05_on_state: "true"
          bulb_06_on_state: "true"
          bulb_07_on_state: "true"
          bulb_08_on_state: "true"
          bulb_09_on_state: "true"
          bulb_10_on_state: "true"
          bulb_11_on_state: "true"
          bulb_12_on_state: "true"

template:
  - binary_sensor:
      - unique_id: "4fd1dd66-c51b-474d-9de7-da4dfd5cc398"
        name: "Circadian Mode"
        state: "{{ states('input_select.light_mode') == 'Circadian' }}"
