# ==================================================================================================
#
# Master Bedroom Light Configuration
#
# Lights:
#   light.main_lamp_1: Master Bedroom Lamp 1 Lightbulb 1
#   light.main_lamp_2: Master Bedroom Lamp 2 Lightbulb 1
#   light.main_lamp_4: Master Bedroom Ceiling Lightbulb 2
#   light.main_lamp_14: Master Bedroom Lamp 1 Lightbulb 2
#   light.main_lamp_15: Master Bedroom Lamp 2 Lightbulb 2
#   light.main_lamp_16: Master Bedroom Ceiling Lightbulb 1
#
# Light Groups:
#   - light.den_couch_lamp_1
#   - light.den_couch_lamp_2
#   - light.den_ceiling
#   - light.den_fireplace
#   - light.den_tower_lamp
#   - light.den_table_lamp
#
# ==================================================================================================
adaptive_lighting:
  - name: "MF: Master Bedroom Lamp 1"
    lights:
      - light.mf_bedroom_1_lamp_1
    initial_transition: 1
    min_color_temp: 2200
    max_color_temp: 6500
  - name: "MF: Master Bedroom Lamp 2"
    lights:
      - light.mf_bedroom_1_lamp_2
    initial_transition: 1
    min_color_temp: 2200
    max_color_temp: 6500
  - name: "MF: Master Bedroom Ceiling"
    lights:
      - light.mf_bedroom_1_ceiling
    initial_transition: 1
    min_color_temp: 2200
    max_color_temp: 6500

# ==================================================================================================
#
# Automations
#
#
#
# ==================================================================================================
automation:
  - id: "848efd5b-0d62-496b-8da2-ff2beb51155c"
    alias: "[Light] Master Bedroom Lamp 2: Adaptive Lighting (Toggle Brightness Adjustment)"
    description: ""
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        to: "Circadian"
      - platform: state
        entity_id: binary_sensor.light_master_bedroom_lamp_2_brightness
    variables:
      brightness_mode: "{{ states('binary_sensor.light_mf_bedroom_1_lamp_2_autobrightness') }}"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
    action:
      - service: "switch.turn_{{ brightness_mode }}"
        data:
          entity_id:
            - switch.adaptive_lighting_adapt_brightness_mf_bedroom_1_lamp_2

  - id: "92bc214d-271f-41e2-9ec4-8acc93475bb5"
    alias: "[Light] Master Bedroom Lamp 2: Adaptive Lighting (Turn Off Brightness Adjustment)"
    initial_state: false
    description: ""
    trigger:
        - platform: event
          event_type: hue_event
          event_data:
            id: bf_great_room_switch_button
            subtype: 3
        - platform: event
          event_type: hue_event
          event_data:
            id: bf_great_room_switch_button
            subtype: 2
    condition: []
    action:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.adaptive_lighting_adapt_brightness_mf_bedroom_1_lamp_2
    mode: single

  - id: "5db29ab1-0ad3-492d-9cb0-763c0d2e6561"
    alias: "[Light] MF: Master Bedroom Lamp 2 at Night"
    description: "Turn on Master Bedroom Lamp 2 at night"
    initial_state: false
    trigger:
      - event: sunset
        platform: sun
    condition: []
    action:
      - data: {}
        entity_id: light.mf_bedroom_1_lamp_2
        service: light.turn_on

# ==================================================================================================
#
# Rest Commands
#
# ==================================================================================================
rest_command:
  light_update_mf_bedroom_1_lamp_2_scene_homeassistant:
    url: "https://hue1.iot.home/clip/v2/resource/scene/{{ scene_id }}"
    method: put
    headers:
      hue-application-key: "{{ username }}"
    payload: '{
          "id":"{{ scene_id }}",
          "actions":[
          {
          "action":{ {{ color }},{{ brightness }},{{ bulb_01_on_state }} },
          "target":{"rid":"e7e3a4b4-c9ac-4841-929f-7330da707855","rtype":"light"}
          },{
          "action":{ {{ color }},{{ brightness }},{{ bulb_02_on_state }} },
          "target":{"rid":"95a7a21c-f290-4c7a-97ce-f13d8c856e4b","rtype":"light"}
          }
          ]
          }'
    verify_ssl: false
    content_type: "application/json"

# ==================================================================================================
#
# Scenes
#
# ==================================================================================================
scene:
  - id: "ad077505-0081-4ecc-ae1e-a566b42c5f53"
    name: "[Light] Enable Master Bedroom Automations"
    entities:
      automation.light_master_bedroom_lamp_2_at_night:
        state: "on"
      automation.light_master_bedroom_lamp_2_adaptive_lighting_toggle_brightness_adjustment:
        state: "on"

  # ================================================================================================
  #
  # Lamp 1 Scenes
  #
  # ================================================================================================
  - id: "d0380075-67cf-415e-a079-1c66fabc40fb"
    name: "[Light] MF: Master Bedroom Lamp 1 - Migraine"
    entities:
      light.mf_bedroom_1_lamp_1_bulb_1:
        state: "on"
        xy_color:
          - 0.17
          - 0.7
        brightness: 64
      light.mf_bedroom_1_lamp_1_bulb_2:
        state: "off"

  - id: "66453b6a-f834-4e8b-8211-1d669e61bcc8"
    name: "[Light] MF: Master Bedroom Lamp 1 - Darken"
    entities:
      light.mf_bedroom_1_lamp_1_bulb_1:
        state: "on"
        xy_color:
          - 0.689
          - 0.309
        brightness: 64
      light.mf_bedroom_1_lamp_1_bulb_2:
        state: "off"

  - id: "bf87d6ac-3a90-4092-8931-012522dc4397"
    name: "[Light] MF: Master Bedroom Lamp 1 - Bright"
    entities:
      light.mf_bedroom_1_lamp_1:
        state: "on"
        color_temp: 367
        brightness: 255

  - id: "d8ce6ef4-fb6c-4a5b-b1da-fa87d14a77e9"
    name: "[Light] MF: Master Bedroom Lamp 1 - Concentrate"
    entities:
      light.mf_bedroom_1_lamp_1:
        state: "on"
        color_temp: 230
        brightness: 255

  - id: "68e0f129-74ea-4e29-90e5-af5a1e8e861f"
    name: "[Light] MF: Master Bedroom Lamp 1 - Dimmed"
    entities:
      light.mf_bedroom_1_lamp_1:
        state: "on"
        color_temp: 369
        brightness: 76

  - id: "3556a43c-91c4-436b-b40e-81919e25e931"
    name: "[Light] MF: Master Bedroom Lamp 1 - Energize"
    entities:
      light.mf_bedroom_1_lamp_1:
        state: "on"
        color_temp: 156
        brightness: 255

  - id: "276fe8f5-8e97-4f7d-900d-61f52679b457"
    name: "[Light] MF: Master Bedroom Lamp 1 - Nightlight"
    entities:
      light.mf_bedroom_1_lamp_1:
        state: "on"
        color_temp: 454
        brightness: 1

  - id: "936f4109-bfaf-40a5-8d67-1d85707bc412"
    name: "[Light] MF: Master Bedroom Lamp 1 - Read"
    entities:
      light.mf_bedroom_1_lamp_1:
        state: "on"
        color_temp: 343
        brightness: 255

  - id: "ce0efdd4-0dc4-4b60-9a5d-53585166a9b3"
    name: "[Light] MF: Master Bedroom Lamp 1 - Relax"
    entities:
      light.mf_bedroom_1_lamp_1:
        state: "on"
        color_temp: 447
        brightness: 145

  - id: "db3d818a-ec93-48f9-ba1d-16b3440acc0f"
    name: "[Light] MF: Master Bedroom Lamp 1 - Off"
    entities:
      light.mf_bedroom_1_lamp_1:
        state: "off"

  # ================================================================================================
  #
  # Lamp 2 Scenes
  #
  # ================================================================================================
  - id: "1836a0ae-050e-476c-b8d6-aea5fd639f10"
    name: "[Light] MF: Master Bedroom Lamp 2 - Migraine"
    entities:
      light.mf_bedroom_1_lamp_2_bulb_1:
        state: "on"
        xy_color:
          - 0.17
          - 0.7
        brightness: 64
      light.mf_bedroom_1_lamp_2_bulb_2:
        state: "off"

  - id: "e92369eb-f339-49d7-af93-64b9cad81fd7"
    name: "[Light] MF: Master Bedroom Lamp 2 - Darken"
    entities:
      light.mf_bedroom_1_lamp_2_bulb_1:
        state: "on"
        xy_color:
          - 0.689
          - 0.309
        brightness: 64
      light.mf_bedroom_1_lamp_2_bulb_2:
        state: "off"

  - id: "06d149e8-b2ec-43ff-96fe-4bf48014d8ad"
    name: "[Light] MF: Master Bedroom Lamp 2 - Bright"
    entities:
      light.mf_bedroom_1_lamp_2:
        state: "on"
        color_temp: 367
        brightness: 255

  - id: "8f3aae5b-c4d6-4c24-8e09-947f51398b6c"
    name: "[Light] MF: Master Bedroom Lamp 2 - Concentrate"
    entities:
      light.mf_bedroom_1_lamp_2:
        state: "on"
        color_temp: 230
        brightness: 255

  - id: "13795b8f-7a5f-4150-9e82-319a3b45ed13"
    name: "[Light] MF: Master Bedroom Lamp 2 - Dimmed"
    entities:
      light.mf_bedroom_1_lamp_2:
        state: "on"
        color_temp: 369
        brightness: 76

  - id: "10b32f48-d3aa-47a2-89c9-84756d17c960"
    name: "[Light] MF: Master Bedroom Lamp 2 - Energize"
    entities:
      light.mf_bedroom_1_lamp_2:
        state: "on"
        color_temp: 156
        brightness: 255

  - id: "3c12122d-8471-431e-b10e-b4ae11728f97"
    name: "[Light] MF: Master Bedroom Lamp 2 - Nightlight"
    entities:
      light.mf_bedroom_1_lamp_2:
        state: "on"
        color_temp: 454
        brightness: 1

  - id: "b5353749-f92f-4974-9550-247f93a06820"
    name: "[Light] MF: Master Bedroom Lamp 2 - Read"
    entities:
      light.mf_bedroom_1_lamp_2:
        state: "on"
        color_temp: 343
        brightness: 255

  - id: "aefd3be3-e983-49b5-8b97-4b3a083d77ab"
    name: "[Light] MF: Master Bedroom Lamp 2 - Relax"
    entities:
      light.mf_bedroom_1_lamp_2:
        state: "on"
        color_temp: 447
        brightness: 145

  - id: "b9065ae7-5046-47e2-888c-7e3255337346"
    name: "[Light] MF: Master Bedroom Lamp 2 - Off"
    entities:
      light.mf_bedroom_1_lamp_2:
        state: "off"

  # ================================================================================================
  #
  # Ceiling Fixture
  #
  # ================================================================================================
  - id: "1576c6b9-16a4-47b6-b0bf-bdfb26454cbd"
    name: "[Light] MF: Master Bedroom Ceiling Fixture - Migraine"
    entities:
      light.mf_bedroom_ceiling_fixture:
        state: "on"
        xy_color:
          - 0.17
          - 0.7
        brightness: 64

  - id: "8c7b4e25-486a-46e9-a344-a973254ba4d7"
    name: "[Light] MF: Master Bedroom Ceiling Fixture - Darken"
    entities:
      light.mf_bedroom_ceiling_fixture:
        state: "on"
        xy_color:
          - 0.689
          - 0.309
        brightness: 64

  - id: "72a7b482-a657-499a-bc00-05c1a2b4262c"
    name: "[Light] MF: Master Bedroom Ceiling Fixture - Bright"
    entities:
      light.mf_bedroom_ceiling_fixture:
        state: "on"
        color_temp: 367
        brightness: 255

  - id: "bbeb9d3b-5a5c-4194-8963-0c8ec8f2407f"
    name: "[Light] MF: Master Bedroom Ceiling Fixture - Concentrate"
    entities:
      light.mf_bedroom_ceiling_fixture:
        state: "on"
        color_temp: 230
        brightness: 255

  - id: "90e4115f-a8e2-4354-af82-a5b10992277f"
    name: "[Light] MF: Master Bedroom Ceiling Fixture - Dimmed"
    entities:
      light.mf_bedroom_ceiling_fixture:
        state: "on"
        color_temp: 369
        brightness: 76

  - id: "52e2196c-c222-434d-8f58-ca9a598ad359"
    name: "[Light] MF: Master Bedroom Ceiling Fixture - Energize"
    entities:
      light.mf_bedroom_ceiling_fixture:
        state: "on"
        color_temp: 156
        brightness: 255

  - id: "2df23591-b05e-401b-80c8-f419f4864f96"
    name: "[Light] MF: Master Bedroom Ceiling Fixture - Nightlight"
    entities:
      light.mf_bedroom_ceiling_fixture:
        state: "on"
        color_temp: 454
        brightness: 1

  - id: "d70c11f6-768e-4036-8e95-755a98b207dd"
    name: "[Light] MF: Master Bedroom Ceiling Fixture - Read"
    entities:
      light.mf_bedroom_ceiling_fixture:
        state: "on"
        color_temp: 343
        brightness: 255

  - id: "887b1e4d-9f65-45b1-9974-5e3e2d34fa8a"
    name: "[Light] MF: Master Bedroom Ceiling Fixture - Relax"
    entities:
      light.mf_bedroom_ceiling_fixture:
        state: "on"
        color_temp: 447
        brightness: 145

  - id: "6b214d35-6da1-44ed-bbbd-8ec4cbbff627"
    name: "[Light] MF: Master Bedroom Ceiling Fixture - Off"
    entities:
      light.mf_bedroom_ceiling_fixture:
        state: "off"

# ==================================================================================================
#
# Template binary_sensors and sensors
#
# ==================================================================================================
template:
  - binary_sensor:
      - unique_id: "d03e7d81-3a2e-4ffe-b2bf-962ead50cd1c"
        name: "[Light] MF: Master Bedroom Lamp 1 (Autobrightness)"
        state: >-
          {{ (
               state_attr("switch.adaptive_lighting_mf_bedroom_1_lamp_1", "brightness_pct") | int ) <
               ( state_attr("binary_sensor.light_mf_bedroom_1_lamp_1_autobrightness", "brightness_max")
               | int )
             and ( state_attr("switch.adaptive_lighting_mf_bedroom_1_lamp_1", "brightness_pct") | int ) >
             ( state_attr("binary_sensor.light_mf_bedroom_1_lamp_1_autobrightness", "brightness_min") | int
             ) }}
        attributes:
          brightness: >-
            {% if state_attr("light.mf_bedroom_1_lamp_1", "brightness") == None or
               is_state_attr("light.mf_bedroom_1_lamp_1", "brightness", "unknown") or
               is_state("light.mf_bedroom_1_lamp_1", "off") %}
              {{ ( state_attr("switch.adaptive_lighting_mf_bedroom_1_lamp_1", "brightness_pct" ) | int | int ) }}
            {% else %}
              {{ ( state_attr("light.mf_bedroom_1_lamp_1","brightness") / 254 * 100 ) | int }}
            {% endif %}
          brightness_max: >-
            {{ state_attr("binary_sensor.light_mf_bedroom_1_lamp_1_autobrightness", "brightness") | int + 4 }}
          brightness_min: >-
            {{ state_attr("binary_sensor.light_mf_bedroom_1_lamp_1_autobrightness", "brightness") | int - 4 }}
          xy_color: >-
            {{ state_attr("light.mf_bedroom_1_lamp_1", "xy_color") }}
          color_temp: >-
            {{ state_attr("light.mf_bedroom_1_lamp_1", "color_temp") }}

      - unique_id: "2d72d588-2e84-474e-bb1a-362d1c4ff334"
        name: "[Light] MF: Master Bedroom Lamp 2 (Autobrightness)"
        state: >-
          {{ (
               state_attr("switch.adaptive_lighting_mf_bedroom_1_lamp_2", "brightness_pct") | int ) <
               ( state_attr("binary_sensor.light_mf_bedroom_1_lamp_2_autobrightness", "brightness_max")
               | int )
             and ( state_attr("switch.adaptive_lighting_mf_bedroom_1_lamp_2", "brightness_pct") | int ) >
             ( state_attr("binary_sensor.light_mf_bedroom_1_lamp_2_autobrightness", "brightness_min") | int
             ) }}
        attributes:
          brightness: >-
            {% if state_attr("light.mf_bedroom_1_lamp_2", "brightness") == None or
               is_state_attr("light.mf_bedroom_1_lamp_2", "brightness", "unknown") or
               is_state("light.mf_bedroom_1_lamp_2", "off") %}
              {{ ( state_attr("switch.adaptive_lighting_mf_bedroom_1_lamp_2", "brightness_pct" ) | int | int ) }}
            {% else %}
              {{ ( state_attr("light.mf_bedroom_1_lamp_2","brightness") / 254 * 100 ) | int }}
            {% endif %}
          brightness_max: >-
            {{ state_attr("binary_sensor.light_mf_bedroom_1_lamp_2_autobrightness", "brightness") | int + 4 }}
          brightness_min: >-
            {{ state_attr("binary_sensor.light_mf_bedroom_1_lamp_2_autobrightness", "brightness") | int - 4 }}
          xy_color: >-
            {{ state_attr("light.mf_bedroom_1_lamp_2", "xy_color") }}
          color_temp: >-
            {{ state_attr("light.mf_bedroom_1_lamp_2", "color_temp") }}

      - unique_id: "969aceec-9cc3-4c11-926a-6d5eee3b940a"
        name: "[Light] Master Bedroom Color Mode"
        state: "{{ state_attr('light.mf_bedroom_1','color_mode') == 'xy' }}"

  - sensor:

      - unique_id: "101b21a5-0f36-4171-ae6d-38552da993c1"
        name: "[Light] Master Bedroom Lamp 1 Color"
        state: "{{ state_attr('light.mf_bedroom_1_lamp_1', 'xy_color') }}"

      - unique_id: "8970dec0-877b-4cbd-a98b-0f708475377a"
        name: "[Light] Master Bedroom Lamp 2 Color"
        state: "{{ state_attr('light.mf_bedroom_1_lamp_2', 'xy_color') }}"
