# ==================================================================================================
#
# Master Bedroom Light Configuration
#
# Lights:
#   light.main_lamp_1: Master Bedroom Lamp 1 Lightbulb 1
#   light.main_lamp_2: Master Bedroom Lamp 2 Lightbulb 1
#   light.main_lamp_4: Master Bedroom Ceiling Lightbulb 2
#   light.main_lamp_14: Master Bedroom Lamp 1 Lightbulb 2
#   light.main_lamp_15: Master Bedroom Lamp 2 Lightbulb 2
#   light.main_lamp_16: Master Bedroom Ceiling Lightbulb 1
#
# Light Groups:
#   - light.den_couch_lamp_1
#   - light.den_couch_lamp_2
#   - light.den_ceiling
#   - light.den_fireplace
#   - light.den_tower_lamp
#   - light.den_table_lamp
#
# ==================================================================================================
adaptive_lighting:
  - name: "MF: Master Bedroom Lamp 1"
    lights:
      - light.mf_bedroom_1_lamp_1
    initial_transition: 1
    min_color_temp: 2200
    max_color_temp: 6500
  - name: "MF: Master Bedroom Lamp 2"
    lights:
      - light.mf_bedroom_1_lamp_2
    initial_transition: 1
    min_color_temp: 2200
    max_color_temp: 6500
  - name: "MF: Master Bedroom Ceiling"
    lights:
      - light.mf_bedroom_1_ceiling
    initial_transition: 1
    min_color_temp: 2200
    max_color_temp: 6500

# ==================================================================================================
#
# Automations
#
#
#
# ==================================================================================================
automation:
  - id: "848efd5b-0d62-496b-8da2-ff2beb51155c"
    alias: "[Light] Master Bedroom Lamp 2: Adaptive Lighting (Toggle Brightness Adjustment)"
    description: ""
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        to: "Circadian"
      - platform: state
        entity_id: binary_sensor.light_master_bedroom_lamp_2_brightness
    variables:
      brightness_mode: "{{ states('binary_sensor.light_master_bedroom_lamp_2_autobrightness') }}"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
    action:
      - service: "switch.turn_{{ brightness_mode }}"
        data:
          entity_id:
            - switch.adaptive_lighting_master_bedroom_lamp_2_with_brightness_adjustment

  - id: "5db29ab1-0ad3-492d-9cb0-763c0d2e6561"
    alias: "[Light] Master Bedroom Lamp 2 at Night"
    description: "Turn on Master Bedroom Lamp 2 at night"
    initial_state: false
    trigger:
      - event: sunset
        platform: sun
    condition: []
    action:
      - data: {}
        entity_id: light.master_bedroom_lamp_2
        service: light.turn_on

# # ==================================================================================================
# #
# # Scenes
# #
# # ==================================================================================================
# scene:
#   - id: "ad077505-0081-4ecc-ae1e-a566b42c5f53"
#     name: "[Light] Enable Master Bedroom Automations"
#     entities:
#       automation.light_master_bedroom_lamp_2_at_night:
#         state: "on"


# # ==================================================================================================
# #
# # Templates
# #
# # ==================================================================================================
# binary_sensor:
#   - platform: template
#     sensors:
#       light_master_bedroom_lamp_1_autobrightness:
#         friendly_name: "[Light] Master Bedroom Lamp 1 Autobrightness"
#         value_template: >-
#           {{ (
#                state_attr("switch.adaptive_lighting_master_bedroom_lamp_1", "brightness_pct") | int ) <
#                ( state_attr("binary_sensor.light_master_bedroom_lamp_1_autobrightness", "brightness_max")
#                | int )
#              and ( state_attr("switch.adaptive_lighting_master_bedroom_lamp_1", "brightness_pct") | int ) >
#              ( state_attr("binary_sensor.light_master_bedroom_lamp_1_autobrightness", "brightness_min") | int
#              ) }}
#         attribute_templates:
#           brightness: >-
#             {% if state_attr("light.master_bedroom_lamp_1", "brightness") == None or
#                is_state_attr("light.master_bedroom_lamp_1", "brightness", "unknown") or
#                is_state("light.master_bedroom_lamp_1", "off") %}
#               {{ ( state_attr("switch.adaptive_lighting_basement", "brightness_pct" ) | int | int ) }}
#             {% else %}
#               {{ ( state_attr("light.master_bedroom_lamp_1","brightness") / 254 * 100 ) | int }}
#             {% endif %}
#           brightness_max: >-
#             {{ state_attr("binary_sensor.light_master_bedroom_lamp_1_autobrightness", "brightness") | int + 4 }}
#           brightness_min: >-
#             {{ state_attr("binary_sensor.light_master_bedroom_lamp_1_autobrightness", "brightness") | int - 4 }}
#           xy_color: >-
#             {{ state_attr("light.master_bedroom_lamp_1", "xy_color") }}
#           color_temp: >-
#             {{ state_attr("light.master_bedroom_lamp_1", "color_temp") }}

#       light_master_bedroom_lamp_2_autobrightness:
#         friendly_name: "[Light] Master Bedroom Lamp 2 Autobrightness"
#         value_template: >-
#           {{ (
#                state_attr("switch.adaptive_lighting_master_bedroom_lamp_2", "brightness_pct") | int ) <
#                ( state_attr("binary_sensor.light_master_bedroom_lamp_2_autobrightness", "brightness_max")
#                | int )
#              and ( state_attr("switch.adaptive_lighting_master_bedroom_lamp_2", "brightness_pct") | int ) >
#              ( state_attr("binary_sensor.light_master_bedroom_lamp_2_autobrightness", "brightness_min") | int
#              ) }}
#         attribute_templates:
#           brightness: >-
#             {% if state_attr("light.master_bedroom_lamp_2", "brightness") == None or
#                is_state_attr("light.master_bedroom_lamp_2", "brightness", "unknown") or
#                is_state("light.master_bedroom_lamp_2", "off") %}
#               {{ ( state_attr("switch.adaptive_lighting_basement", "brightness_pct" ) | int | int ) }}
#             {% else %}
#               {{ ( state_attr("light.master_bedroom_lamp_2","brightness") / 254 * 100 ) | int }}
#             {% endif %}
#           brightness_max: >-
#             {{ state_attr("binary_sensor.light_master_bedroom_lamp_2_autobrightness", "brightness") | int + 4 }}
#           brightness_min: >-
#             {{ state_attr("binary_sensor.light_master_bedroom_lamp_2_autobrightness", "brightness") | int - 4 }}
#           xy_color: >-
#             {{ state_attr("light.master_bedroom_lamp_2", "xy_color") }}
#           color_temp: >-
#             {{ state_attr("light.master_bedroom_lamp_2", "color_temp") }}

# #       light_master_bedroom_ceiling_autobrightness:
# #         friendly_name: "[Light] Master Bedroom Chair Autobrightness"
# #         value_template: >-
# #           {{ ( states("sensor.circadian_brightness") | int ) < ( state_attr("binary_sensor.light_master_bedroom_ceiling_autobrightness", "brightness_max") | int )
# #              and ( states("sensor.circadian_brightness") | int ) > ( state_attr("binary_sensor.light_master_bedroom_ceiling_autobrightness", "brightness_min") | int ) }}
# #         attribute_templates:
# #           brightness: >-
# #             {% if state_attr("light.master_bedroom_ceiling", "brightness") == None or
# #                is_state_attr("light.master_bedroom_ceiling", "brightness", "unknown")  or
# #                is_state("light.master_bedroom_ceiling", "off") %}
# #               {{ ( states("sensor.circadian_brightness") | int ) }}
# #             {% else %}
# #               {{ ( state_attr("light.master_bedroom_ceiling", "brightness") / 254 * 100 ) | int }}
# #             {% endif %}
# #           brightness_max: >-
# #             {{ state_attr("binary_sensor.light_master_bedroom_ceiling_autobrightness", "brightness") | int + 4 }}
# #           brightness_min: >-
# #             {{ state_attr("binary_sensor.light_master_bedroom_ceiling_autobrightness", "brightness") | int - 4 }}
# #           #xy_color: >-
# #           #  {{ state_attr("light.master_bedroom_ceiling","xy_color") }}
# #           color_temp: >-
# #             {{ state_attr("light.master_bedroom_ceiling","color_temp") }}

# sensor:
#   - platform: template
#     sensors:
#       light_master_lamp_1_xy_color:
#         friendly_name: "[Light] Master Lamp 1: XY Color"
#         value_template: "{{ state_attr('light.main_lamp_1','xy_color') }}"
#       light_master_lamp_2_xy_color:
#         friendly_name: "[Light] Master Lamp 2: XY Color"
#         value_template: "{{ state_attr('light.main_lamp_2','xy_color') }}"

template:
  - binary_sensor:
      - unique_id: "d03e7d81-3a2e-4ffe-b2bf-962ead50cd1c"
        name: "[Light] MF: Master Bedroom Lamp 1 (Autobrightness)"
        state: >-
          {{ (
               state_attr("switch.adaptive_lighting_mf_bedroom_1_lamp_1", "brightness_pct") | int ) <
               ( state_attr("binary_sensor.light_mf_bedroom_1_lamp_1_autobrightness", "brightness_max")
               | int )
             and ( state_attr("switch.adaptive_lighting_mf_bedroom_1_lamp_1", "brightness_pct") | int ) >
             ( state_attr("binary_sensor.light_mf_bedroom_1_lamp_1_autobrightness", "brightness_min") | int
             ) }}
        attributes:
          brightness: >-
            {% if state_attr("light.mf_bedroom_1_lamp_1", "brightness") == None or
               is_state_attr("light.mf_bedroom_1_lamp_1", "brightness", "unknown") or
               is_state("light.mf_bedroom_1_lamp_1", "off") %}
              {{ ( state_attr("switch.adaptive_lighting_mf_bedroom_1_lamp_1", "brightness_pct" ) | int | int ) }}
            {% else %}
              {{ ( state_attr("light.mf_bedroom_1_lamp_1","brightness") / 254 * 100 ) | int }}
            {% endif %}
          brightness_max: >-
            {{ state_attr("binary_sensor.light_mf_bedroom_1_lamp_1_autobrightness", "brightness") | int + 4 }}
          brightness_min: >-
            {{ state_attr("binary_sensor.light_mf_bedroom_1_lamp_1_autobrightness", "brightness") | int - 4 }}
          xy_color: >-
            {{ state_attr("light.mf_bedroom_1_lamp_1", "xy_color") }}
          color_temp: >-
            {{ state_attr("light.mf_bedroom_1_lamp_1", "color_temp") }}

      - unique_id: "2d72d588-2e84-474e-bb1a-362d1c4ff334"
        name: "[Light] MF: Master Bedroom Lamp 2 (Autobrightness)"
        state: >-
          {{ (
               state_attr("switch.adaptive_lighting_mf_bedroom_1_lamp_2", "brightness_pct") | int ) <
               ( state_attr("binary_sensor.light_mf_bedroom_1_lamp_2_autobrightness", "brightness_max")
               | int )
             and ( state_attr("switch.adaptive_lighting_mf_bedroom_1_lamp_2", "brightness_pct") | int ) >
             ( state_attr("binary_sensor.light_mf_bedroom_1_lamp_2_autobrightness", "brightness_min") | int
             ) }}
        attributes:
          brightness: >-
            {% if state_attr("light.mf_bedroom_1_lamp_2", "brightness") == None or
               is_state_attr("light.mf_bedroom_1_lamp_2", "brightness", "unknown") or
               is_state("light.mf_bedroom_1_lamp_2", "off") %}
              {{ ( state_attr("switch.adaptive_lighting_mf_bedroom_1_lamp_2", "brightness_pct" ) | int | int ) }}
            {% else %}
              {{ ( state_attr("light.mf_bedroom_1_lamp_2","brightness") / 254 * 100 ) | int }}
            {% endif %}
          brightness_max: >-
            {{ state_attr("binary_sensor.light_mf_bedroom_1_lamp_2_autobrightness", "brightness") | int + 4 }}
          brightness_min: >-
            {{ state_attr("binary_sensor.light_mf_bedroom_1_lamp_2_autobrightness", "brightness") | int - 4 }}
          xy_color: >-
            {{ state_attr("light.mf_bedroom_1_lamp_2", "xy_color") }}
          color_temp: >-
            {{ state_attr("light.mf_bedroom_1_lamp_2", "color_temp") }}

      - unique_id: "969aceec-9cc3-4c11-926a-6d5eee3b940a"
        name: "[Light] Master Bedroom Color Mode"
        state: "{{ state_attr('light.mf_bedroom_1','color_mode') == 'xy' }}"

  - sensor:

      - unique_id: "101b21a5-0f36-4171-ae6d-38552da993c1"
        name: "[Light] Master Bedroom Lamp 1 Color"
        state: "{{ state_attr('light.mf_bedroom_1_lamp_1', 'xy_color') }}"

      - unique_id: "8970dec0-877b-4cbd-a98b-0f708475377a"
        name: "[Light] Master Bedroom Lamp 2 Color"
        state: "{{ state_attr('light.mf_bedroom_1_lamp_2', 'xy_color') }}"
