# ==================================================================================================
#
# Great Lighting Configuration
#
# Lights:
#   - light.mf_den_ceiling_bulb
#     light id: 8
#   - light.mf_den_couch_lamp_1_bulb
#     light id: 7
#   - light.mf_den_couch_lamp_2_bulb
#     light id: 6
#   - light.mf_den_fireplace_bulb
#     light id: 25
#   - light.mf_dining_area_ceiling_bulb
#     light id: 31
#   - light.mf_entryway_ceiling_bulb
#     light id: 13
#   - light.mf_kitchen_ceiling_bulb
#     light id: 10
#   - light.mf_kitchen_island_ceiling_bulb
#     light id: 24
#   - light.mf_living_area_ceiling_bulb
#     light id: 26
#
# Light Groups (Rooms):
#   - light.mf_great_room
#
# Light Groups (Zones):
#   - light.mf_den_ceiling
#   - light.mf_den_couch_lamp_1
#   - light.mf_den_couch_lamp_2
#   - light.mf_den_fireplace
#   - light.mf_dining_area_ceiling
#   - light.mf_entryway_ceiling
#   - light.mf_kitchen_ceiling
#   - light.mf_kitchen_island_ceiling
#   - light.mf_living_area_ceiling

# ==================================================================================================
adaptive_lighting:
  - name: "MF: Den Couch Lamp 1"
    lights:
      - light.mf_den_couch_lamp_1
    initial_transition: 1
    min_color_temp: 2000
    max_color_temp: 6500
  - name: "MF: Den Couch Lamp 2"
    lights:
      - light.mf_den_couch_lamp_2
    initial_transition: 1
    min_color_temp: 2000
    max_color_temp: 6500

# ==================================================================================================
#
# Automations
#
# 
#
# ==================================================================================================
automation:
  # ================================================================================================
  #
  # Light fixture: Den Couch Lamp 2
  #
  # Light Group:
  #   - light.den_couch_lamp_2
  #
  # Automations:
  #   -
  #
  # ================================================================================================
  - id: "a80e9988-f278-4e7d-b625-e407db54e3f9"
    alias: "[Light] MF: Den Couch Lamp 2 - Adaptive Lighting (Toggle Brightness Adjustment)"
    description: ""
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        to: "Circadian"
      - platform: state
        entity_id: binary_sensor.light_mf_den_couch_lamp_2_brightness
    variables:
      brightness_mode: "{{ states('binary_sensor.light_mf_den_couch_lamp_2_autobrightness') }}"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
    action:
      - service: "switch.turn_{{ brightness_mode }}"
        data:
          entity_id:
            - switch.adaptive_lighting_mf_den_couch_lamp_2_with_brightness_adjustment

  - id: "5d497792-9062-446c-836f-d033bb7686a9"
    alias: "[Light] MF: Den Couch Lamp 2 - Adaptive Lighting (Turn Off Brightness Adjustment)"
    description: ""
    initial_state: false
    trigger:
        - platform: event
          event_type: hue_event
          event_data:
            id: mf_den_couch_lamp_2_switch_button
            subtype: 3
        - platform: event
          event_type: hue_event
          event_data:
            id: mf_den_couch_lamp_2_switch_button
            subtype: 2
    condition: []
    action:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.adaptive_lighting_adapt_brightness_den_couch_lamp_2
    mode: single

  # ================================================================================================
  #
  # Light fixture: Den Couch Lamp 1
  #
  # Light Group:
  #   - light.den_couch_lamp_1
  #
  # Automations:
  #   -
  #
  # ================================================================================================
  - id: "ab8e3063-5b76-4146-980f-d945c1d9eebd"
    alias: "[Light] MF: Den Couch Lamp 1 - Adaptive Lighting (Toggle Brightness Adjustment)"
    description: ""
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        to: "Circadian"
      - platform: state
        entity_id: binary_sensor.light_mf_den_couch_lamp_1_brightness
    variables:
      brightness_mode: "{{ states('binary_sensor.light_mf_den_couch_lamp_1_autobrightness') }}"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
    action:
      - service: "switch.turn_{{ brightness_mode }}"
        data:
          entity_id:
            - switch.adaptive_lighting_mf_den_couch_lamp_1_with_brightness_adjustment

  - id: "859d806f-611d-431a-a3cc-fec03a761795"
    alias: "[Light] MF: Den Couch Lamp 1 - Adaptive Lighting (Turn Off Brightness Adjustment)"
    description: ''
    initial_state: false
    trigger:
        - platform: event
          event_type: hue_event
          event_data:
            id: mf_den_couch_lamp_1_switch_button
            subtype: 3
        - platform: event
          event_type: hue_event
          event_data:
            id: mf_den_couch_lamp_1_switch_button
            subtype: 2
    condition: []
    action:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.adaptive_lighting_adapt_brightness_den_couch_lamp_1
    mode: single

#   # ================================================================================================
#   #
#   # Light fixture: Fireplace Lights
#   #
#   # Lights:
#   #   - 
#   #   - 
#   #   - 
#   #
#   # Automations:
#   #   - 
#   #
#   # ================================================================================================
#   - id: "b1a819a1-ffd0-4da3-9d16-0e8b3784aab4"
#     alias: "[Light] Den Fireplace: Adaptive Lighting (Toggle Brightness Adjustment)"
#     initial_state: false
#     trigger:
#       - platform: state
#         entity_id: input_select.light_mode
#         to: "Circadian"
#       - platform: state
#         entity_id: binary_sensor.light_mf_den_couch_lamp_1_brightness
#     variables:
#       brightness_mode: "{{ states('binary_sensor.light_mf_den_couch_lamp_1_autobrightness') }}"
#     condition:
#       condition: and
#       conditions:
#         - condition: template
#           value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
#     action:
#       - service: "switch.turn_{{ brightness_mode }}"
#         data:
#           entity_id:
#             - switch.adaptive_lighting_mf_den_couch_lamp_1_with_brightness_adjustment

#   # ================================================================================================
#   #
#   # Light fixture: Den Ceiling Lights
#   #
#   # Lights:
#   #   - 
#   #   - 
#   #   - 
#   #
#   # Automations:
#   #   - 
#   #
#   # ================================================================================================
#   - id: "a9f92c36-73f7-40cb-901e-2db2f2ee7608"
#     alias: "[Light] Den Ceiling: Adaptive Lighting (with Brightness Adjustment)"
#     initial_state: false
#     trigger:
#       - platform: state
#         entity_id: input_select.light_mode
#         to: "Circadian"
#       - platform: state
#         entity_id: binary_sensor.light_mf_den_couch_lamp_1_brightness
#     variables:
#       brightness_mode: "{{ states('binary_sensor.light_mf_den_couch_lamp_1_autobrightness') }}"
#     condition:
#       condition: and
#       conditions:
#         - condition: template
#           value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
#     action:
#       - service: "switch.turn_{{ brightness_mode }}"
#         data:
#           entity_id:
#             - switch.adaptive_lighting_mf_den_couch_lamp_1_with_brightness_adjustment

#   # ================================================================================================
#   #
#   # Set Lighting Mode: Circadian (with Brightness adjustments)
#   #
#   # - In the morning when the sun rises to 18 degrees below the horizon
#   #   enable
#   # ================================================================================================
#   - id: "0b2cebc3-9523-4096-b26a-481ee222d4b5"
#     alias: "[Light] MF: Den Tower Lamp: Adaptive Lighting (Toggle Brightness Adjustment)"
#     initial_state: false
#     trigger:
#       - platform: state
#         entity_id: input_select.light_mode
#         to: "Circadian"
#       - platform: state
#         entity_id: binary_sensor.light_mf_den_couch_lamp_1_brightness
#     variables:
#       brightness_mode: "{{ states('binary_sensor.light_mf_den_couch_lamp_1_autobrightness') }}"
#     condition:
#       condition: and
#       conditions:
#         - condition: template
#           value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
#     action:
#       - service: "switch.turn_{{ brightness_mode }}"
#         data:
#           entity_id:
#             - switch.adaptive_lighting_mf_den_couch_lamp_1_with_brightness_adjustment


# ==================================================================================================
#
# Input Select
#
# ==================================================================================================

# ==================================================================================================
#
# Rest Command
#
# ==================================================================================================
rest_command:
  light_update_mf_den_couch_lamp_1_scene_homeassistant:
    url: "https://hue1.iot.home/clip/v2/resource/scene/{{ scene_id }}"
    method: put
    headers:
      hue-application-key: "{{ username }}"
    payload: '{
          "id":"{{ scene_id }}",
          "actions":[
          {
          "action":{ {{ color }},{{ brightness }},{{ bulb_01_on_state }} },
          "target":{"rid":"0bdf5862-6217-4ab3-b9d3-bed4daf06f7c","rtype":"light"}
          }
          ]
          }'
    verify_ssl: false
    content_type: "application/json"
  light_update_mf_den_couch_lamp_2_scene_homeassistant:
    url: "https://hue1.iot.home/clip/v2/resource/scene/{{ scene_id }}"
    method: put
    headers:
      hue-application-key: "{{ username }}"
    payload: '{
          "id":"{{ scene_id }}",
          "actions":[
          {
          "action":{ {{ color }},{{ brightness }},{{ bulb_01_on_state }} },
          "target":{"rid":"b71eb26f-4d78-404a-a51a-49043497b63c","rtype":"light"}
          }
          ]
          }'
    verify_ssl: false
    content_type: "application/json"

# ==================================================================================================
#
# Scenes:
#   - Darken Room
#   - Migraine
#
# ==================================================================================================
scene:
  - id: "e2b63d06-9725-4e40-87ef-8feba9956177"
    name: "[Light] MF: Enable Den Automations"
    entities:
      automation.light_mf_den_couch_lamp_2_adaptive_lighting_toggle_brightness_adjustment:
        state: 'on'
      automation.light_mf_den_couch_lamp_2_adaptive_lighting_turn_off_brightness_adjustment:
        state: 'on'

  # ================================================================================================
  #
  # Den Couch Lamp 1
  #
  # ================================================================================================
  - id: "863a5290-97c7-48fa-93c6-52a49ca44103"
    name: "[Light] MF: Den Couch Lamp 1 - Darken"
    entities:
      light.mf_den_couch_lamp_1:
        state: "on"
        xy_color:
          - 0.6915
          - 0.3083
        brightness: 64

  - id: "8843858d-20ac-4ed4-bd1d-657a39206ace"
    name: "[Light] MF: Den Couch Lamp 1 - Migraine"
    entities:
      light.mf_den_couch_lamp_1:
        state: "on"
        xy_color:
          - 0.17
          - 0.7
        brightness: 64

  - id: "3ec0d226-7cf6-4688-8b5a-df6447f358be"
    name: "[Light] MF: Den Couch Lamp 1 - Bright"
    entities:
      light.mf_den_couch_lamp_1:
        state: "on"
        color_temp: 367
        brightness: 255

  - id: "fc7dc9b0-4396-42ce-af37-5902ee086238"
    name: "[Light] MF: Den Couch Lamp 1 - Concentrate"
    entities:
      light.mf_den_couch_lamp_1:
        state: "on"
        color_temp: 230
        brightness: 255

  - id: "8d78d8d4-ed41-4892-8d8d-fec62130155d"
    name: "[Light] MF: Den Couch Lamp 1 - Dimmed"
    entities:
      light.mf_den_couch_lamp_1:
        state: "on"
        color_temp: 369
        brightness: 76

  - id: "2a0f7fb0-6ca0-43e8-9b0b-960f7c93d71a"
    name: "[Light] MF: Den Couch Lamp 1 - Energize"
    entities:
      light.mf_den_couch_lamp_1:
        state: "on"
        color_temp: 156
        brightness: 255

  - id: "a94ba65d-769b-47fa-bae3-8875bff08e9f"
    name: "[Light] MF: Den Couch Lamp 1 - Nightlight"
    entities:
      light.mf_den_couch_lamp_1:
        state: "on"
        color_temp: 454
        brightness: 1

  - id: "e0dff188-c945-41ca-82b4-a24c019ef5a1"
    name: "[Light] MF: Den Couch Lamp 1 - Read"
    entities:
      light.mf_den_couch_lamp_1:
        state: "on"
        color_temp: 343
        brightness: 255

  - id: "f43bc7a8-4793-4302-acc2-6796cf862d7d"
    name: "[Light] MF: Den Couch Lamp 1 - Relax"
    entities:
      light.mf_den_couch_lamp_1:
        state: "on"
        color_temp: 447
        brightness: 145

  - id: "13503348-3d83-4c75-a530-2c32f3847a3d"
    name: "[Light] MF: Den Couch Lamp 1 - Off"
    entities:
      light.mf_den_couch_lamp_1:
        state: "off"

  # ================================================================================================
  #
  # Den Couch Lamp 2
  #
  # ================================================================================================
  - id: "93871962-9f75-444e-837c-99f722f4e8c3"
    name: "[Light] MF: Den Couch Lamp 2 - Darken"
    entities:
      light.mf_den_couch_lamp_2:
        state: "on"
        xy_color:
          - 0.6915
          - 0.3083
        brightness: 64

  - id: "5d637a2a-67c9-48ba-81fa-24cce9b4f091"
    name: "[Light] MF: Den Couch Lamp 2 - Migraine"
    entities:
      light.mf_den_couch_lamp_2:
        state: "on"
        xy_color:
          - 0.17
          - 0.7
        brightness: 64

  - id: "02d94dac-9921-4f2f-b02b-63c339eb0807"
    name: "[Light] MF: Den Couch Lamp 2 - Bright"
    entities:
      light.mf_den_couch_lamp_2:
        state: "on"
        color_temp: 367
        brightness: 255

  - id: "a34124d3-4b6b-4b46-be51-a38eeb4a3a35"
    name: "[Light] MF: Den Couch Lamp 2 - Concentrate"
    entities:
      light.mf_den_couch_lamp_2:
        state: "on"
        color_temp: 230
        brightness: 255

  - id: "dce8337f-15d2-4695-af40-16c899b0a708"
    name: "[Light] MF: Den Couch Lamp 2 - Dimmed"
    entities:
      light.mf_den_couch_lamp_2:
        state: "on"
        color_temp: 369
        brightness: 76

  - id: "64813793-3700-4a5c-9c21-80d8707430cf"
    name: "[Light] MF: Den Couch Lamp 2 - Energize"
    entities:
      light.mf_den_couch_lamp_2:
        state: "on"
        color_temp: 156
        brightness: 255

  - id: "de7322ee-5388-4318-bb8f-5055478ffbbe"
    name: "[Light] MF: Den Couch Lamp 2 - Nightlight"
    entities:
      light.mf_den_couch_lamp_2:
        state: "on"
        color_temp: 454
        brightness: 1

  - id: "bebd8c74-ef6f-45bf-b28f-9ad0c0dc951c"
    name: "[Light] MF: Den Couch Lamp 2 - Read"
    entities:
      light.mf_den_couch_lamp_2:
        state: "on"
        color_temp: 343
        brightness: 255

  - id: "fbedbfc7-254b-4fdf-abd8-e496da77c1d1"
    name: "[Light] MF: Den Couch Lamp 2 - Relax"
    entities:
      light.mf_den_couch_lamp_2:
        state: "on"
        color_temp: 447
        brightness: 145

  - id: "4efac057-e776-48c6-8d6e-79f4f27196d9"
    name: "[Light] MF: Den Couch Lamp 2 - Off"
    entities:
      light.mf_den_couch_lamp_2:
        state: "off"

# ==================================================================================================
#
# Templates
#
# ==================================================================================================
template:
  - binary_sensor:
      - name: "[Light] MF: Den Couch Lamp 1 (Autobrightness)"
        unique_id: "61149df3-3363-4717-a1f0-bdea867113b2"
        state: >-
          {{ (
               states("sensor.global_dummy_light_brightness") | int(100) ) <
               ( state_attr("binary_sensor.light_mf_den_couch_lamp_1_autobrightness", "brightness_max")
               | int(104) )
             and ( states("sensor.global_dummy_light_brightness") | int(100) ) >
             ( state_attr("binary_sensor.light_mf_den_couch_lamp_1_autobrightness", "brightness_min") | int(96)
             ) }}
        attributes:
          brightness: >-
            {% if state_attr("light.mf_den_couch_lamp_1", "brightness") == None or
               is_state_attr("light.mf_den_couch_lamp_1", "brightness", "unknown") or
               is_state("light.mf_den_couch_lamp_1", "off") %}
              {{ ( states("sensor.global_dummy_light_brightness") | int(100) ) }}
            {% else %}
              {{ ( state_attr("light.mf_den_couch_lamp_1","brightness") / 254 * 100 ) | int(100) }}
            {% endif %}
          brightness_max: >-
            {{ state_attr("binary_sensor.light_mf_den_couch_lamp_1_autobrightness", "brightness") | int(100) + 4 }}
          brightness_min: >-
            {{ state_attr("binary_sensor.light_mf_den_couch_lamp_1_autobrightness", "brightness") | int(100) - 4 }}

      - unique_id: "59aed0e9-54d2-4f94-a0e6-02899e1ff99b"
        name: "[Light] MF: Den Couch Lamp 2 (Autobrightness)"
        state: >-
          {{ (
               states("sensor.global_dummy_light_brightness") | int(100) ) <
               ( state_attr("binary_sensor.light_mf_den_couch_lamp_2_autobrightness", "brightness_max")
               | int(104) )
             and ( states("sensor.global_dummy_light_brightness") | int(100) ) >
             ( state_attr("binary_sensor.light_mf_den_couch_lamp_2_autobrightness", "brightness_min") | int(96)
             ) }}
        attributes:
          brightness: >-
            {% if state_attr("light.mf_den_couch_lamp_2", "brightness") == None or
               is_state_attr("light.mf_den_couch_lamp_2", "brightness", "unknown") or
               is_state("light.mf_den_couch_lamp_2", "off") %}
              {{ ( states("sensor.global_dummy_light_brightness") | int(100) ) }}
            {% else %}
              {{ ( state_attr("light.mf_den_couch_lamp_2","brightness") / 254 * 100 ) | int(100) }}
            {% endif %}
          brightness_max: >-
            {{ state_attr("binary_sensor.light_mf_den_couch_lamp_2_autobrightness", "brightness") | int(100) + 4 }}
          brightness_min: >-
            {{ state_attr("binary_sensor.light_mf_den_couch_lamp_2_autobrightness", "brightness") | int(100) - 4 }}

      - unique_id: "34c07133-565d-4368-99d4-587b129800b5"
        name: "[Light] MF: Great Room Color Mode"
        state: "{{ state_attr('light.mf_great_room','color_mode') == 'xy' }}"

  - sensor:
      - unique_id: "4a80505d-9bd2-405b-82e7-0babe7472038"
        name: "[Light] Den Couch Lamp 1 Color"
        state: "{{ state_attr('light.den_couch_lamp_1', 'xy_color') }}"

      - unique_id: "3e2b59e0-884f-405f-8b9b-4ce79e6a55eb"
        name: "[Light] Den Couch Lamp 2 Color"
        state: "{{ state_attr('light.den_couch_lamp_2', 'xy_color') }}"
