binary_sensor:
  - platform: bayesian
    name: user0005_status
    prior: 0.25
    probability_threshold: 0.91
    device_class: 'presence'
    observations:
      - entity_id: 'device_tracker.user0005_phone'
        prob_given_true: 0.9
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.user0005_phone_wifi'
        prob_given_true: 0.9
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.user0005_phone_bt'
        prob_given_true: 0.8
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'home'

input_select:
  # Example configuration.yaml entry
  user0005_status_dropdown:
    name: !secret user0005
    options:
      - Home
      - Work
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
    initial: Home

person:
  # - name: user0005
  #   id: user0005
  #   device_trackers:
  #     - device_tracker.user0005_phone
  #     - device_tracker.user0005_phone_bt
  #     - device_tracker.user0005_phone_wifi

