binary_sensor:
  - platform: bayesian
    name: "User0002: Bayesian - Home"
    prior: 0.375
    probability_threshold: 0.9
    device_class: "presence"
    observations:
      # User0002: Phone GPS (Owntracks)
      - entity_id: "device_tracker.user0002_phone"
        prob_given_true: 0.9
        prob_given_false: 0.1
        platform: "state"
        to_state: "home"
      # User0002: Phone Wifi
      - entity_id: "device_tracker.b8_d7_af_78_0f_3c"
        prob_given_true: 0.7
        prob_given_false: 0.3
        platform: "state"
        to_state: "home"
      # User0002: Phone Bluetooth"
      - entity_id: "device_tracker.galaxy_note8_2"
        prob_given_true: 0.6
        prob_given_false: 0.4
        platform: "state"
        to_state: "home"
  - platform: bayesian
    name: "User0002: Bayesian - Away"
    prior: 0.1
    probability_threshold: 0.9
    device_class: "presenence"
    observations:
      - entity_id: "binary_sensor.user0002_distance_quarter_km"
        prob_given_true: 0.9
        platform: "state"
        to_state: "on"
      - entity_id: "binary_sensor.user0002_moving"
        prob_given_true: 0.9
        platform: "state"
        to_state: "moving"
     

input_select:
  user0002_status_dropdown:
    name: "User0002 Status Dropdown"
    options:
      - Home
      - Work
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
    initial: Home

person:
  - name: user0002
    id: user0002
    device_trackers:
      - device_tracker.user0002_phone
      - device_tracker.b8_d7_af_78_0f_3c

template:
  - binary_sensor:
      - unique_id: "375f2267-3ba5-4fa6-b960-9e31a7364875"
        name: "User0002: Status"
        state: >-
          {{ state_attr('binary_sensor.user0002_bayesian_home', 'probability') >
             state_attr('binary_sensor.user0002_bayesian_away', 'probability') }}
        device_class: presence

      - unique_id: "912c3e59-bfe0-42a2-aa48-14dba4b31b30"
        name: "User0002: Phone Charging Status"
        state: "{{ ( states('sensor.user0002_phone_charging_status') | int > 1 ) }}"
        device_class: battery_charging

      - unique_id: "264b827f-06df-475a-8d14-e8f57413fa45"
        name: "User0002: Distance - Quarter KM"
        state: "{{ ( states('sensor.user0002_distance') | float > 0.25 ) }}"

      - unique_id: "b9fbe5d1-c1a4-4058-8f0c-eb45ea86d016"
        name: "User0002: Moving"
        state: "{{ ( states('sensor.user0002_velocity') | float > 0 ) }}"
        device_class: moving

      - unique_id: "28df0aa2-d5d5-498b-8c07-6da70c61d1da"
        name: "User0002: Laptop"
        state: >-
          {{ is_state("device_tracker.user0002_laptop_1_wifi", "home")
          or is_state("device_tracker.user0002_laptop_2_wifi", "home") }}
        device_class: connectivity


  - sensor:
      - unique_id: "4f1abd71-a0d3-45f4-a87a-3059c924f462"
        name: "User0002: Velocity"
        state: "{{ state_attr('device_tracker.user0002_phone', 'velocity') }}"
        state_class: measurement
        unit_of_measurement: kph

      - unique_id: "232a0a08-6650-41c8-bcbd-ac3d1875d538"
        name: "User0002: Distance"
        state: "{{ distance('device_tracker.user0002_phone') }}"
        state_class: measurement
        unit_of_measurement: km

      - unique_id: "79617b70-87f2-4a65-a3a3-a901cfa3b031"
        name: "User0002: Phone Charging Status"
        state: "{{ state_attr('device_tracker.user0002_phone', 'battery_status') }}"

      - unique_id: "239738c6-44b1-448f-a281-01d1a6135f08"
        name: "User0002: Phone Battery"
        state: "{{ state_attr('device_tracker.user0002_phone', 'battery_level') }}"
        state_class: measurement
        unit_of_measurement: "%"
