binary_sensor:
  - platform: bayesian
    name: user0003_status
    prior: 0.25
    probability_threshold: 0.91
    device_class: 'presence'
    observations:
      - entity_id: 'device_tracker.user0003_phone'
        prob_given_true: 0.9
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.user0003_phone_wifi'
        prob_given_true: 0.9
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.user0003_phone_bt'
        prob_given_true: 0.8
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.cc4463abc980'
        prob_given_true: 0.7
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'home'

input_select:
  # Example configuration.yaml entry
  user0003_status_dropdown:
    options:
      - Home
      - Work
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
    initial: Home

# person:
#   - name: user0003
#     id: user0003
#     device_trackers:
#       - device_tracker.user0003_phone
#       - device_tracker.user0003_phone_bt
#       - device_tracker.user0003_phone_wifi
#       - device_tracker.cc4463abc980
#       - device_tracker.user0003_ipad
#       - device_tracker.user0003_ipad_bt
