binary_sensor:
  - platform: bayesian
    unique_id: "748ded88-ad08-4368-95d3-a6e72c6d66cb"
    name: "user0001_status"
    prior: 0.75
    probability_threshold: 0.91
    device_class: 'presence'
    observations:
      - entity_id: 'device_tracker.b8_d7_af_6b_9a_e3'
        prob_given_true: 0.9
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.user0001_laptop_wifi'
        prob_given_true: 0.6
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'home'


input_select:
  # Example configuration.yaml entry
  user0001_status_dropdown:
    name: "User0001 Status Dropdown"
    options:
      - Home
      - Work
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
    initial: Home

person:
  - name: user0001
    id: user0001
    device_trackers:
      - device_tracker.b8_d7_af_6b_9a_e3
      - device_tracker.user0001_laptop_wifi

