# ======================================================================
#
# Back Bedroom Lighting Configuration
#
# Lights:
#   light.main_lamp_22: Back Bedroom Ceiling Lightbulb
#   light.main_lamp_28: Back Bedroom Closet Lightbulb
# Light Groups:
#   light.back_bedroom_ceiling
#     hue lights: 22
#   light.back_bedroom_closet
#     hue lights: 28
#
# Hue "Homeassistant" Scene IDs:
#   Back Bedroom Ceiling: qS-eiYbXIwAXNSl
#   Back Bodreom Closet: 
#
# ======================================================================

# ======================================================================
#
# Automations
#
# ======================================================================
automation:
  # ====================================================================
  #
  # Light Group: Back Bedroom Ceiling Lights
  #
  # Automations:
  #   - 
  #
  # ====================================================================
  - alias: '[Light] Back Bedroom Ceiling Light: Circadian Lighting (with Brightness Adjustment)'
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        to: "Circadian"
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_back_bedroom_ceiling_lights_with_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_back_bedroom_ceiling_lights_without_brightness_adjustment

  - alias: '[Light] Back Bedroom Ceiling Light: Circadian Lighting (without Brightness adjust)'
    initial_state: false
    trigger:
      - platform: state
        entity_id: sensor.light_back_bedroom_ceiling_lights_autobrightness
        to: 'off'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_back_bedroom_ceiling_lights_without_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_back_bedroom_ceiling_lights_with_brightness_adjustment

  # ======================================================================
  #
  # Light fixture: Back Bedroom Closet
  #
  # Automations:
  #   - 
  #
  # ======================================================================
  - alias: '[Light] Back Bedroom Closet: Circadian Lighting (with Brightness Adjustment)'
    initial_state: false
    trigger:
      platform: state
      entity_id: input_select.light_mode
      to: "Circadian"
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_back_bedroom_closet_with_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_back_bedroom_closet_without_brightness_adjustment

  - alias: '[Light] Back Bedroom Closet: Circadian Lighting (without Brightness adjust)'
    initial_state: false
    trigger:
      - platform: state
        entity_id: binary_sensor.light_back_bedroom_closet_autobrightness
        to: 'off'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_back_bedroom_closet_without_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_back_bedroom_closet_with_brightness_adjustment

# ======================================================================
#
# Binary Sensor
#
# ======================================================================
binary_sensor:
  - platform: template
    sensors:
      light_back_bedroom_ceiling_autobrightness:
        friendly_name: "[Light] Back Bedroom Ceiling Autobrightness"
        value_template: >-
          {{ ( state_attr('binary_sensor.light_back_bedroom_ceiling_autobrightness', 'circadian_brightness') | int ) < ( state_attr('binary_sensor.light_back_bedroom_ceiling_autobrightness', 'brightness_max') | int )
             and ( state_attr('binary_sensor.light_back_bedroom_ceiling_autobrightness', 'circadian_brightness') | int ) > ( state_attr('binary_sensor.light_back_bedroom_ceiling_autobrightness', 'brightness_min') | int ) }}
        attribute_templates:
          circadian_brightness: >-
            {{ state_attr('switch.circadian_lighting_back_bedroom_ceiling_with_brightness_adjustment','brightness') | round(0) }}
          brightness: >-
            {% if is_state_attr('light.back_bedroom_ceiling','brightness', 'unknown') %}
              100
            {% else %}
              {{ ( state_attr('light.back_bedroom_ceiling','brightness') / 254 * 100 ) | int }}
            {% endif %}
          brightness_max: >-
            "{{ state_attr('binary_sensor.light_back_bedroom_ceiling_autobrightness', 'brightness') | int + 4 }}"
          brightness_min: >-
            "{{ state_attr('binary_sensor.light_back_bedroom_ceiling_autobrightness', 'brightness') | int - 4 }}"
          xy_color: >-
            {{ state_attr('light.back_bedroom_ceiling','xy_color') }}
          #colortemp: >-
          #  {{ state_attr('light.back_bedroom_ceiling','color_temp') }}

# ======================================================================
#
# Input Select
#
# ======================================================================
input_select:
  hue_scene_back_bedroom_bedroom:
    name: "[Light] Back Bedroom Scene"
    icon: mdi:palette
    initial: 'Circadian'
    options:
      - Arctic aurora
      - Sevanna sunset
      - Tropical twilight
      - Spring blossom
      - Relax
      - Read
      - Concentrate
      - Energize
      - Bright
      - Dimmed
      - Nightlight
      - Motown
      - Midsomer Sun
      - Midwinter
      - Ocean Dawn
      - Emerald Isle
      - Mountain Breeze
      - Spring lake
      - Moonlight
      - Starlight
      - Soho
      - Golden Pond
      - Frosty Dawn
      - Fairfax
      - Autumn Gold
      - Palm Beach
      - Lake Mist
      - Chinatown
      - Tokyo
      - Sunday Morning
      - Ibiza
      - Nebula
      - Galaxy
      - Ruby Glow
      - Winter mountain
      - Blue Lagoon
      - Honolulu
      - Lake Placid
      - Osaka
      - Sundowner
      - Blood Moon
      - Circadian
      - Night Mode
      - Migraine

# ======================================================================
#
# Rest Commands
#
# ======================================================================
# ======================================================================
#
# Group: Back Bedroom Ceiling
# Scene_ID: qS-eiYbXIwAXNSl
# Lights: 22
#
# ======================================================================

# ======================================================================
#
# Scenes:
#
# ======================================================================
#scene:
#  - name: "[Light] Back Bedroom: Darken Room"
#    entities:
#      light.back_bedroom_ceiling:

# ======================================================================
#
# Sensors
#
# ======================================================================
# sensor:
#   - platform: template
#     sensors:
#       light_back_bedroom_ceiling_circadian_brightness:
#         friendly_name: "[Light] Back Bedroom Ceiling Lights: Circadian Brightness"
#         value_template: "{{ state_attr('switch.circadian_lighting_back_bedroom_ceiling_lights_with_brightness_adjustment','brightness') | round(0) }}"
#         unit_of_measurement: '%'
#       light_back_bedroom_closet_circadian_brightness:
#         friendly_name: "[Light] Back Bedroom Closet: Circadian Brightness"
#         value_template: "{{ state_attr('switch.circadian_lighting_back_bedroom_closet_with_brightness_adjustment','brightness') | round(0) }}"
#         unit_of_measurement: '%'
#       light_back_bedroom_ceiling_brightness:
#         friendly_name: "[Light] Back Bedroom Ceiling Lights: Brightness"
#         value_template:  "{{ ( state_attr('light.back_bedroom_ceiling','brightness') / 254 * 100 ) | int }}"
#         unit_of_measurement: '%'
#       light_back_bedroom_closet_brightness:
#         friendly_name: "[Light] Back Bedroom Closet: Brightness"
#         value_template:  "{{ ( state_attr('light.back_bedroom_closet','brightness') / 254 * 100 ) | int }}"
#         unit_of_measurement: '%'

# ======================================================================
#
# Switches
#
# ======================================================================
switch:
  # ========================================
  #
  # Back Bedroom
  #
  # =========================================
  - platform: circadian_lighting
    name: "Back Bedroom Ceiling Lights (without Brightness Adjustment)"
    lights_ct:
      - light.back_bedroom_ceiling
    disable_brightness_adjust: true

  - platform: circadian_lighting
    name: "Back Bedroom Ceiling Lights (with Brightness Adjustment)"
    lights_ct:
      - light.back_bedroom_ceiling
    disable_brightness_adjust: false
    min_brightness: 25

  - platform: circadian_lighting
    name: "Back Bedroom Closet (without Brightness Adjustment)"
    lights_ct:
      - light.back_bedroom_closet
    disable_brightness_adjust: true

  - platform: circadian_lighting
    name: "Back Bedroom Closet (with Brightness Adjustment)"
    lights_ct:
      - light.back_bedroom_closet
    disable_brightness_adjust: false
    min_brightness: 25
