# ======================================================================
#
# Basement
#
#
#
# ======================================================================
automation:
  # ======================================================================
  #
  # Light fixture: Basement Ceiling Lights
  #
  # Lights:
  #   - 
  #   - 
  #   - 
  #
  # Automations:
  #   - 
  #
  # ======================================================================
  - alias: '[Light] Basement Ceiling Light: Circadian Lighting (with Brightness Adjustment)'
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        to: "Circadian"
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_basement_with_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_basement_without_brightness_adjustment

  - alias: '[Light] Basement Ceiling Light: Circadian Lighting (without Brightness adjust)'
    initial_state: false
    trigger:
      - platform: state
        entity_id: sensor.light_basement_brightness
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
        - condition: state
          entity_id: switch.circadian_lighting_basement_with_brightness_adjustment
          state: 'on'
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_basement_without_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_basement_with_brightness_adjustment

  - alias: '[Light] Basement Ceiling Light: Disable Circadian Lighting'
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        from: "Circadian"
    action:
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_basement_with_brightness_adjustment
            - switch.circadian_lighting_basement_without_brightness_adjustment

# ======================================================================
#
#
#
# ======================================================================
input_select:
  hue_scene_basement_bedroom:
    name: "[Light] Hue Basement Scene"
    icon: mdi:palette
    initial: 'Circadian'
    options:
      - Arctic aurora
      - Sevanna sunset
      - Tropical twilight
      - Spring blossom
      - Relax
      - Read
      - Concentrate
      - Energize
      - Bright
      - Dimmed
      - Nightlight
      - Motown
      - Midsomer Sun
      - Midwinter
      - Ocean Dawn
      - Emerald Isle
      - Mountain Breeze
      - Spring lake
      - Moonlight
      - Starlight
      - Soho
      - Golden Pond
      - Frosty Dawn
      - Fairfax
      - Autumn Gold
      - Palm Beach
      - Lake Mist
      - Chinatown
      - Tokyo
      - Sunday Morning
      - Ibiza
      - Nebula
      - Galaxy
      - Ruby Glow
      - Winter mountain
      - Blue Lagoon
      - Honolulu
      - Lake Placid
      - Osaka
      - Sundowner
      - Blood Moon
      - Circadian
      - Night Mode
      - Migraine

# ======================================================================
#
# Scenes
#
# Notes:
#   RGB Color Values: https://htmlcolorcodes.com/color-names/
# ======================================================================
# scene:
#   - id: '1576892024578'
#     name: "Basement: Darken Room"
#     entities:
#       automation.light_basement_ceiling_light_circadian_lighting_with_brightness_adjustment:
#         friendly_name: '[Light] Basement Ceiling Light: Circadian Lighting (with Brightness
#           Adjustment)'
#         last_triggered:
#         state: 'off'
#       automation.light_basement_ceiling_light_circadian_lighting_without_brightness_adjust:
#         friendly_name: '[Light] Basement Ceiling Light: Circadian Lighting (without
#           Brightness adjust)'
#         last_triggered:
#         state: 'off'
#       light.basement_lamp_20:
#         friendly_name: "Basement Right"
#         state: 'off'
#       light.basement_lamp_21:
#         friendly_name: "Basement Left"
#         state: 'off'
#       light.basement_lamp_9:
#         friendly_name: "Basement Center"
#         brightness_pct: 25
#         color_name: "darkred"
#         state: 'on'
#   - id: '1576960043395'
#     name: Basement Migraine
#     entities:
#       automation.light_basement_ceiling_light_circadian_lighting_with_brightness_adjustment:
#         friendly_name: '[Light] Basement Ceiling Light: Circadian Lighting (with Brightness
#           Adjustment)'
#         last_triggered:
#         state: 'off'
#       automation.light_basement_ceiling_light_circadian_lighting_without_brightness_adjust:
#         friendly_name: '[Light] Basement Ceiling Light: Circadian Lighting (without
#           Brightness adjust)'
#         last_triggered:
#         state: 'off'
#       light.basement_lamp_1:
#         friendly_name: "Basement Center"
#         state: 'on'
#         color_name: "darkgreen"
#         brightness_pct: 25
#       light.basement_lamp_2:
#         friendly_name: "Basement Right"
#         state: 'off'
#       light.basement_lamp_3:
#         friendly_name: "Basement Left"
#         state: 'off'

# ======================================================================
#
#
#
# ======================================================================
sensor:
  - platform: template
    sensors:
      light_basement_ceiling_circadian_brightness:
        friendly_name: "[Light] Basement Ceiling Lights: Circadian Brightness"
        value_template: "{{ state_attr('switch.circadian_lighting_basement_with_brightness_adjustment','brightness') | round(0) }}"
        unit_of_measurement: '%'
      light_basement_ceiling_brightness:
        friendly_name: "[Light] Basement Ceiling Lights: Brightness"
        value_template:  "{{ (state_attr('light.basement','brightness') / 254 * 100 ) | int }}"
        unit_of_measurement: '%'

# ======================================================================
#
#
#
# ======================================================================
switch:
  # ================================
  #
  # Basementroom
  #
  # ===============================
  - platform: circadian_lighting
    name: "Basement (without Brightness Adjustment)"
    lights_ct:
      - light.basement_lamp_1
      - light.basement_lamp_2
      - light.basement_lamp_3
    disable_brightness_adjust: true

  - platform: circadian_lighting
    name: "Basement (with Brightness Adjustment)"
    lights_ct:
      - light.basement_lamp_1
      - light.basement_lamp_2
      - light.basement_lamp_3
    disable_brightness_adjust: false
    min_brightness: 25
