# ==================================================================================================
#
# Bathroom 2
#
#
# Lights:
#   - light.main_lamp_
#   - light.main_lamp_
#   - light.main_lamp_
#   - light.main_lamp_
#   - light.main_lamp_
#   - light.main_lamp_
#   - light.main_lamp_
#   - light.main_lamp_
#   - light.main_lamp_
#   - light.main_lamp_
#   - light.main_lamp_
#
# Light Groups:
#   - light.den_couch_lamp_1
#   - light.den_couch_lamp_2
#   - light.den_ceiling
#   - light.den_fireplace
#   - light.den_tower_lamp
#   - light.den_table_lamp
#
# ==================================================================================================
automation:
  # ================================================================================================
  #
  # Light fixture: Bathroom 2
  #
  # Lights:
  #   - 
  #   - 
  #   - 
  #
  # Automations:
  #   - 
  #
  # ================================================================================================
  - id: "1587733513647"
    alias: "[Light] Bathroom 2: Circadian Lighting (with Brightness Adjustment)"
    description: "Turn on Bathroom 2 Circadian Lighting (with Brightness Adjustment)"
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        to: "Circadian"
      - platform: state
        entity_id: light_bathroom_2_autobrightness
        to: "on"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
    action:
      - service: switch.turn_on
        data: {}
        entity_id:
          - switch.circadian_lighting_bathroom_2_with_brightness_adjustment
      - service: switch.turn_off
        data: {}
        entity_id:
          - switch.circadian_lighting_bathroom_2_without_brightness_adjustment

  - alias: "[Light] Bathroom 2: Circadian Lighting (without Brightness adjust)"
    initial_state: false
    trigger:
      - platform: state
        entity_id: binary_sensor.light_bathroom_2_autobrightness
        to: "off"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_bathroom_2_without_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_bathroom_2_with_brightness_adjustment

# ======================================================================
#
# Binary Sensors
#
# ======================================================================
binary_sensor:
  - platform: template
    sensors:
      light_bathroom_2_autobrightness:
        friendly_name: "[Light] Bathroom 2 Autobrightness"
        value_template: >-
          {{ ( states("sensor.circadian_brightness") | int ) < ( state_attr("binary_sensor.light_bathroom_2_autobrightness", "brightness_max") | int )
             and ( states("sensor.circadian_brightness") | int ) > ( state_attr("binary_sensor.light_bathroom_2_autobrightness", "brightness_min") | int ) }}
        attribute_templates:
          brightness: >-
            {% if state_attr("light.bathroom_2", "brightness") == None or
               is_state_attr("light.bathroom_2","brightness", "unknown")  or
               is_state("light.bathroom_2", "off") -%}
              100
            {%- else %}
              {{ ( state_attr("light.bathroom_2","brightness") / 254 * 100 ) | int }}
            {% endif %}
          brightness_max: >-
            {{ state_attr("binary_sensor.light_bathroom_2_autobrightness", "brightness") | int + 4 }}
          brightness_min: >-
            {{ state_attr("binary_sensor.light_bathroom_2_autobrightness", "brightness") | int - 4 }}
          xy_color: >-
            {{ state_attr("light.bathroom_2","xy_color") }}
          color_temp: >-
            {{ state_attr("light.bathroom_2","color_temp") }}

# ======================================================================
#
#
#
# ======================================================================
input_select:
  hue_scene_bahroom_2:
    name: "[Light] Hue Bathroom 2 Scene"
    icon: mdi:palette
    initial: "Circadian"
    options:
      - Arctic aurora
      - Sevanna sunset
      - Tropical twilight
      - Spring blossom
      - Relax
      - Read
      - Concentrate
      - Energize
      - Bright
      - Dimmed
      - Nightlight
      - Motown
      - Midsomer Sun
      - Midwinter
      - Ocean Dawn
      - Emerald Isle
      - Mountain Breeze
      - Spring lake
      - Moonlight
      - Starlight
      - Soho
      - Golden Pond
      - Frosty Dawn
      - Fairfax
      - Autumn Gold
      - Palm Beach
      - Lake Mist
      - Chinatown
      - Tokyo
      - Sunday Morning
      - Ibiza
      - Nebula
      - Galaxy
      - Ruby Glow
      - Winter mountain
      - Blue Lagoon
      - Honolulu
      - Lake Placid
      - Osaka
      - Sundowner
      - Blood Moon
      - Circadian
      - Night Mode
      - Migraine

# ======================================================================
#
# Rest Commands
#
# Used to update hue scenes
#
# ======================================================================
# ======================================================================
#
# Group: Bathroom 2room
# Scene_ID: YMQdt3e0IgsRg5E
# Lights: 9, 20, 21
#
# ======================================================================

# ======================================================================
#
# Scenes
#
# Notes:
#   RGB Color Values: https://htmlcolorcodes.com/color-names/
# ======================================================================
scene:
  - id: '1587774493438'
    name: '[Light] Bathroom 2: Enable Automations'
    entities:
      automation.light_bathroom_2_circadian_lighting_with_brightness_adjust:
        friendly_name: '[Light] Bathroom 2: Circadian Lighting (with Brightness adjust)'
        state: 'off'
    entities:
      automation.light_bathroom_2_circadian_lighting_without_brightness_adjust:
        friendly_name: '[Light] Bathroom 2: Circadian Lighting (without Brightness adjust)'
        last_triggered:
        state: 'off'

#   - id: "1576892024578"
#     name: "[Light] Bathroom 2: Darken Room"
#     entities:
#       automation.light_bathroom_2_light_circadian_lighting_with_brightness_adjustment:
#         friendly_name: "[Light] Bathroom 2: Circadian Lighting (with Brightness
#           Adjustment)"
#         last_triggered:
#         state: "off"
#       automation.light_bathroom_2_light_circadian_lighting_without_brightness_adjust:
#         friendly_name: "[Light] Bathroom 2: Circadian Lighting (without
#           Brightness adjust)"
#         last_triggered:
#         state: "off"
#       light.main_lamp_20:
#         friendly_name: "Bathroom 2 Right"
#         state: "off"
#       light.main_lamp_21:
#         friendly_name: "Bathroom 2 Left"
#         state: "off"
#       light.main_lamp_9:
#         friendly_name: "Bathroom 2 Center"
#         brightness_pct: 25
#         color_name: "darkred"
#         state: "on"
#   - id: "1576960043395"
#     name: "[Light] Bathroom 2: Migraine"
#     entities:
#       automation.light_bathroom_2_light_circadian_lighting_with_brightness_adjustment:
#         friendly_name: "[Light] Bathroom 2: Circadian Lighting (with Brightness
#           Adjustment)"
#         last_triggered:
#         state: "off"
#       automation.light_bathroom_2_light_circadian_lighting_without_brightness_adjust:
#         friendly_name: "[Light] Bathroom 2: Circadian Lighting (without
#           Brightness adjust)"
#         last_triggered:
#         state: "off"
#       light.main_lamp_9:
#         friendly_name: "Bathroom 2 Center"
#         state: "on"
#         color_name: "darkgreen"
#         brightness_pct: 25
#       light.main_lamp_20:
#         friendly_name: "Bathroom 2 Right"
#         state: "off"
#       light.main_lamp_21:
#         friendly_name: "Bathroom 2 Left"
#         state: "off"

# ======================================================================
#
#
#
# ======================================================================
# sensor:
#   - platform: template
#     sensors:
#       light_bahroom_2_circadian_brightness:
#         friendly_name: "[Light] Bathroom 2 Light: Circadian Brightness"
#         value_template: "{{ state_attr("switch.circadian_lighting_bahroom_2_with_brightness_adjustment","brightness") | round(0) }}"
#         unit_of_measurement: "%"
#       light_bahroom_2_brightness:
#         friendly_name: "[Light] Bathroom 2 Light: Brightness"
#         value_template:  "{{ (state_attr("light.bahroom_2","brightness") / 254 * 100 ) | int }}"
#         unit_of_measurement: "%"
#       light_bahroom_2_xy_color:
#         friendly_name: "[Light] Bathroom 2 Center Ceiling Light: XY Color"
#         value_template: "{{ state_attr("light.main_lamp_9","xy_color") }}"

# ======================================================================
#
#
#
# ======================================================================
switch:
  # ================================
  #
  # Bathroom 2 room
  #
  # ===============================
  - platform: circadian_lighting
    name: "Bathroom 2 (without Brightness Adjustment)"
    lights_ct:
      - light.bathroom_2
    disable_brightness_adjust: true

  - platform: circadian_lighting
    name: "Bathroom 2 (with Brightness Adjustment)"
    lights_ct:
      - light.bathroom_2
    disable_brightness_adjust: false
    min_brightness: 1
