# ======================================================================
#
# Front Bedroom Lighting Configuration
#
#
#
# ======================================================================
automation:
  # ======================================================================
  #
  # Light fixture: Front Bedroom Ceiling Lights
  #
  # Lights:
  #   - 
  #   - 
  #   - 
  #
  # Automations:
  #   - 
  #
  # ======================================================================
  - alias: '[Lights] Front Bedroom Ceiling Lights: Circadian Lighting (with Brightness Adjustment)'
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        to: "Circadian"
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_front_bedroom_ceiling_lights_with_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_front_bedroom_ceiling_lights_without_brightness_adjustment

  - alias: '[Lights] Front Bedroom Ceiling Lights: Circadian Lighting (without Brightness adjust)'
    initial_state: false
    trigger:
      - platform: state
        entity_id: sensor.light_front_bedroom_ceiling_lights_brightness
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
        - condition: state
          entity_id: switch.circadian_lighting_front_bedroom_ceiling_lights_with_brightness_adjustment
          state: 'on'
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_front_bedroom_ceiling_lights_without_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_front_bedroom_ceiling_lights_with_brightness_adjustment

  - alias: '[Lights] Front Bedroom Ceiling Lights: Disable Circadian Lighting'
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        from: "Circadian"
    action:
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_front_bedroom_ceiling_lights_with_brightness_adjustment
            - switch.circadian_lighting_front_bedroom_ceiling_lights_without_brightness_adjustment

  # ======================================================================
  #
  # Light fixture: Front Bedroom Closet
  #
  # Lights:
  #   -
  #
  # Automations:
  #   - 
  #
  # ======================================================================
  - alias: '[Lights] Front Bedroom Closet: Circadian Lighting (with Brightness Adjustment)'
    initial_state: false
    trigger:
      platform: state
      entity_id: input_select.light_mode
      to: "Circadian"
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_front_bedroom_closet_with_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_front_bedroom_closet_without_brightness_adjustment

  - alias: '[Lights] Front Bedroom Closet: Circadian Lighting (without Brightness adjust)'
    initial_state: false
    trigger:
      - platform: state
        entity_id: sensor.light_front_bedroom_closet_brightness
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
        - condition: state
          entity_id: switch.circadian_lighting_front_bedroom_closet_with_brightness_adjustment
          state: 'on'
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_front_bedroom_closet_without_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_front_bedroom_closet_with_brightness_adjustment

  - alias: '[Lights] Front Bedroom Closet: Disable Circadian Lighting'
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        from: "Circadian"
    action:
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_front_bedroom_closet_with_brightness_adjustment
            - switch.circadian_lighting_front_bedroom_closet_without_brightness_adjustment

# ======================================================================
#
#
#
# ======================================================================
input_select:
  hue_scene_front_bedroom_bedroom:
    name: "[Light] Hue Front Bedroom Scene"
    icon: mdi:palette
    initial: 'Circadian'
    options:
      - Arctic aurora
      - Sevanna sunset
      - Tropical twilight
      - Spring blossom
      - Relax
      - Read
      - Concentrate
      - Energize
      - Bright
      - Dimmed
      - Nightlight
      - Motown
      - Midsomer Sun
      - Midwinter
      - Ocean Dawn
      - Emerald Isle
      - Mountain Breeze
      - Spring lake
      - Moonlight
      - Starlight
      - Soho
      - Golden Pond
      - Frosty Dawn
      - Fairfax
      - Autumn Gold
      - Palm Beach
      - Lake Mist
      - Chinatown
      - Tokyo
      - Sunday Morning
      - Ibiza
      - Nebula
      - Galaxy
      - Ruby Glow
      - Winter mountain
      - Blue Lagoon
      - Honolulu
      - Lake Placid
      - Osaka
      - Sundowner
      - Blood Moon
      - Circadian
      - Night Mode
      - Migraine

# ======================================================================
#
# Rest Commands:
#
# ======================================================================
# ======================================================================
#
# Group: Front Bedroom Ceiling
# Scene_ID: 0sMU7uHvTUUKIl7
# Lights: 23
#
# ======================================================================

# ======================================================================
#
#
#
# ======================================================================
# sensor:
#   - platform: template
#     sensors:
#       light_front_bedroom_ceiling_circadian_brightness:
#         friendly_name: "[Light] Front Bedroom Ceiling Lights: Circadian Brightness"
#         value_template: "{{ state_attr('switch.circadian_lighting_front_bedroom_ceiling_lights_with_brightness_adjustment','brightness') | round(0) }}"
#         unit_of_measurement: '%'
#       light_front_bedroom_closet_circadian_brightness:
#         friendly_name: "[Light] Front Bedroom Closet: Circadian Brightness"
#         value_template: "{{ state_attr('switch.circadian_lighting_front_bedroom_closet_with_brightness_adjustment','brightness') | round(0) }}"
#         unit_of_measurement: '%'
#       light_front_bedroom_ceiling_brightness:
#         friendly_name: "[Light] Front Bedroom Ceiling Lights: Brightness"
#         value_template:  "{{ ( state_attr('light.front_bedroom_ceiling','brightness') / 254 * 100 ) | int }}"
#         unit_of_measurement: '%'
#       light_front_bedroom_closet_brightness:
#         friendly_name: "[Light] Front Bedroom Closet: Brightness"
#         value_template:  "{{ ( state_attr('light.front_bedroom_closet','brightness') / 254 * 100 ) | int }}"
#         unit_of_measurement: '%'

# ======================================================================
#
# Switches
#
# ======================================================================
switch:
  # ===========================================
  #
  # Front Bedroom
  #
  # ===========================================
  - platform: circadian_lighting
    name: "Front Bedroom Ceiling Lights (without Brightness Adjustment)"
    lights_ct:
      - light.main_lamp_34
    disable_brightness_adjust: true

  - platform: circadian_lighting
    name: "Front Bedroom Ceiling Lights (with Brightness Adjustment)"
    lights_ct:
      - light.main_lamp_34
    disable_brightness_adjust: false
    min_brightness: 25

  - platform: circadian_lighting
    name: "Front Bedroom Closet (without Brightness Adjustment)"
    lights_ct:
      - light.main_lamp_29
    disable_brightness_adjust: true

  - platform: circadian_lighting
    name: "Front Bedroom Closet (with Brightness Adjustment)"
    lights_ct:
      - light.main_lamp_29
    disable_brightness_adjust: false
    min_brightness: 25
    #disable_entity:
    #disable_state:
