# ==================================================================================================
#
# common settings
#
# ==================================================================================================
homeassistant:
  customize_glob:
    "light.*bulb*":
      hidden:  true

# ==================================================================================================
#
# automations
#
# ==================================================================================================
automation:
  # - id: "1587755245580"
  #   alias: "Enable Light Automations"
  #   description: ""
  #   trigger:
  #     - event: start
  #       platform: homeassistant
  #   condition: []
  #   action:
  #     - scene: scene.light_enable_basement_automations
  #     - scene: scene.light_enable_common_automations
  #     - scene: scene.light_enable_den_automations
  #     - scene: scene.light_enable_master_bedroom_automations

  # ================================================================================================
  #
  # Set Lighting Mode: Circadian
  #
  # Trigger:
  # - In the morning when the sun rises to 18 degrees below the horizon
  #   enable
  #
  # Actions:
  #
  # ================================================================================================
  - alias: "[Light] Set Light Mode: Circadian"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        above: -18
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.light_mode
          option: "Circadian"

  # ================================================================================================
  #
  # Set Lighting Mode: Darken House
  #
  # Trigger:
  # - When the timer that begins the nighttime routine finishes
  #
  # Actions:
  #
  # ================================================================================================
  - alias: "[Light] Set Light Mode: Darken House"
    description: ""
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.lights_off
    condition: []
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.light_mode
          option: "Darken House"

  # ================================================================================================
  #
  # Set Lighting Mode: Migraine
  #
  # Trigger:
  # - Input Boolean: Special Migraine Mode is set to true
  #
  # Actions:
  # - 
  # ================================================================================================
  - alias: "[Light] Set Light Mode: Migraine"
    trigger:
      platform: state
      entity_id: input_boolean.special_migraine_mode
      to: "on"
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.light_mode
          option: "Migraine"

  # ================================================================================================
  #
  # Set Lighting Mode: Guests
  #
  # Trigger:
  # - Input Boolean: Special Guest Mode is set to true
  #
  # Actions:
  # -
  #
  # ================================================================================================
  - alias: "[Light] Set Light Mode: Guests"
    description: ""
    trigger:
    - platform: state
      entity_id: input_boolean.special_guest_present
      from: "off"
      to: "on"
    condition: []
    action:
      data:
        entity_id: input_select.light_mode
        option: "Guests"
      service: input_select.select_option

  - alias: "[Light] Update 'HomeAssistant' scene for circadian cycle"
    #initial_state: false
    description: "This allows switches to turn on to the correct color temp and brightness"
    trigger:
      - platform: time_pattern
        minutes: "/5"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
    action:
        service: script.light_update_scene_homeassistant_circadian

  - alias: "[Light] Update 'HomeAssistant' scene for darken house"
    #initial_state: false
    description: "This allows switches to turn on to the correct color temp and brightness"
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        to: "Darken House"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Darken House') }}"
    action:
        service: script.light_update_scene_homeassistant_darkenhouse

# ==================================================================================================
#
# Custom Component: Circadian Lighting
#
# https://github.com/claytonjn/hass-circadian_lighting
#
# ==================================================================================================
circadian_lighting:
  # Minimum color temperature to set
  min_colortemp: 2200
  # Maximum color temperature to set
  max_colortemp: 6500
  # Positive/Negative offset to sunrise/sunset
  # String: (-)HH:MM:SS
  # Default: None
  #sunrise_offset:
  #sunset_offset
  # Time for sunrise / sunset
  # Time: HH:MM:SS
  # Default: Actual Sunrise/Sunset time
  #sunrise_time:
  #sunset_time:
  # Latitude / Longitude / Elevation
  # Lat and Long used to determine sunrise / sunset / elevation
  # Default: Use Home Assistant Provided lat, long, elevation
  #latitudue:
  #longitude:
  #elevation:
  # Frequency at which the lights should be updated
  # Positive Integer: # (Seconds)
  # Default: 300 (300 seconds = 5 minutes)
  #interval:
  # Transition time for light changes
  # Float: # (Seconds)
  # Default: 60 (60 seconds =  1 minute)
  #transition

# ==================================================================================================
#
# Input select
#
# ==================================================================================================
input_select:
  light_mode:
    name: "Light Mode"
    options:
      - "Circadian"
      - "Darken House"
      - "Migraine"
      - "Sleeping (Migraine)"
      - "Night Out"
      - "Guests"
      - "Other"
    #initial: "Circadian"
    #icon: "mdi:light"

# ==================================================================================================
#
# Light Groups
#
# ==================================================================================================
light:
  - platform: group
    name: All lights
    entities:
      - light.basement
      - light.main_floor
  - platform: template
    lights:
      circadian_light:
        friendly_name: "Circadian Light used for testing"
        level_template: "{{ state_attr('switch.circadian_lighting_circadian_light','brightness') | round(0) }}"
        turn_on:
          service: notify.notify
          data:
            message: "Fake light turned on!"
        turn_off:
          service: notify.notify
          data:
            message: "Fake light turned off!"

#  - platform: sensehat

# ==================================================================================================
#
# Scenes
#
# ==================================================================================================
scene:
  name: "[Light] Enable Common Automations"
  entities:
    automation.light_set_light_mode_circadian:
      state: 'on'
    automation.light_set_light_mode_guests:
      state: 'on'
    automation.light_set_light_mode_migraine:
      state: 'on'
    automation.light_set_light_mode_darken_house:
      state: 'on'

# ==================================================================================================
#
# Update home assistant scenes
#
# ==================================================================================================
script:
  light_update_scene_homeassistant_circadian:
    alias: "[Light] Update Home Assistant Scenes (Circadian)"
    sequence:
      - service: rest_command.light_update_basement_scene_homeassistant
        data:
          scene_id: "wct01qioygY1j89"
          username: !secret hue2_username
          color: '"ct": {{ states("sensor.circadian_mired") | int }}'
          brightness: '"bri": {{ states("sensor.circadian_brightness_value") | int }}'
          bulb_01_on_state: "true"
          bulb_02_on_state: "true"
          bulb_03_on_state: "true"
          bulb_04_on_state: "true"
          bulb_05_on_state: "true"
          bulb_06_on_state: "true"
          bulb_07_on_state: "true"
          bulb_08_on_state: "true"
          bulb_09_on_state: "true"
          bulb_10_on_state: "true"
          bulb_11_on_state: "true"
          bulb_12_on_state: "true"
          bulb_13_on_state: "true"

      - service: rest_command.light_update_master_bedroom_chair_scene_homeassistant
        data:
          scene_id: "Foe7UChLJgWAZWE"
          username: !secret hue1_username
          color: '"ct": {{ states("sensor.circadian_mired") | int }}'
          brightness: '"bri": {{ states("sensor.circadian_brightness_value") | int }}'
          bulb_01_on_state: "true"
      - service: rest_command.light_update_master_bedroom_chair_scene_homeassistant
        data:
          scene_id: "Ho1gLz3G1oapF6z"
          username: !secret hue1_username
          color: '"ct": {{ states("sensor.circadian_mired") | int }}'
          brightness: '"bri": {{ states("sensor.circadian_brightness_value") | int }}'
          bulb_01_on_state: "true"

      - service: rest_command.light_update_master_bedroom_lamp_1_scene_homeassistant
        data:
          scene_id: "zr8ixsEYzTlD53i"
          username: !secret hue1_username
          color: '"ct": {{ states("sensor.circadian_mired") | int }}'
          brightness: '"bri": {{ states("sensor.circadian_brightness_value") | int }}'
          bulb_01_on_state: "true"
          bulb_02_on_state: "true"
      - service: rest_command.light_update_master_bedroom_lamp_1_scene_homeassistant
        data:
          scene_id: "OCrZppa5t98Hlnd"
          username: !secret hue1_username
          color: '"ct": {{ states("sensor.circadian_mired") | int }}'
          brightness: '"bri": {{ states("sensor.circadian_brightness_value") | int }}'
          bulb_01_on_state: "true"
          bulb_02_on_state: "true"

      - service: rest_command.light_update_master_bedroom_lamp_2_scene_homeassistant
        data:
          scene_id: "lWy-DMekfBnrLSu"
          username: !secret hue1_username
          color: '"ct": {{ states("sensor.circadian_mired") | int }}'
          brightness: '"bri": {{ states("sensor.circadian_brightness_value") | int }}'
          bulb_01_on_state: "true"
          bulb_02_on_state: "true"
      - service: rest_command.light_update_master_bedroom_lamp_2_scene_homeassistant
        data:
          scene_id: "bPMgpBKmlEUqMRc"
          username: !secret hue1_username
          color: '"ct": {{ states("sensor.circadian_mired") | int }}'
          brightness: '"bri": {{ states("sensor.circadian_brightness_value") | int }}'
          bulb_01_on_state: "true"
          bulb_02_on_state: "true"

      - service: rest_command.light_update_den_couch_lamp_1_scene_homeassistant
        data:
          scene_id: "XIpkjatAPzszIBY"
          username: !secret hue1_username
          color: '"ct": {{ states("sensor.circadian_mired") | int }}'
          brightness: '"bri": {{ states("sensor.circadian_brightness_value") | int }}'
          bulb_01_on_state: "true"
      - service: rest_command.light_update_den_couch_lamp_1_scene_homeassistant
        data:
          scene_id: "RYBofU8D0xfz-J6"
          username: !secret hue1_username
          color: '"ct": {{ states("sensor.circadian_mired") | int }}'
          brightness: '"bri": {{ states("sensor.circadian_brightness_value") | int }}'
          bulb_01_on_state: "true"

      - service: rest_command.light_update_den_couch_lamp_2_scene_homeassistant
        data:
          scene_id: "j10CCgzz0-DpX7w"
          username: !secret hue1_username
          color: '"ct": {{ states("sensor.circadian_mired") | int }}'
          brightness: '"bri": {{ states("sensor.circadian_brightness_value") | int }}'
          bulb_01_on_state: "true"
      - service: rest_command.light_update_den_couch_lamp_2_scene_homeassistant
        data:
          scene_id: "-vntxqGkxUZ4bZ8"
          username: !secret hue1_username
          color: '"ct": {{ states("sensor.circadian_mired") | int }}'
          brightness: '"bri": {{ states("sensor.circadian_brightness_value") | int }}'
          bulb_01_on_state: "true"

  light_update_scene_homeassistant_darkenhouse:
    alias: "[Light] Update Home Assistant Scenes (Darken House)"
    sequence:
      - service: rest_command.light_update_basement_scene_homeassistant
        data:
          scene_id: "wct01qioygY1j89"
          username: !secret hue2_username
          color: '"ct": 454'
          brightness: '"bri": 25 }}'
          bulb_01_on_state: "true"
          bulb_02_on_state: "true"
          bulb_03_on_state: "true"
          bulb_04_on_state: "true"
          bulb_05_on_state: "true"
          bulb_06_on_state: "true"
          bulb_07_on_state: "true"
          bulb_08_on_state: "true"
          bulb_09_on_state: "true"
          bulb_10_on_state: "true"
          bulb_11_on_state: "true"
          bulb_12_on_state: "true"
          bulb_13_on_state: "true"

      - service: rest_command.light_update_master_bedroom_chair_scene_homeassistant
        data:
          scene_id: "Foe7UChLJgWAZWE"
          username: !secret hue1_username
          color: '"ct": 454'
          brightness: '"bri": 25 }}'
          bulb_01_on_state: "true"
      - service: rest_command.light_update_master_bedroom_chair_scene_homeassistant
        data:
          scene_id: "Ho1gLz3G1oapF6z"
          username: !secret hue1_username
          color: '"ct": 454'
          brightness: '"bri": 25 }}'
          bulb_01_on_state: "true"

      - service: rest_command.light_update_master_bedroom_lamp_1_scene_homeassistant
        data:
          scene_id: "zr8ixsEYzTlD53i"
          username: !secret hue1_username
          color: '"ct": 454'
          brightness: '"bri": 25 }}'
          bulb_01_on_state: "true"
          bulb_02_on_state: "true"
      - service: rest_command.light_update_master_bedroom_lamp_1_scene_homeassistant
        data:
          scene_id: "OCrZppa5t98Hlnd"
          username: !secret hue1_username
          color: '"ct": 454'
          brightness: '"bri": 25 }}'
          bulb_01_on_state: "true"
          bulb_02_on_state: "true"

      - service: rest_command.light_update_master_bedroom_lamp_2_scene_homeassistant
        data:
          scene_id: "lWy-DMekfBnrLSu"
          username: !secret hue1_username
          color: '"ct": 454'
          brightness: '"bri": 25 }}'
      - service: rest_command.light_update_master_bedroom_lamp_2_scene_homeassistant
        data:
          scene_id: "bPMgpBKmlEUqMRc"
          username: !secret hue1_username
          color: '"ct": 454'
          brightness: '"bri": 25 }}'
  
      - service: rest_command.light_update_den_couch_lamp_1_scene_homeassistant
        data:
          scene_id: "XIpkjatAPzszIBY"
          username: !secret hue1_username
          color: '"ct": 454'
          brightness: '"bri": 25 }}'
          bulb_01_on_state: "true"
      - service: rest_command.light_update_den_couch_lamp_1_scene_homeassistant
        data:
          scene_id: "RYBofU8D0xfz-J6"
          username: !secret hue1_username
          color: '"ct": 454'
          brightness: '"bri": 25 }}'
          bulb_01_on_state: "true"
  
      - service: rest_command.light_update_den_couch_lamp_2_scene_homeassistant
        data:
          scene_id: "j10CCgzz0-DpX7w"
          username: !secret hue1_username
          color: '"ct": 454'
          brightness: '"bri": 25 }}'
          bulb_01_on_state: "true"
      - service: rest_command.light_update_den_couch_lamp_2_scene_homeassistant
        data:
          scene_id: "-vntxqGkxUZ4bZ8"
          username: !secret hue1_username
          color: '"ct": 454'
          brightness: '"bri": 25 }}'
          bulb_01_on_state: "true"

# ==================================================================================================
#
# Sensors
#
# ==================================================================================================
sensor:
  - platform: template
    sensors:
      circadian_temperature:
        friendly_name: "Circadian Color Temperature"
        value_template: "{{ state_attr('sensor.circadian_values','colortemp') | round(0) }}"
        unit_of_measurement: "°K"
  - platform: template
    sensors:
      circadian_brightness:
        friendly_name: "Circadian Brightness"
        value_template: "{{ state_attr('switch.circadian_lighting_circadian_light','brightness') }}"
        unit_of_measurement: "%"
  - platform: template
    sensors:
      circadian_mired:
        friendly_name: "Circadian Mired"
        value_template: "{{ 1000000 // state_attr('sensor.circadian_values','colortemp') | int }}"
  - platform: template
    sensors:
      circadian_brightness_value:
        friendly_name: "Circadian Brightness Value"
        value_template: "{{ states('sensor.circadian_brightness') | int * 254 // 100 }}"
        
switch:
  # ================================
  #
  # Basementroom
  #
  # ===============================
  - platform: circadian_lighting
    name: "circadian_light"
    lights_ct:
      - light.circadian_light
 
