# ======================================================================
#
# Den Lighting Configuration 
#
# ======================================================================

# ======================================================================
#
# Automations:
#
# ======================================================================
automation:
  # ======================================================================
  #
  # Light fixture: Den Couch Lamp Right
  #
  # Lights:
  #   - 
  #   - 
  #   - 
  #
  # Automations:
  #   - 
  #
  # ======================================================================
  - alias: '[Light] Den Couch Right: Circadian Lighting (With Brightness Adjustment)'
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        to: "Circadian"
      - platform: state
        entity_id: binary_sensor.light_den_couch_right_autobrightness
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
    action:
      - service: switch.turn_on
        entity_id:
          - switch.circadian_lighting_den_couch_right_with_brightness_adjustment
      - service: switch.turn_off
        entity_id:
          - switch.circadian_lighting_den_couch_right_without_brightness_adjustment

  - id: '1579090724953'
    alias: '[Light] Den Couch Right: Circadian Lighting (without Brightness adjust)'
    trigger:
      - platform: state
        entity_id: binary_sensor.light_den_couch_right_autobrightness
        to: 'off'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
    action:
      - service: switch.turn_on
        entity_id:
          - switch.circadian_lighting_den_couch_right_without_brightness_adjustment
      - service: switch.turn_off
        entity_id:
          - switch.circadian_lighting_den_couch_right_with_brightness_adjustment

  # ======================================================================
  #
  # Light fixture: Den Couch Lamp: Left
  #
  # Lights:
  #   - 
  #   - 
  #   - 
  #
  # Automations:
  #   - 
  #
  # ======================================================================
  - alias: '[Light] Den Couch Left: Circadian Lighting (with Brightness Adjustment)'
    initial_state: false
    trigger:
      platform: state
      entity_id: input_select.light_mode
      to: "Circadian"
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_den_couch_left_with_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_den_couch_left_without_brightness_adjustment

  - alias: '[Light] Den Couch Left: Circadian Lighting (without Brightness adjust)'
    initial_state: false
    trigger:
      platform: state
      entity_id: sensor.light_main_couch_left_brightness
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
        - condition: state
          entity_id: switch.circadian_lighting_den_couch_left_with_brightness_adjustment
          state: 'on'
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_den_couch_left_without_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_den_couch_left_with_brightness_adjustment


  # ======================================================================
  #
  # Light fixture: Fireplace Lights
  #
  # Lights:
  #   - 
  #   - 
  #   - 
  #
  # Automations:
  #   - 
  #
  # ======================================================================
  - alias: '[Light] Fireplace: Circadian Lighting (with Brightness Adjustment)'
    initial_state: false
    trigger:
      platform: state
      entity_id: input_select.light_mode
      to: "Circadian"
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_fireplace_with_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_fireplace_without_brightness_adjustment

  - alias: '[Light] Fireplace: Circadian Lighting (without Brightness adjust)'
    initial_state: false
    trigger:
      platform: state
      entity_id: sensor.light_main_fireplace_brightness
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
        - condition: state
          entity_id: switch.circadian_lighting_fireplace_with_brightness_adjustment
          state: 'on'
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_fireplace_without_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_fireplace_with_brightness_adjustment

  - alias: '[Light] Fireplace: Disable Circadian Lighting'
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        from: "Circadian"
    action:
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_fireplace_with_brightness_adjustment
            - switch.circadian_lighting_fireplace_without_brightness_adjustment

  # ======================================================================
  #
  # Light fixture: Main Sitting_Area Lights
  #
  # Lights:
  #   - 
  #   - 
  #   - 
  #
  # Automations:
  #   - 
  #
  # ======================================================================
  - alias: '[Light] Den Sitting Area: Circadian Lighting (with Brightness Adjustment)'
    initial_state: false
    trigger:
      platform: state
      entity_id: input_select.light_mode
      to: "Circadian"
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_den_sitting_area_with_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_den_sitting_area_without_brightness_adjustment

  - alias: '[Light] Den Sitting Area: Circadian Lighting (without Brightness adjust)'
    initial_state: false
    trigger:
      platform: state
      entity_id: sensor.light_den_sitting_area_brightness
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
        - condition: state
          entity_id: switch.circadian_lighting_den_sitting_area_with_brightness_adjustment
          state: 'on'
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_den_sitting_area_without_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_den_sitting_area_with_brightness_adjustment

  - alias: '[Light] Den Sitting Area: Disable Circadian Lighting'
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        from: "Circadian"
    action:
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_den_sitting_area_with_brightness_adjustment
            - switch.circadian_lighting_den_sitting_area_without_brightness_adjustment

  # ======================================================================
  #
  # Set Lighting Mode: Circadian (with Brightness adjustments)"
  #
  # - In the morning when the sun rises to 18 degrees below the horizon
  #   enable
  # ======================================================================
  - alias: '[Light] Tower Lamp Circadian Lighting (with Brightness Adjustment)'
    initial_state: false
    trigger:
      platform: state
      entity_id: input_select.light_mode
      to: "Circadian"
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_tower_lamp_with_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_tower_lamp_without_brightness_adjustment

  - alias: '[Light] Tower Lamp: Circadian Lighting (without Brightness adjust)'
    initial_state: false
    trigger:
      platform: state
      entity_id: sensor.light_tower_lamp_brightness
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
        - condition: state
          entity_id: switch.circadian_lighting_tower_lamp_with_brightness_adjustment
          state: 'on'
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_tower_lamp_without_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_tower_lamp_with_brightness_adjustment

  - alias: '[Light] Tower Lamp: Disable Circadian Lighting'
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        from: "Tower Lamp: Circadian (With_Brightness_Adjustment)"
      - platform: state
        entity_id: input_select.light_mode
        from: "Tower Lamp: Circadian (Without_Brightness_Adjustment)"
    condition:
      condition: or
      conditions:
        - condition: template
          value_template: "{{ not is_state('input_select.light_mode', 'Tower Lamp: Circadian (With_Brightness_Adjustment)') }}"
        - condition: template
          value_template: "{{ not is_state('input_select.light_mode', 'Tower Lamp: Circadian (Without_Brightness_Adjustment)') }}"
    action:
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_tower_lamp_with_brightness_adjustment
            - switch.circadian_lighting_tower_lamp_without_brightness_adjustment

# ======================================================================
#
# Binary Sensor
#
# ======================================================================
binary_sensor:
  - platform: template
    sensors:
      light_den_couch_right_autobrightness:
        friendly_name: "[Light] Den Couch Right Autobrightness"
        value_template: >-
          {{ ( states('sensor.light_den_couch_right_circadian_brightness') | int ) < ( states('sensor.light_den_couch_right_brightness_max') | int )
             and ( states('sensor.light_den_couch_right_circadian_brightness') | int  ) > ( states('sensor.light_den_couch_right_brightness_min') | int ) }}
        # attribute_templates:
        #   circadian_brightness: >-
        #     {{ state_attr('switch.circadian_lighting_den_couch_right_with_brightness_adjustment','brightness') | round(0) }}
        #   brightness: >-
        #     {% if is_state_attr('light.den_couch_lamp_right','brightness', 'unknown') %}
        #       100
        #     {% else %}
        #       {{ ( state_attr('light.den_couch_lamp_right','brightness') / 254 * 100 ) | int }}
        #     {% endif %}
        #   xy_color: >-
        #     {{ state_attr('light.den_couch_lamp_right','xy_color') }}

# ======================================================================
#
# Input Select
#
# ======================================================================

# ======================================================================
#
# Rest Command
#
# ======================================================================
# ======================================================================
#
# Group: Main Couch Right
# Scene_ID: nFeCiO75XJjnaml
# Lights: 6
#
# ======================================================================

# ======================================================================
#
# Group: Main Couch Left
# Scene_ID: Qr6JRXSt1GrBwHP
# Lights: 7
#
# ======================================================================

# ======================================================================
#
# Scenes:
#   - Darken Room
#   - Migraine
#
# ======================================================================
#scene:

# ======================================================================
#
#
#
# ======================================================================
sensor:
  - platform: template
    sensors:
      light_den_couch_right_circadian_brightness:
        friendly_name: "[Light] Den Couch Lamp Right: Circadian Brightness"
        value_template: "{{ state_attr('switch.circadian_lighting_den_couch_right_with_brightness_adjustment','brightness') | round(0) }}"
        unit_of_measurement: '%'
      light_den_couch_left_circadian_brightness:
        friendly_name: "[Light] Den Couch Lamp Left: Circadian Brightness"
        value_template: "{{ state_attr('switch.circadian_lighting_den_couch_left_with_brightness_adjustment','brightness') | round(0) }}"
        unit_of_measurement: '%'
      light_den_tower_lamp_circadian_brightness:
        friendly_name: "[Light] Den Tower Lamp: Circadian Brightness"
        value_template: "{{ state_attr('switch.circadian_lighting_den_tower_lamp_with_brightness_adjustment','brightness') | round(0) }}"
        unit_of_measurement: '%'
      light_den_fireplace_circadian_brigthness:
        friendly_name: "[Light] Den Fireplace Light: Circadian Brightness"
        value_template: "{{ state_attr('switch.circadian_lighting_den_fireplace_with_brightness_adjustment','brightness') | round(0) }}"
        unit_of_measurement: '%'
      light_den_sitting_area_circadian_brigthness:
        friendly_name: "[Light] Den Sitting Area: Circadian Brightness"
        value_template: "{{ state_attr('switch.circadian_lighting_den_sitting_area_with_brightness_adjustment','brightness') | round(0) }}"
        unit_of_measurement: '%'
      light_den_table_lamp_circadian_brigthness:
        friendly_name: "[Light] Den Table Lamp: Circadian Brightness"
        value_template: "{{ state_attr('switch.circadian_lighting_den_table_lamp_with_brightness_adjustment','brightness') | round(0) }}"
        unit_of_measurement: '%'
      light_den_couch_right_brightness:
        friendly_name: "[Light] Den Couch Lamp Right: Brightness"
        value_template:  "{{ ( state_attr('light.den_couch_lamp_right','brightness') / 254 * 100 ) | int }}"
        unit_of_measurement: '%'
      light_den_couch_right_brightness_max:
        friendly_name: "[Light] Den Couch Lamp Right: Max Brightness"
        value_template:  "{{ states('sensor.light_den_couch_right_brightness') | int + 4 }}"
        unit_of_measurement: '%'
      light_den_couch_right_brightness_min:
        friendly_name: "[Light] Den Couch Lamp Right: Min Brightness"
        value_template:  "{{ states('sensor.light_den_couch_right_brightness') | int - 4 }}"
        unit_of_measurement: '%'
      # light_den_couch_right_brightness_diff:
      #   friendly_name: "[Light] Den Couch Lamp Right: Brightness Difference"
      #   value_template:  "{{ states('sensor.light_den_couch_right_circadian_brightness') | int - states(sensor.light_den_couch_right_brightness) | int }}"
      #   unit_of_measurement: '%'
      # light_den_couch_right_brightness_abs:
      #   friendly_name: "[Light] Den Couch Lamp Right: Absolute Brightness Difference"
      #   value_template:  "{{ states('sensor.light_den_couch_right_circadian_brightness_diff') | abs }}"
      #   unit_of_measurement: '%'
      light_den_couch_left_brightness:
        friendly_name: "[Light] Den Couch Lamp Left: Brightness"
        value_template:  "{{ ( state_attr('light.den_couch_lamp_left','brightness') / 254 * 100 ) | int }}"
        unit_of_measurement: '%'
      light_den_tower_lamp_brightness:
        friendly_name: "[Light] Den Tower Lamp: Brightness"
        value_template:  "{{ ( state_attr('light.den_tower_lamp','brightness') / 254 * 100 ) | int }}"
        unit_of_measurement: '%'
      light_den_table_lamp_brightness:
        friendly_name: "[Light] Den Table Lamp: Brightness"
        value_template:  "{{ ( state_attr('light.den_table_lamp','brightness') / 254 * 100 ) | int }}"
        unit_of_measurement: '%'
      light_den_fireplace_brightness:
        friendly_name: "[Light] Den Fireplace Light: Brightness"
        value_template:  "{{ ( state_attr('light.den_fireplace','brightness') / 254 * 100 ) | int }}"
        unit_of_measurement: '%'
      light_den_sitting_area_brightness:
        friendly_name: "[Light] Den Sitting Area: Brightness"
        value_template:  "{{ ( state_attr('light.den_sitting_area','brightness') / 254 * 100 ) | int }}"
        unit_of_measurement: '%'

# ======================================================================
#
#
#
# ======================================================================
switch:
  # ==========================================
  #
  # Den
  #
  # =========================================
  - platform: circadian_lighting
    name: "Den Couch Right (without Brightness Adjustment)"
    lights_ct:
      - light.main_lamp_6
    disable_brightness_adjust: true

  - platform: circadian_lighting
    name: "Den Couch Right (with Brightness Adjustment)"
    lights_ct:
      - light.main_lamp_6
    disable_brightness_adjust: false
    min_brightness: 25

  - platform: circadian_lighting
    name: "Den Couch Left (without Brightness Adjustment)"
    lights_ct:
      - light.main_lamp_7
    disable_brightness_adjust: true

  - platform: circadian_lighting
    name: "Den Couch Left (with Brightness Adjustment)"
    lights_ct:
      - light.main_lamp_7
    disable_brightness_adjust: false
    min_brightness: 25

  - platform: circadian_lighting
    name: "Den Fireplace (without Brightness Adjustment)"
    lights_ct:
      - light.main_lamp_25
    disable_brightness_adjust: true

  - platform: circadian_lighting
    name: "Den Fireplace (with Brightness Adjustment)"
    lights_ct:
      - light.main_lamp_25
    disable_brightness_adjust: false
    min_brightness: 25

  - platform: circadian_lighting
    name: "Den Sitting Area (without Brightness Adjustment)"
    lights_ct:
      - light.main_lamp_8
    disable_brightness_adjust: true

  - platform: circadian_lighting
    name: "Den Sitting Area (with Brightness Adjustment)"
    lights_ct:
      - light.main_lamp_8
    disable_brightness_adjust: false
    min_brightness: 25

  - platform: circadian_lighting
    name: "Den Tower Lamp (without Brightness Adjustment)"
    lights_ct:
      - light.main_lamp_3
    disable_brightness_adjust: true

  - platform: circadian_lighting
    name: "Den Tower Lamp (with Brightness Adjustment)"
    lights_ct:
      - light.main_lamp_3
    disable_brightness_adjust: false
    min_brightness: 25

  - platform: circadian_lighting
    name: "Den Table Lamp (without Brightness Adjustment)"
    lights_ct:
      - light.main_lamp_27
    disable_brightness_adjust: true

  - platform: circadian_lighting
    name: "Den Table Lamp (with Brightness Adjustment)"
    lights_ct:
      - light.main_lamp_27
    disable_brightness_adjust: false
    min_brightness: 25
