# ======================================================================
#
# Dining Area Lighting Configuration
#
# Lights:
#   - light.main_lamp_
#   - light.main_lamp_
#   - light.main_lamp_
#   - light.main_lamp_
#   - light.main_lamp_
#   - light.main_lamp_
#   - light.main_lamp_
#   - light.main_lamp_
#   - light.main_lamp_
#   - light.main_lamp_
#   - light.main_lamp_
#
# Light Groups:
#   - light.den_couch_lamp_1
#   - light.den_couch_lamp_2
#   - light.den_ceiling
#   - light.den_fireplace
#   - light.den_tower_lamp
#   - light.den_table_lamp
#
# ======================================================================

# ======================================================================
#
# Automations:
#
# ======================================================================
automation:
  # ======================================================================
  #
  # Light fixture: Main Dining Lights
  #
  # Lights:
  #   - 
  #   - 
  #   - 
  #
  # Automations:
  #   - 
  #
  # ======================================================================
  - alias: "[Light] Dining Area Ceiling: Circadian Lighting (with Brightness Adjustment)"
    initial_state: false
    trigger:
      platform: state
      entity_id: input_select.light_mode
      to: "Circadian"
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_dining_area_ceiling_with_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_dining_area_ceiling_without_brightness_adjustment

  - alias: "[Light] Dining Area Ceiling: Circadian Lighting (without Brightness adjust)"
    initial_state: false
    trigger:
      platform: state
      entity_id: binary_sensor.light_dining_area_ceiling_autobrightness
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_dining_area_ceiling_without_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_dining_area_ceiling_with_brightness_adjustment

# ======================================================================
#
# Binary Sensor
#
# ======================================================================
binary_sensor:
  - platform: template
    sensors:
      light_dining_area_ceiling_autobrightness:
        friendly_name: "[Light] Dining Area Ceiling Autobrightness"
        value_template: >-
          {{ ( states("sensor.circadian_brightness") | int ) < ( state_attr("binary_sensor.light_dining_area_ceiling_autobrightness", "brightness_max") | int )
             and ( states("sensor.circadian_brightness") | int ) > ( state_attr("binary_sensor.light_dining_area_ceiling_autobrightness", "brightness_min") | int ) }}
        attribute_templates:
          brightness: >-
            {% if state_attr("light.dining_area_ceiling", "brightness") == None or
               is_state_attr("light.dining_area_ceiling", "brightness", "unknown")  or
               is_state("light.dining_area_ceiling", "off") %}
              100
            {% else %}
              {{ ( state_attr("light.dining_area_ceiling","brightness") / 254 * 100 ) | int }}
            {% endif %}
          brightness_max: >-
            {{ state_attr("binary_sensor.light_dining_area_ceiling_autobrightness", "brightness") | int + 4 }}
          brightness_min: >-
            {{ state_attr("binary_sensor.light_dining_area_ceiling_autobrightness", "brightness") | int - 4 }}
          xy_color: >-
            {{ state_attr("light.dining_area_ceiling","xy_color") }}
          color_temp: >-
            {{ state_attr("light.dining_area_ceiling","color_temp") }}

# ======================================================================
#
# Scenes:
#
# ======================================================================
#scene:

# ======================================================================
#
#
#
# ======================================================================
# sensor:
#   - platform: template
#     sensors:
#       light_dining_circadian_brigthness:
#         friendly_name: "[Light] Dining: Circadian Brightness"
#         value_template: "{{ state_attr("switch.circadian_lighting_dining_with_brightness_adjustment","brightness") | round(0) }}"
#         unit_of_measurement: "%"
#       light_dining_brightness:
#         friendly_name: "[Light] Dining: Brightness"
#         value_template:  "{{ ( state_attr("light.dining","brightness") / 254 * 100 ) | int }}"
#         unit_of_measurement: "%"

# ======================================================================
#
# Switches
#
# ======================================================================
switch:
  # ==========================================
  #
  # Main
  #
  # =========================================
  - platform: circadian_lighting
    name: "Dining Area Ceiling (without Brightness Adjustment)"
    lights_ct:
      - light.dining_area_ceiling
    disable_brightness_adjust: true

  - platform: circadian_lighting
    name: "Dining Area Ceiling (with Brightness Adjustment)"
    lights_ct:
      - light.dining_area_ceiling
    disable_brightness_adjust: false
    min_brightness: 1
