# ======================================================================
#
# Entryway
#
# Lights:
#   light.main_lamp_13: Entryway Ceiling Lightbulb
#
# Light Groups:
#   - light.den_couch_lamp_1
#   - light.den_couch_lamp_2
#   - light.den_ceiling
#   - light.den_fireplace
#   - light.den_tower_lamp
#   - light.den_table_lamp
#
# ======================================================================

# ======================================================================
#
# Automations:
#
# ======================================================================
automation:
  # ====================================================================
  #
  # Light fixture: Entryway Ceiling Lights
  #
  # Lights:
  #   - 
  #   - 
  #   - 
  #
  # Automations:
  #   - 
  #
  # ====================================================================
  - alias: "[Light] Entryway Ceiling: Circadian Lighting (with Brightness Adjustment)"
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        to: "Circadian"
      - platform: state
        entity_id: binary_sensor.light_entryway_ceiling_autobrightness
        to: "off"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_entryway_with_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_entryway_without_brightness_adjustment

  - alias: "[Light] Entryway Ceiling: Circadian Lighting (without Brightness adjust)"
    initial_state: false
    trigger:
      - platform: state
        entity_id: binary_sensor.light_entryway_ceiling_autobrightness
        to: "off"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
        - condition: state
          entity_id: switch.circadian_lighting_entryway_with_brightness_adjustment
          state: "on"
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_entryway_without_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_entryway_with_brightness_adjustment

# ======================================================================
#
# Binary Sensor
#
# ======================================================================
binary_sensor:
  - platform: template
    sensors:
      light_entryway_ceiling_autobrightness:
        friendly_name: "[Light] Entryway Ceiling Autobrightness"
        value_template: >-
          {{ ( states("sensor.circadian_brightness") | int ) < ( state_attr("binary_sensor.light_entryway_ceiling_autobrightness", "brightness_max") | int )
             and ( states("sensor.circadian_brightness") | int ) > ( state_attr("binary_sensor.light_entryway_ceiling_autobrightness", "brightness_min") | int ) }}
        attribute_templates:
          brightness: >-
            {% if state_attr("light.entryway_ceiling", "brightness") == None or
               is_state_attr("light.entryway_ceiling", "brightness", "unknown")  or
               is_state("light.entryway_ceiling", "off") %}
              {{ ( states("sensor.circadian_brightness") | int ) }}
            {% else %}
              {{ ( state_attr("light.entryway_ceiling","brightness") / 254 * 100 ) | int }}
            {% endif %}
          brightness_max: >-
            {{ state_attr("binary_sensor.light_entryway_ceiling_autobrightness", "brightness") | int + 4 }}
          brightness_min: >-
            {{ state_attr("binary_sensor.light_entryway_ceiling_autobrightness", "brightness") | int - 4 }}
          xy_color: >-
            {{ state_attr("light.entryway","xy_color") }}
          color_temp: >-
            {{ state_attr("light.entryway","color_temp") }}

# ======================================================================
#
# Scenes:
#   - Darken Room
#   - Migraine
#
# ======================================================================
#scene:

# ======================================================================
#
#
#
# ======================================================================
# sensor:
#   - platform: template
#     sensors:
#       light_entryway_circadian_brigthness:
#         friendly_name: "[Light] Entryway: Circadian Brightness"
#         value_template: "{{ state_attr("switch.circadian_lighting_entryway_with_brightness_adjustment","brightness") | round(0) }}"
#         unit_of_measurement: "%"
#       light_entryway_brightness:
#         friendly_name: "[Light] Entryway: Brightness"
#         value_template:  "{{ ( state_attr("light.entryway","brightness") / 254 * 100 ) | int }}"
#         unit_of_measurement: "%"

# ======================================================================
#
# Switches:
#   - Entryway
# 
#
# ======================================================================
switch:
  # ====================================================================
  #
  # Entryway
  # Without Brightnes adjustment
  #
  # 
  #
  # ====================================================================
  - platform: circadian_lighting
    name: "Entryway Ceiling (without Brightness Adjustment)"
    lights_ct:
      - light.main_lamp_13
    disable_brightness_adjust: true

  - platform: circadian_lighting
    name: "Entryway Ceiling (with Brightness Adjustment)"
    lights_ct:
      - light.main_lamp_13
    disable_brightness_adjust: false
    min_brightness: 1
