# ======================================================================
#
# Living Area Lights
#
# Lights:
#   light.main_lamp_10: Kitchen Ceiling Lightbulb
#   light.main_lamp_24: Kitchen Island Ceiling Lightbulb
#
# Light Groups:
#   - light.den_couch_lamp_1
#   - light.den_couch_lamp_2
#   - light.den_ceiling
#   - light.den_fireplace
#   - light.den_tower_lamp
#   - light.den_table_lamp 
#
# ======================================================================

# ======================================================================
#
# Automations:
#
# ======================================================================
automation:
  # ======================================================================
  #
  # Light fixture: Main Living_Area Lights
  #
  # Lights:
  #   - 
  #   - 
  #   - 
  #
  # Automations:
  #   - 
  #
  # ======================================================================
  - alias: '[Light] Living Area: Circadian Lighting (with Brightness Adjustment)'
    initial_state: false
    trigger:
      platform: state
      entity_id: input_select.light_mode
      to: "Circadian"
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_living_area_with_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_living_area_without_brightness_adjustment

  - alias: '[Light] Living Area: Circadian Lighting (without Brightness adjust)'
    initial_state: false
    trigger:
      platform: state
      entity_id: sensor.light_living_area_brightness
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
        - condition: state
          entity_id: switch.circadian_lighting_living_area_with_brightness_adjustment
          state: 'on'
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_living_area_without_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_living_area_with_brightness_adjustment

  - alias: '[Light] Living Area: Disable Circadian Lighting'
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        from: "Circadian"
    action:
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_living_area_with_brightness_adjustment
            - switch.circadian_lighting_living_area_without_brightness_adjustment

# ======================================================================
#
# Binary Sensor
#
# ======================================================================
#binary_sensor:
#  - platform: template
#    sensors:
#      main_couch_right_autobrightness:
#        friendly_name: "Main Couch Right Autobrightness"
#        value_template: "{{ states('sensor.lights_main_couch_lamp_right_circadian_brightness') == states('sensor.lights_main_couch_lamp_right_brightness') }}"

# ======================================================================
#
# Scenes:
#   - Darken Room
#   - Migraine
#
# ======================================================================
#scene:

# ======================================================================
#
#
#
# ======================================================================
# sensor:
#   - platform: template
#     sensors:
#       light_living_area_circadian_brigthness:
#         friendly_name: "[Light] Main Living Area: Circadian Brightness"
#         value_template: "{{ state_attr('switch.circadian_lighting_living_with_brightness_adjustment','brightness') | round(0) }}"
#         unit_of_measurement: '%'
#       light_living_area_brightness:
#         friendly_name: "[Light] Main Living Area: Brightness"
#         value_template:  "{{ ( state_attr('light.living_area','brightness') / 254 * 100 ) | int }}"
#         unit_of_measurement: '%'

# ======================================================================
#
#
#
# ======================================================================
switch:
  # ==========================================
  #
  # Main
  #
  # =========================================
  - platform: circadian_lighting
    name: "Living Area (without Brightness Adjustment)"
    lights_ct:
      - light.main_lamp_26
    disable_brightness_adjust: true

  - platform: circadian_lighting
    name: "Living Area (with Brightness Adjustment)"
    lights_ct:
      - light.main_lamp_26
    disable_brightness_adjust: false
    min_brightness: 25
