# ======================================================================
#
# Back Bedroom
#
#
#
# ======================================================================
automation:
  # ======================================================================
  #
  # Light fixture: Master Bathroom (Inner)
  #
  # Lights:
  #   - 
  #   - 
  #   - 
  #
  # Automations:
  #   - 
  #
  # ======================================================================
  - alias: '[Lights] Master Bathroom (Inner): Circadian Lighting (with Brightness Adjustment)'
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        to: "Circadian"
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_master_bathroom_inner_with_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_master_bathroom_inner_without_brightness_adjustment

  - alias: '[Lights] Master Bathroom (Inner): Circadian Lighting (without Brightness adjust)'
    initial_state: false
    trigger:
      - platform: state
        entity_id: sensor.light_master_bathroom_inner_brightness
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
        - condition: state
          entity_id: switch.circadian_lighting_master_bathroom_inner_with_brightness_adjustment
          state: 'on'
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_master_bathroom_inner_without_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_master_bathroom_inner_with_brightness_adjustment

  - alias: '[Lights] Master Bathroom (Inner): Disable Circadian Lighting'
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        from: "Circadian"
    action:
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_master_bathroom_inner_with_brightness_adjustment
            - switch.circadian_lighting_master_bathroom_inner_without_brightness_adjustment

  # ======================================================================
  #
  # Light fixture: Master Bathroom (Outer)
  #
  # Lights:
  #   -
  #
  # Automations:
  #   - 
  #
  # ======================================================================
  - alias: '[Lights] Master Bathroom (Outer): Circadian Lighting (with Brightness Adjustment)'
    initial_state: false
    trigger:
      platform: state
      entity_id: input_select.light_mode
      to: "Circadian"
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_master_bathroom_outer_with_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_master_bathroom_outer_without_brightness_adjustment

  - alias: '[Lights] Master Bathroom (Outer): Circadian Lighting (without Brightness adjust)'
    initial_state: false
    trigger:
      - platform: state
        entity_id: sensor.light_master_bathroom_outer_brightness
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state('input_select.light_mode', 'Circadian') }}"
        - condition: state
          entity_id: switch.circadian_lighting_master_bathroom_outer_with_brightness_adjustment
          state: 'on'
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.circadian_lighting_master_bathroom_outer_without_brightness_adjustment
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_master_bathroom_outer_with_brightness_adjustment

  - alias: '[Lights] Master Bathroom (Outer): Disable Circadian Lighting'
    initial_state: false
    trigger:
      - platform: state
        entity_id: input_select.light_mode
        from: "Circadian"
    action:
      - service: switch.turn_off
        data:
          entity_id:
            - switch.circadian_lighting_master_bathroom_outer_with_brightness_adjustment
            - switch.circadian_lighting_master_bathroom_outer_without_brightness_adjustment

# ======================================================================
#
#
#
# ======================================================================
input_select:
  hue_master_bathroom_inner:
    name: "[Light] Hue Master Bathroom (Inner) Scene"
    icon: mdi:palette
    initial: 'Circadian'
    options:
      - Arctic aurora
      - Sevanna sunset
      - Tropical twilight
      - Spring blossom
      - Relax
      - Read
      - Concentrate
      - Energize
      - Bright
      - Dimmed
      - Nightlight
      - Motown
      - Midsomer Sun
      - Midwinter
      - Ocean Dawn
      - Emerald Isle
      - Mountain Breeze
      - Spring lake
      - Moonlight
      - Starlight
      - Soho
      - Golden Pond
      - Frosty Dawn
      - Fairfax
      - Autumn Gold
      - Palm Beach
      - Lake Mist
      - Chinatown
      - Tokyo
      - Sunday Morning
      - Ibiza
      - Nebula
      - Galaxy
      - Ruby Glow
      - Winter mountain
      - Blue Lagoon
      - Honolulu
      - Lake Placid
      - Osaka
      - Sundowner
      - Blood Moon
      - Circadian
      - Night Mode
      - Migraine

# ======================================================================
#
#
#
# ======================================================================
#rest_command:
# ======================================================================
#
# Scene_ID: NcXhhhoJnaJIWLa
#
# ======================================================================
#  update_hue_scene_master_bath_inner:
#    url: https://10.3.1.1/api/e2Du8WsQfAUiZPrtb-6qkAbvnoTKq3degi6iGbtf/scenes/NcXhhhoJnaJIWLa/lightstates/
#    method: put
#    payload: "{ '12': { 'on': true, 'bri': <circadian_brightness>, 'ct': <circadian_ct> }, { '17': { 'on': true, 'bri': <circadian_brightness>, 'ct': <circadian_ct> }, { '19': { 'on': true, 'bri': <circadian_brightness>, 'ct': <circadian_ct> }"

# ======================================================================
#
#
#
# ======================================================================
sensor:
  - platform: template
    sensors:
      light_master_bathroom_inner_circadian_brightness:
        friendly_name: "[Light] Master Bathroom (Inner): Circadian Brightness"
        value_template: "{{ state_attr('switch.circadian_lighting_master_bathroom_inner_with_brightness_adjustment','brightness') | round(0) }}"
        unit_of_measurement: '%'
      light_master_bathroom_outer_circadian_brightness:
        friendly_name: "[Light] Master Bathroom (Outer): Circadian Brightness"
        value_template: "{{ state_attr('switch.circadian_lighting_master_bathroom_outer_with_brightness_adjustment','brightness') | round(0) }}"
        unit_of_measurement: '%'
      light_master_bathroom_inner_brightness:
        friendly_name: "[Light] Master Bathroom (Inner): Brightness"
        value_template:  "{{ ( state_attr('light.master_bath_inner','brightness') / 254 * 100 ) | int }}"
        unit_of_measurement: '%'
      light_master_bathroom_outer_brightness:
        friendly_name: "[Light] Master Bathroom (Outer): Brightness"
        value_template:  "{{ ( state_attr('light.master_bath_outer','brightness') / 254 * 100 ) | int }}"
        unit_of_measurement: '%'

#  =====================================================================
#
#  Scenes:
#
#
# ======================================================================
scene:
  - id: '1576892383155'
    name: "[Light] Master Bathroom (Inner): Darken Room"
    entities:
      light.hue_lamp_12:
        friendly_name: "Master Bathroom Center"
        brightness_pct: 25
        rgb_color:
        - 255
        - 0
        - 0
        state: 'on'
      light.hue_lamp_17:
        friendly_name: "Master Bathroom Left"
        state: 'off'
      light.hue_lamp_19:
        friendly_name: "Master Bathroom Right"
        state: 'off'

# ======================================================================
#
#
#
# ======================================================================
switch:
  # =====================================
  #
  # Master Bathroom
  #
  # =====================================
  - platform: circadian_lighting
    name: "Master Bathroom (Inner) (without Brightness Adjustment)"
    lights_ct:
      - light.hue_lamp_17
      - light.hue_lamp_12
      - light.hue_lamp_19
    disable_brightness_adjust: true

  - platform: circadian_lighting
    name: "Master Bathroom (Inner) (with Brightness Adjustment)"
    lights_ct:
      - light.hue_lamp_17
      - light.hue_lamp_12
      - light.hue_lamp_19
    disable_brightness_adjust: false
    min_brightness: 50

  - platform: circadian_lighting
    name: "Master Bathroom (Outer) (without Brightness Adjustment)"
    lights_ct:
      - light.hue_lamp_32
    disable_brightness_adjust: true

  - platform: circadian_lighting
    name: "Master Bathroom (Outer) (with Brightness Adjustment)"
    lights_ct:
      - light.hue_lamp_32
    disable_brightness_adjust: false
    min_brightness: 50
