- platform: pirateweather
  api_key: !secret pirateweather
  scan_interval: '00:30:00'
  forecast:
    - 0
  monitored_conditions:
    - summary
    - icon
    - temperature
    - precip_type
    - precip_intensity
    - precip_probability
    - precip_accumulation
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_gust
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_high
    - temperature_low
    - apparent_temperature_high
    - apparent_temperature_low
    - precip_intensity_max
    - uv_index
    - moon_phase
    - nearest_storm_distance
    - nearest_storm_bearing

- platform: pirateweather
  api_key: !secret pirateweather
  scan_interval: '06:00:00'
  forecast:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  monitored_conditions:
    - summary
    - icon
    - temperature
    - precip_type
    - precip_intensity
    - precip_probability
    - precip_accumulation
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_gust
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_high
    - temperature_low
    - apparent_temperature_high
    - apparent_temperature_low
    - precip_intensity_max
    - uv_index
    - moon_phase
    - nearest_storm_distance
    - nearest_storm_bearing
    #time_of_day:

- platform: moon

# Seasons
- platform: season
  type: astronomical
