- platform: mqtt
  state_topic: "owntracks/user0001/phone"
  name: "user0001_phone_battery"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'
  device_class: battery

- platform: mqtt
  state_topic: "owntracks/user0002/phone"
  name: "user0002_phone_battery"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'
  device_class: battery

- platform: mqtt
  state_topic: "sensors/Hestia/sensehat/temperature"
  name: "hestia_sensehat_temperature"

- platform: mqtt
  state_topic: "sensors/Hestia/sensehat/humidity"
  name: "hestia_sensehat_humidity"

- platform: mqtt
  state_topic: "sensors/Hestia/sensehat/pressure"
  name: "hestia_sensehat_pressure"

