- platform: mqtt
  state_topic: "owntracks/user0001/phone"
  name: "user0001_phone_battery"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'
  device_class: battery

- platform: mqtt
  name: "hestia_sensehat_temp_c"
  state_topic: "homeassistant/sensor/hestia/sensehat/state"
  value_template: "{{ value_json.temperature_celcius }}"
  unit_of_measurement: "°C"
  device_class: "temperature"

- platform: mqtt
  name: "hestia_sensehat_temp_f"
  state_topic: "homeassistant/sensor/hestia/sensehat/state"
  value_template: "{{ value_json.temperature_fahrenheit }}"
  unit_of_measurement: "°F"
  device_class: "temperature"

- platform: mqtt
  name: "hestia_sensehat_pressure_mbar"
  state_topic: "homeassistant/sensor/hestia/sensehat/state"
  value_template: "{{ value_json.pressure_mbar }}"
  unit_of_measurement: "mbar"
  device_class: "pressure"

- platform: mqtt
  name: "hestia_sensehat_pressure_inhg"
  state_topic: "homeassistant/sensor/hestia/sensehat/state"
  value_template: "{{ value_json.pressure_inhg }}"
  unit_of_measurement: "inHg"

- platform: mqtt
  state_topic: "homeassistant/sensor/hestia/sensehat/state"
  name: "hestia_sensehat_humidity"
  value_template: "{{ value_json.humidity }}"
  unit_of_measurement: "%"

- platform: mqtt
  state_topic: "sensors/atlas/sensors/Battery/value"
  unit_of_measurement: "%"
  name: "atlas battery"

- platform: mqtt
  state_topic: "sensors/atlas/sensors/ath10k_hwmon_1/value"
  name: "atlas cpu temperature"
