- platform: template
  sensors:
    thermostat_temperature:
      value_template: "{{ state_attr('climate.thermostat','current_temperature') | round(1) }}"
      unit_of_measurement: '°F'
    thermostat_humidity:
      value_template: "{{ state_attr('climate.thermostat','current_humidity') | round(1) }}"
      unit_of_measurement: '%'

- platform: template
  sensors:
    sensehat_temperature:
      value_template: "{{ states('sensor.hestia_sensehat_temp_f') }}"
      unit_of_measurement: "°F"
    sensehat_pressure:
      value_template: "{{ states('sensor.hestia_sensehat_pressure_inHg') }}"
      unit_of_measurement: 'inHg'
    sensehat_humidity:
      value_template: "{{ states('sensor.hestia_sensehat_humidity') }}"
      unit_of_measurement: '%'
   openweathermap_pressure_inhg:
     friendly_name: "OpenWeatherMap Pressure"
     value_template: '{{ states("sensor.openweathermap_pressure") | float / 33.864 | round(2) }}'
     unit_of_measurement: 'inHg'
   openweathermap_wind_speed_mph:
     friendly_name: "OpenWeatherMap Wind Speed"
     value_template: '{{ states("sensor.openweathermap_wind_speed") | float * 2.236936 | round(2) }}'
     unit_of_measurement: 'mph'
   nws_visibility:
     friendly_name: "NWS Visibility"
     value_template: "{{ state_attr('weather.kahn_hourly','visibility') }}"
     unit_of_measurement: "mi"
   nws_precip_probability:
     friendly_name: "NWS Precipitation Probability"
     value_template: "{{ state_attr('weather.kahn_hourly','forecast')[0]['precipitation_probability'] }}"
     unit_of_measurement: "%"
