---
# ==================================================================================================
#
# Holiday: Christmas
#
# ==================================================================================================
automation:
  - id: "2b71d034-526c-448f-a444-c8ac87dcac94"
    alias: "[Christmas] Enable Automations"
    description: ""
    trigger:
      - event: start
        platform: homeassistant
    condition: []
    action:
      - scene: scene.christmas_enable_light_automations

# ==================================================================================================
#
# Input DateTime
#
# ==================================================================================================
input_datetime:
  christmas_lights_morning:
    name: "Christmas Lights On Time"
    has_date: false
    has_time: true
  christmas_lights_evening:
    name: "Christmas Lights Off Time"
    has_date: false
    has_time: true

# ==================================================================================================
#
# Scenes
#
# ==================================================================================================
scene:
  - id: "832aa014-6c04-44d8-a244-99501f907a18"
    name: "[Christmas] Enable Light Automations"
    entities:
      automation.christmas_activate_christmas_lights_off_scene:
        state: 'on'
      automation.christmas_activate_christmas_lights_on_scene:
        state: 'on'
      automation.christmas_activate_christmas_outdoor_lights_off_scene:
        state: 'on'
      automation.christmas_activate_christmas_outdoor_lights_on_scene:
        state: 'on'
