---
# ==================================================================================================
#
# Automations
#
# ==================================================================================================
automation:
  - id: "51b89d95-4cd8-4834-acba-bfb796c119eb"
    alias: "[Christmas] Activate 'Indoor Lights On' Scene"
    description: "Turns on indoor Christmas lights at time specified in input_datetime.christmas_lights_morning"
    trigger:
      - platform: time
        at: input_datetime.christmas_lights_morning
    condition: []
    action:
      - scene: scene.christmas_lights_on
    mode: single

  - id: "b11661ac-4aaa-42cd-9b95-af4e99e76d60"
    alias: "[Christmas] Activate 'Indoor Lights Off' Scene"
    description: "Turns off indoor lights at time specified in inupt_datetime.christmas_lights_evening"
    trigger:
      - platform: time
        at: input_datetime.christmas_lights_evening
    condition: []
    action:
      - scene: scene.christmas_lights_off
    mode: single

  - id: "678b965c-45ae-45df-b5fc-6f1b5aa7fdfb"
    alias: "[Christmas] Activate 'Outdoor Lights On' Scene"
    description: "Turns on outdoor Christmas lights."
    trigger:
      - platform: sun
        event: sunset
      - platform: time
        at: input_datetime.christmas_lights_morning
    condition:
      - condition: state
        entity_id: "sun.sun"
        state: "below_horizon"
    action:
      - scene: scene.christmas_outdoor_lights_on
    mode: single

  - id: "7670c95b-1283-4a5d-8bc4-ad6977d5fa49"
    alias: "[Christmas] Activate 'Outdoor Lights Off' Scene"
    description: "Turns off outdoor Christmas lights."
    trigger:
      - platform: sun
        event: sunrise
    condition: []
    action:
      - scene: scene.christmas_outdoor_lights_off
    mode: single

# ==================================================================================================
#
# Scenes
#
# ==================================================================================================
scene:
  - id: "fb6cec0b-c060-4f4c-9554-3c65a12cd5ce"
    name: "[Christmas] Indoor Lights On"
    entities:
      # switch.mf1_greatroom_zwave8_switch:
      #   state: "on"
      # switch.mf1_den_zwave34_switch:
      #   state: "on"
      light.twinkly_a8a6fd:
        state: "on"
      light.twinkly_68e925:
        state: "on"

  - id: "d7f5be4d-0de2-45b4-90d6-e9c47605c9c8"
    name: "[Christmas] Indoor Lights Off"
    entities:
      # switch.mf1_greatroom_zwave8_switch:
      #   state: "on"
      # switch.mf1_den_zwave34_switch:
      #   state: "on"
      light.twinkly_a8a6fd:
        state: "off"
      light.twinkly_68e925:
        state: "off"

  - id: "c881541b-8a2a-4d90-9e49-7771c7c1e7fe"
    name: "[Christmas] Outdoor Lights On"
    entities:
      switch.by_zwave7_switch:
        state: "on"

  - id: "74176d81-64ef-4997-94c2-ca6421d60f5a"
    name: "[Christmas] Outdoor Lights Off"
    entities:
      switch.by_zwave7_switch:
        state: "off"
