automation:
  - id: "1606841326257"
    alias: "[Christmas] Activate 'Christmas Lights On' Scene"
    initial_state: false
    description: "Turns on all Christmas lights at astronomical dawn."
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        above: -18
    condition: []
    action:
      - scene: scene.christmas_lights_on
    mode: single

  - id: "1576628018411"
    alias: "[Christmas] Activate 'Christmas Lights Off' Scene"
    initial_state: false
    description: ""
    trigger:
      - platform: time
        at: "21:00:00"
    condition: []
    action:
      - scene: scene.christmas_lights_off
    mode: single

  - id: "1607003903288"
    alias: "[Christmas] Activate 'Christmas Outdoor Lights On' Scene"
    initial_state: false
    description: ""
    trigger:
      - platform: sun
        event: sunset
    condition: []
    action:
      - scene: scene.christmas_outdoor_lights_on
    mode: single

  - id: "1606782092296"
    alias: "[Christmas] Activate 'Christmas Outdoor Lights Off' Scene"
    initial_state: false
    description: ""
    trigger:
      - platform: sun
        event: sunrise
    condition: []
    action:
      - scene: scene.christmas_outdoor_lights_off
    mode: single

scene:
  - id: "1606841163904"
    name: "[Christmas] Lights On"
    entities:
      switch.28169_plug_in_one_outlet_smart_switch_switch:
        node_id: 8
        friendly_name: "28169 Plug-In One-Outlet Smart Switch: Switch"
        state: "on"
      switch.14284_outdoor_smart_switch_switch:
        node_id: 7
        friendly_name: "Plug-in Outdoor Smart Switch: Switch"
        state: "on"

  - id: "1606782193777"
    name: "[Christmas] Lights Off"
    entities:
      switch.28169_plug_in_one_outlet_smart_switch_switch:
        node_id: 8
        friendly_name: "28169 Plug-In One-Outlet Smart Switch: Switch"
        state: "off"
      switch.14284_outdoor_smart_switch_switch:
        node_id: 7
        friendly_name: "Plug-in Outdoor Smart Switch: Switch"
        state: "off"

  - id: "1576958171165"
    name: "[Christmas] Outdoor Lights On"
    entities:
      switch.14284_outdoor_smart_switch_switch:
        node_id: 7
        friendly_name: "Plug-in Outdoor Smart Switch: Switch"
        state: "on"

  - id: "1606782269331"
    name: "[Christmas] Outdoor Lights Off"
    entities:
      switch.14284_outdoor_smart_switch_switch:
        node_id: 7
        friendly_name: "Plug-in Outdoor Smart Switch: Switch"
        state: "off"
