sensor:
  - unique_id: "5ed058c2-1299-4597-89ee-7847b36ff2d4"
    name: "Home01: Sensehat - Temp"
    state_topic: "homeassistant/sensor/home01/sensehat/state"
    value_template: "{{ value_json.temperature }}"
    unit_of_measurement: "°C"
    device_class: "temperature"

  - unique_id: "1117c980-2079-4546-8818-8613f53aa252"
    name: "Home01: Sensehat - Pressure"
    state_topic: "homeassistant/sensor/home01/sensehat/state"
    value_template: "{{ value_json.pressure }}"
    unit_of_measurement: "mbar"
    device_class: "pressure"

  - unique_id: "4e3c4a91-54fd-44db-a3b6-6deeeb2d4e01"
    name: "Home01: Sensehat - Humidity"
    state_topic: "homeassistant/sensor/home01/sensehat/state"
    value_template: "{{ value_json.humidity }}"
    unit_of_measurement: "%"

